### ISSUE TITLE
List of TODOs - Contributors welcome!

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#10]
This is being posted here for the sake of not having to create a commit on master every time I want to edit something. 

Please read the style and contributing guide for opening a pull request.
https://frc-docs.readthedocs.io/en/develop/contributing.html

[Getting started with the control system](https://wpilib.screenstepslive.com/s/currentCS/m/getting_started)
    OPEN - 2018 Game Data Details

[Other KOP Resources]
- In progress by @firecrafty

[Test Mode](https://wpilib.screenstepslive.com/s/3120/m/8564/l/87776-using-test-mode)
- Available

**Comment by CrispyBacon1999** [comment]
I'll take everything under the driver station section.

**Comment by firecrafty** [comment]
@CrispyBacon1999 Are you still planning on taking the driver station items? It doesn't look like you've done anything in your fork, and I'd be willing to take them if you aren't

**Comment by CrispyBacon1999** [comment]
@firecrafty If you're actively working on it, go for it. I can push what I have to my fork if you want.

**Comment by firecrafty** [comment]
I haven't started, if you're working on it, great.

**Comment by Daltz333** [comment]
@CrispyBacon1999 @firecrafty Any updates on your guys/gals sections?

**Comment by yellowjaguar5** [comment]
@CrispyBacon1999 @firecrafty Any updates on the driver station sections? If neither of you are working on it/started it, I can port it.

**Comment by yellowjaguar5** [comment]
@Daltz333 I'll take [Troubleshooting]

**Comment by yellowjaguar5** [comment]
@Daltz333 I'll take `2018 Game Data Details`

**Comment by DylanB5402** [comment]
@Daltz333, you still need someone to do test mode? Also, test mode is from the archived 2014 docs, does it still need to be ported?
