### ISSUE TITLE
Fix Speed Controller vs Motor Controller sitewide

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#1002]
Many documents are split on the terminology.  Will try to include notes indicating their equivalence but since first calls them all Motor Controllers in the game manual we should too!

**Comment by Daltz333** [comment]
@TheTripleV planned to develop something to enforce things like this

**Comment by AustinShalit** [comment]
In the code the object is called a `SpeedController` which is probably what is causing the discrepancy.
