### ISSUE TITLE
Tutorial on SendableChooser

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#102]
This might exist on ScreenSteps already. Should be investigated either way.

**Comment by yellowjaguar5** [comment]
Should this be added to the Using the Sendable interface page added in #133?

**Comment by Starlight220** [comment]
Hey @Daltz333 - is this still relevant/unresolved?
I can cobble together something for this, might need some help with cpp code samples but otherwise, I'll be fine.
And where should it be added?

**Comment by Daltz333** [comment]
This is still relevant, perhaps a new article in basic programming sampling autonomous picking with sendable chooser

**Comment by Starlight220** [comment]
It seems that this is done in #687, in [this file](https://github.com/wpilibsuite/frc-docs/pull/687/files#diff-a73b9cb8f790cf9f2aa205642bb0e80b). If that PR is stale/dead/stuck but the article we need is relatively ok, I can extract it to a different PR.

**Comment by Daltz333** [comment]
Correct, and that PR is mostly done, it just needs some review comments addressed and then it's good to go.

**Comment by yellowjaguar5** [comment]
I can definitely address the review comments in the next week, but @Starlight220 If you want to finish it up, let me know. I just don't want us to duplicate work.

**Comment by Starlight220** [comment]
@yellowjaguar5 - I won't be next to a computer from tomorrow morning until Sunday, so I won't be working on it until then. And if you finish up that PR and @Daltz333 reviews & merges it, I think that this issue can be closed. Therefore I suggest you bind that PR to this issue, so it'll be closed automatically when that PR resolves it.
