### ISSUE TITLE
Add page detailing community resources

### ISSUE THREAD

**Issue by cadandcookies** [wpilibsuite/frc-docs#103]
Since this is an excellent resource towards the the software and electronics components for FRC, it seems logical that it might also provide a stepping off point towards other community resources and assistance, particularly ones that provide real time (or quick) responses to individual questions, as this isn't something well suited to a static site.

Potential examples of resources that might be highlighted are the FRC Discord (particularly the #programming-discussion and #programming-help channels), Chief Delphi's Programming category, and The Compass Alliance's Call Center.

There would also likely need to be some sort of disclaimer on these.

**Comment by AustinShalit** [comment]
We can probably stick a link to the evergreen page here: https://www.firstinspires.org/resource-library/frc/supplemental-resources

**Comment by AustinShalit** [comment]
This is going to be handled by FIRST on the supplemental resources page.
