### ISSUE TITLE
Document GradleRIO capabilities

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/frc-docs#1030]
I can work on this, I just need some guidance as to structure. 
@Daltz333 - where should this be? I assume a section under Software Tools?
Also, what structure do we want this in? A doc outlining every task might be appropriate, but it might be a bit redundant because of `./gradlew tasks`. Maybe denote only the main useful tasks? 
There are a few tasks that help configure CLion - is there a problem documenting it on frc-docs, given that CLion support is unofficial?

**Comment by Daltz333** [comment]
I'd like to hear @ThadHouse input on this. I'd be more inclined to leave this in the GradleRIO readme, as we don't super support anything outside of VS Code.

**Comment by Daltz333** [comment]
``./gradlew tasks`` should be documented, now in the new Advanced GradleRIO section.

We should clarify that some of the tasks are unsupported (clion, vs, etc)
