### ISSUE TITLE
CAN Addressing should be in an advanced section

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#105]
CAN Device Addressing should be in some sort of advanced or vendor specific section. It's not for general team usage.

**Comment by ThadHouse** [comment]
I would prefer advanced. That was part of the reason for creating the CAN API class in wpilib, my goal was to write an arduino demo, but I never got around to that.

**Comment by yellowjaguar5** [comment]
This file got moved in #219 and I opened #234 to move the accompanying document.

**Comment by yellowjaguar5** [comment]
This document was removed in #234. Can this issue be closed?
