### ISSUE TITLE
Document font requirements on Linux

### ISSUE THREAD

**Issue by RyanHir** [wpilibsuite/frc-docs#1070]
https://docs.wpilib.org/en/latest/docs/zero-to-robot/step-2/wpilib-setup.html#extracting-the-installer

Currently the Linux installation presumes that MS (or mock) fonts are installed and will crash instead. That issue is being tracked at wpilibsuite/WPILibInstaller-Avalonia/issues/153

While this would affect a small portion of users, I believe it would be beneficial to say that the extra package is required for installation in case of problems.

**Comment by calcmogul** [comment]
That package wasn't actually required for me. I'm trying to find out which font the installer is picking up instead.

**Comment by Daltz333** [comment]
Not sure if we should document it if we're going to fix it. Maybe something in known-issues

**Comment by Daltz333** [comment]
We can't actually reproduce this? Can you give exact steps on how to reproduce it?

- What distro (do note we only support Ubuntu, but I can add a note for more advanced users)
- Any special steps that was done.

If the system is heavily customized, I don't think this is really something we should spend time documenting.

**Comment by RyanHir** [comment]
This was awhile ago with a very minimal arch system, I have since moved to Gnome 3 on Arch and the project works there now. I presume a font package or something changed things. Thinking about it now, it probably is not worth documenting other than a small notice like you said.
