### ISSUE TITLE
Romi Hardware - standoff location drawing missing?

### ISSUE THREAD

**Issue by samneff72** [wpilibsuite/frc-docs#1072]
Step 7 Instructions reference an image, no image is provided. Hard to figure out where these standoffs go. 

https://docs.wpilib.org/en/latest/docs/romi-robot/hardware.html

**Comment by jasondaming** [comment]
@zhiquanyeo I am assuming this image is the one that was supposed to go here:
![image](https://user-images.githubusercontent.com/15695521/104081787-9fd0d480-51f6-11eb-8d8b-87780fd2066a.png)

I found it [here](https://www.pololu.com/docs/0J68/6)

**Comment by zhiquanyeo** [comment]
I was looking at that one, but it's a little confusing since it doesn't show the mounting holes relative to the Romi32U4 board

**Comment by zhiquanyeo** [comment]
![image](https://user-images.githubusercontent.com/2805133/104082294-f7753d00-5202-11eb-8926-2085053cddfc.png)

Maybe something like this?
