### ISSUE TITLE
Characterization python should point to Python 3.7 installation

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#1095]
Python 3.9 *is not* supported. Update the link

**Comment by sciencewhiz** [comment]
It does say 3.7, do you mean the link should point to 3.7? Is there a way to do that without a specific point release? https://www.python.org/downloads/release/python-379/ is the latest point release now, but may not be in the future.

**Comment by Daltz333** [comment]
Yes, link should point to 3.7, and I'm not sure on pointing to the latest of 3.7

**Comment by TheTripleV** [comment]
frc-characterization metadata could also be changed so it will only install on (3.7) or (3.7 and 3.8).

**Comment by jasondaming** [comment]
I don't really like linking to a specific point release either but I don't think there is a better way and it should be fine for the lifetime that frc-char has left which is I am assuming not that long (less than a couple years?).
