### ISSUE TITLE
ScreenSteps Comment: Reading array values published by NetworkTables

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#110]
https://github.com/wpilibsuite/frc-docs/blob/develop/source/docs/software/vision-processing/grip/reading-array-values-published-by-networktables.rst

>NetworkTable.getTable() no longer exists. This method will no longer work. Must use NetworkTableInstance.

**Comment by Kevin-OConnor** [comment]
Closed by #128
