### ISSUE TITLE
m_leftMotor and m_rightMotor used in Drivetrain Sim Tutorial example code, but not referenced anywhere

### ISSUE THREAD

**Issue by tytremblay** [wpilibsuite/frc-docs#1100]
The java example on [this page](https://docs.wpilib.org/en/stable/docs/software/examples-tutorials/drivesim-tutorial/updating-drivetrain-model.html) references `m_leftMotor` and `m_rightMotor` but the reader is never told what these are.

**Comment by jasondaming** [comment]
Would changing them to m_leftDriveMotor and m_rightDriveMotor solve the issue for you?

**Comment by tytremblay** [comment]
I'd be fine with the names as they are, as long as the documentation told the user what the types these variables are.  They're not referenced in the tutorial other than to say "These are the motor voltages from the two sides of the drivetrain."  

I understand that this, in the end, is just a number likely between -13 and 13, but the tutorial would be easier to understand if it explained what m_leftMotor and m_rightMotor are in this example code.

**Comment by jasondaming** [comment]
I don't understand.  `m_leftMotor.get()` gets the PWM signal (% output) from [-1,1] as the comment above it says.  What are you saying about -13 to 13?

**Comment by tytremblay** [comment]
I'm talking about the input to driveSim.setInputs().  The PWN value gets multiplied by the battery voltage

**Comment by jasondaming** [comment]
Do you have a proposed change?  I am not trying to downplay your concern here and I want to help I just don't understand what the best way to do that would be.

**Comment by jasondaming** [comment]
@tytremblay do you have a proposed change for this?
