### ISSUE TITLE
The method getLeftVelocity() is undefined for the type DifferentialDrivetrainSim

### ISSUE THREAD

**Issue by tytremblay** [wpilibsuite/frc-docs#1102]
The `simulationPeriodic()` method in the example code on [this page](https://docs.wpilib.org/en/stable/docs/software/examples-tutorials/drivesim-tutorial/updating-drivetrain-model.html) uses methods that don't exist on the `DifferentialDriveSim` class.

**Comment by jasondaming** [comment]
Looks like we need to update to:
getLeftPositionMeters()
getLeftVelocityMetersPerSecond()
getRightPositionMeters()
getRightVelocityMetersPerSecond()
