### ISSUE TITLE
Conflict in order of NI Tools & WPI Install

### ISSUE THREAD

**Issue by JimHofm52** [wpilibsuite/frc-docs#1111]
Following the software install instructions, the first implied thing is to install is the NI FRC Game Tools.  HOWEVER, when you go to the NI Download page there is a NOTE:

! Note: Install programming environments such as NI LabVIEW or Microsoft Visual Studio® before installing this product.

This implies WPI (and VSCode) should be loaded first.  In the past, I've installed WPI/VSC first.  Really don't think it makes a difference.  BUT, I'd have NI drop the note or add a note in the Installation Guide to ignore the note.

**Comment by Kevin-OConnor** [comment]
Order doesn't make a difference, there are no dependencies either way between those two. It does make sense that the current combination of things is confusing and we need to either zig or zag.

**Comment by ThadHouse** [comment]
That message on NI's site is actually just a generic message on all of their download pages. We can likely put a note on our end explaining that message doesn't matter.

**Comment by jasondaming** [comment]
I think the only order that matters is that 3rd party libs should be installed after programming environments right?

**Comment by sciencewhiz** [comment]
LabVIEW teams need to install LabVIEW before Game Tools. But Java/C++ teams don't care about installation order.

**Comment by jasondaming** [comment]
So is there any reason we don't just swap the order of "Installing the FRC Game Tools" and "WPILib Installation Guide" then everything is fine even with the note?

**Comment by Daltz333** [comment]
I'm not sure this is an actual issue, since the order has been like this always, and that notice has been around for a bit.

**Comment by jasondaming** [comment]
I did wonder about the order when first installing things this year.  I would propose to either swap the order like I mentioned above or place a note in Offline Installation.

**Comment by Daltz333** [comment]
A note is more accurate since there is no actual issue in the order of things installed.
