### ISSUE TITLE
Broken Link on driver-station

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#112]
https://github.com/wpilibsuite/frc-docs/blob/develop/source/docs/software/getting-started/driver-station.rst

Has a broken link to `installing_FRC_update_suite`

**Comment by Daltz333** [comment]
Where is this link? The compiled version at https://frc-docs.readthedocs.io/en/develop/docs/software/getting-started/frc-update-suite.html#installing-frc-update-suite looks fine

**Comment by AustinShalit** [comment]
Oh wow.  I forgot that I was looking at the GitHub version.
