### ISSUE TITLE
Add Note to Windows 10 wpilib installation setup (when mounting .iso option does not appear)

### ISSUE THREAD

**Issue by TrevCan** [wpilibsuite/frc-docs#1120]
**Just like it was done in [the FRC Game Tools installation,](https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/zero-to-robot/step-2/frc-game-tools.rst#extraction)** the same can happen when installing .isos on Windows 10 Systems for the WPILIB installation, so I suggest this note to be also added, saying to extract the iso and then run the installer."

**Comment by Daltz333** [comment]
This is already noted in the Windows 7 prereq step

**Comment by TrevCan** [comment]
Yes, I understsand that. But I suggest the Windows 10 setup in the **WPILIB installation** should look as the Windows 10 setup in the **FRC Game Tools Installation**. The FRC Game Tools Installation has a note that says (if the _Mount_ option does not appear) to go to the windows 7 installation. I just recommend this for clarification.

**Comment by Daltz333** [comment]
![Screenshot_20210119-184041_Firefox Focus.jpg](https://user-images.githubusercontent.com/10674555/105107297-da076500-5a85-11eb-95d1-81ac2b3dda14.jpg)

**Comment by Daltz333** [comment]
Ah. I see what you mean.

**Comment by TrevCan** [comment]
I don't think you're understanding me. I am suggesting **adding a note** to the **Windows 10 installation**, not the Windows 7. I will attach an image of the **FRC Game Tools setup and the WPILIB installation side by side **
![image](https://user-images.githubusercontent.com/44383325/105107567-09b26f00-5a7e-11eb-88bc-7e0ab012abce.png)

**Comment by Daltz333** [comment]
Yes, that's what I said?

**Comment by TrevCan** [comment]
Yeah man, I didn't see your comment until after I replied and refreshed the page.
