### ISSUE TITLE
Photo not found when clicked on

### ISSUE THREAD

**Issue by Sargeanthost** [wpilibsuite/frc-docs#1125]
The overview picture (first one [here](https://docs.wpilib.org/en/stable/docs/controls-overviews/control-system-hardware.html)) shows up when scrolling, yet gives a page not found when clicked on.

**Comment by Daltz333** [comment]
What browser are you using? The pictures on that page arein SVG format.

**Comment by prateekma** [comment]
It is broken on Chrome (Android), Safari (macOS), and Firefox (macOS) for me.

**Comment by Sargeanthost** [comment]
Broken on Brave which is chromium based.

**Comment by Daltz333** [comment]
It does 404 for me when clicked on, but the images load for me. Maybe the cache is borked. I'll investigate

**Comment by prateekma** [comment]
> It does 404 for me when clicked on, but the images load for me.

I belive that's what the OP meant by "shows up when scrolling, yet gives a page not found when clicked on."

**Comment by jasondaming** [comment]
I think I have a fix here.
