### ISSUE TITLE
Update Text/Image for Characterization Tutorial

### ISSUE THREAD

**Issue by FRC5414** [wpilibsuite/frc-docs#1127]
on the page at https://docs.wpilib.org/en/stable/docs/software/examples-tutorials/trajectory-tutorial/characterizing-drive.html 

there's a red box for Kp = 43.6 and kD of 20.2. The text below it indicates that "for each meter per second of velocity error, the controller will output an additional 8.5 volts". Either some additional math/explanation is needed to explain how to come up with 8.5, or it'd be nice if the image corresponded with the text.

**Comment by jasondaming** [comment]
This is a duplicate of #1099
