### ISSUE TITLE
Document what each of the different new project templates create

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#1128]
Creating a new project and choosing template there are choices that are completely unexplained:
timed skeleton
robotbase skeleton
etc.

**Comment by Daltz333** [comment]
this is already done https://docs.wpilib.org/en/stable/docs/software/vscode-overview/creating-robot-program.html?highlight=robotbase

**Comment by jasondaming** [comment]
I see nothing in that article that mentions either timed skeleton or robotbase skeleton

**Comment by sciencewhiz** [comment]
That page describes the base classes, not the template themselves. For example the Timed Robot template and the Timed Robot Skeleton both implement the Timed Robot base class, but the Timed Robot Skeleton has all blank methods, while the Timed Robot template has some meat in the methods.
