### ISSUE TITLE
ScreenSteps Comment: Programming your radio

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#113]
https://github.com/wpilibsuite/frc-docs/blob/develop/source/docs/software/getting-started/radio-programming.rst

>In the yellow box describing the update from 19.1.0 to 19.1.1, it says "Teams should install the new version, then re-program their radio (their is no need to re-flash the firmware)". The word "their" should be "there".

**Comment by Kevin-OConnor** [comment]
Closed by #128
