### ISSUE TITLE
Update the turntoangle example to match the gyrodrivecommands

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#1135]
[Here](https://docs.wpilib.org/en/stable/docs/software/commandbased/pid-subsystems-commands.html) is where that example is copied.

It is currently being updated in this [issue](https://github.com/wpilibsuite/allwpilib/issues/3114)

**Comment by Starlight220** [comment]
As the example is RLId, it'll be updated automatically when the example itself is updated.

Therefore, closing this issue
