### ISSUE TITLE
SwerveControllerCommand Inconsistently Scales Waypoints.

### ISSUE THREAD

**Issue by Aidenatgt** [wpilibsuite/frc-docs#1137]
When given a trajectory to follow the SwerveControllerCommand will not accurately follow it; instead it dilates the whole trajectory so that while it can travel 0.25 meters accurately, it will not travel 2.0 meters but rather 4.25. In general the place the robot travels to is about twice what the trajectory set it to. This is not a problem with the robot's odometry because the odometry will reflect that it has gone too far with an accurate measure. It is not a problem with tuning as I wrote a ToPosition command that uses a P loop and the odometry to send the robot to a position. It's not a problem with the way I am creating trajectories because when I generate trajectories the same way with a differential drive robot it follows them fine. It is just when I try to follow trajectories with a SwerveControllerCommand that it does not work. My next step is to try a holonomic controller and hopefully that works better.

**Comment by Daltz333** [comment]
@prateekma could you investigate?

**Comment by prateekma** [comment]
The only thing I can think of is a units issue somewhere; we have [tests](https://github.com/wpilibsuite/allwpilib/blob/master/wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/SwerveControllerCommandTest.java) (and I just verified in simulation) to make sure that the command makes the robot reach the desired goal.

Can you provide a minimal example that reproduces this issue (or your robot code if that's easier for you)? I can try playing around with it in simulation.

**Comment by Aidenatgt** [comment]
@prateekma 

`  /**
   * Creates a new FollowTrajectory.
   */
  public FollowTrajectory(Drivetrain drivetrain, Trajectory trajectory, boolean solus) {
    this.drivetrain = drivetrain;

    thetaController.enableContinuousInput(-Math.PI, Math.PI);
    controller = new SwerveControllerCommand(
      trajectory, drivetrain::getPose, drivetrain.getKinematics(), xController, yController, thetaController, drivetrain::setModuleStates, drivetrain);
    drivetrain.resetOdometry(trajectory.getInitialPose());
  }

  public Command getCommand() {
    return (solus) ? controller.andThen(() -> drivetrain.drive(0,0,0, true)) : controller;
  }`

The solus boolean refers to whether this trajectory runs as a single motion or if it is part of a group of trajectories that run sequentially. As for the trajectory itself as I mentioned we can run trajectories on robots which are generated the same way but they actually work. The setModuleStates() works fine, we go through that method in teleop and it works very well. It is the same for the kinematics.

`  @Override
  public void execute() {
    Pose2d pose = drivetrain.getPose();
    double xVel = xController.calculate(pose.getTranslation().getX()) * Constants.Auto.DRIVE_MAX_VELOCITY;
    double yVel = -yController.calculate(pose.getTranslation().getY()) * Constants.Auto.DRIVE_MAX_VELOCITY;
    double thetaVel = thetaController.calculate(pose.getRotation().getDegrees());

    ChassisSpeeds speeds = ChassisSpeeds.fromFieldRelativeSpeeds(xVel, yVel, thetaVel, pose.getRotation());

    drivetrain.setChassisSpeeds(speeds);
  }`

This code runs successfully using the same PID Controllers to set a single position.

**Comment by prateekma** [comment]
One thing you could try is using the [holonomic drive controller](https://docs.wpilib.org/en/stable/docs/software/advanced-controls/trajectories/holonomic.html) directly. Although the swerve controller command is just a thin wrapper around this, it's a good debugging step that might help narrow down the issue.

Another thing is that from your code above, you're only using the feedback controllers. The holonomic drive controller also uses feedforward so that you'll roughly get good tracking even without substantial PID gains. The code for that is [here](https://github.com/wpilibsuite/allwpilib/blob/master/wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/HolonomicDriveController.java#L84). Can you try incorporating some of this into your manual tests as well?

**Comment by prateekma** [comment]
Another debugging step is to set all the PID gains to zero and see what the robot does; it should roughly still follow the trajectory -- I just verified this functionality.

**Comment by Daltz333** [comment]
@Aidenatgt is there any update, or can I close this issue?

**Comment by Daltz333** [comment]
Closed as stale. Please re-open if you still have issues.
