### ISSUE TITLE
Link to the Glass Page from the Simulation Section.  Field 2D Stuff Especially

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#1138]
https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/glass/field2d-widget.html

**Comment by Daltz333** [comment]
I'm fine with adding a duplicate entry to the TOC for simulation for this.

**Comment by jasondaming** [comment]
I was just planning on adding it to the end of the Simulation GUI page.  And then link there from the Simulation tutorial with a note.
