### ISSUE TITLE
Add warning about AddCommands() footgun

### ISSUE THREAD

**Issue by Modelmat** [wpilibsuite/frc-docs#1147]
See https://github.com/wpilibsuite/allwpilib/issues/3109

**Comment by jasondaming** [comment]
How / where do we want to document this?

**Comment by Daltz333** [comment]
The solution should include a warning with an example of what's bad and how to work around it. Unfortunately, that's outside of my skills, so if anybody familiar with C++ wants to tackle. I am taking the "Good First Issue" tag away due to some required C++ semantics knowledge.
