### ISSUE TITLE
Romi - can't open device "/dev/ttyACM0": No such file or directory

### ISSUE THREAD

**Issue by minglethepringle** [wpilibsuite/frc-docs#1155]
I'm following this guide: https://docs.wpilib.org/en/latest/docs/romi-robot/imaging-romi.html
and I'm on the 32U4 Control Board step. I click update firmware and this is the output:

        Beginning binary upload to Romi ...
        Resetting Romi to boot mode (should see quickly flashing yellow LED

        Running imaging tool

        avrdude: Version 6.3-20171130

         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/

         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "/etc/avrdude.conf"

         Using Port                    : /dev/ttyACM0

         Using Programmer              : avr109

         Overriding Baud Rate          : 57600

        avrdude: ser_open(): can't open device "/dev/ttyACM0": No such file or directory

        avrdude done.  Thank you.

I have the USB A-micro B cable plugged in, A side on the RPi and B side on the Romi board. I'm not sure what to do.

**Comment by Daltz333** [comment]
@zhiquanyeo

**Comment by minglethepringle** [comment]
Restarting the Romi and making sure **Writable** is toggled on the dashboard did the trick. Closing.
