### ISSUE TITLE
Romi – dyld: Symbol not found: _objc_opt_respondsToSelector

### ISSUE THREAD

**Issue by minglethepringle** [wpilibsuite/frc-docs#1156]
Got past the imaging issue and now stuck on starting up the simulator.
(BTW – one important thing that the guide doesn't say is that you need to create the VSCode project while on regular wifi because Gradle tries to resolve the dependencies and it says it "succeeds" on Romi wifi but then when the simulator tries to run, the build fails and says some dependency doesn't exist).

This is the command running:

> /usr/bin/env HALSIM_EXTENSIONS=/Users/mingle_li/Documents/frc5735/RomiTest/build/tmp/expandedArchives/halsim_gui-2021.2.1-osxx86-64.zip_d486575893732cad45e9b59326bc8aaa/osx/x86-64/shared/libhalsim_gui.dylib:/Users/mingle_li/Documents/frc5735/RomiTest/build/tmp/expandedArchives/halsim_ds_socket-2021.2.1-osxx86-64.zip_93f3f7d0cd7149c33a4ab2f56c0bd5f6/osx/x86-64/shared/libhalsim_ds_socket.dylib:/Users/mingle_li/Documents/frc5735/RomiTest/build/tmp/expandedArchives/halsim_ws_client-2021.2.1-osxx86-64.zip_a1b23fe09fc1d4d735ea01797028a351/osx/x86-64/shared/libhalsim_ws_client.dylib: DYLD_LIBRARY_PATH=/Users/mingle_li/Documents/frc5735/RomiTest/build/tmp/jniExtractDir LD_LIBRARY_PATH=/Users/mingle_li/Documents/frc5735/RomiTest/build/tmp/jniExtractDir HALSIMWS_HOST=10.0.0.2 /Library/Java/JavaVirtualMachines/jdk-11.0.6.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:57243 -Djava.library.path=/Users/mingle_li/Documents/frc5735/RomiTest/build/tmp/jniExtractDir -XstartOnFirstThread -Dfile.encoding=UTF-8 @/var/folders/dz/hzqgqyq11kz_rryf5j8_6_gh0000gp/T/cp_8a2n5tmuvf3j6iqyprc9em6nr.argfile frc.robot.Main

This is the output:

    HAL Extensions: Attempting to load: libhalsim_gui
    Simulator GUI Initializing.
    dyld: lazy symbol binding failed: Symbol not found: _objc_opt_respondsToSelector
      Referenced from: /Users/mingle_li/Documents/frc5735/RomiTest/build/tmp/expandedArchives/halsim_gui-2021.2.1-osxx86-64.zip_d486575893732cad45e9b59326bc8aaa/osx/x86-64/shared/libhalsim_gui.dylib
      Expected in: /usr/lib/libobjc.A.dylib

    dyld: Symbol not found: _objc_opt_respondsToSelector
      Referenced from: /Users/mingle_li/Documents/frc5735/RomiTest/build/tmp/expandedArchives/halsim_gui-2021.2.1-osxx86-64.zip_d486575893732cad45e9b59326bc8aaa/osx/x86-64/shared/libhalsim_gui.dylib
      Expected in: /usr/lib/libobjc.A.dylib

    Abort trap: 6

I'm on Mac OS Mojave v10.14.6 .

Please help!

**Comment by minglethepringle** [comment]
Some Googling says there's some sort of version mismatch of Mac OS; maybe the minimum version specified somewhere is too high?

**Comment by Daltz333** [comment]
Majove will be supported in the next release.

**Comment by prateekma** [comment]
You are correct. We fixed this recently to make sure our binaries are built with Mojave support (currently it's only Catalina and above), so it should be in the next release

**Comment by minglethepringle** [comment]
Perfect, thank you! Closing.

**Comment by prateekma** [comment]
@minglethepringle We just released [v2021.2.2](https://github.com/wpilibsuite/allwpilib/releases/tag/v2021.2.2) so you don't need to use dev builds anymore.
