### ISSUE TITLE
Trajectory tutorial frc-char feedback gains example doesn't match the figure

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/frc-docs#1165]
From https://docs.wpilib.org/en/stable/docs/software/examples-tutorials/trajectory-tutorial/characterizing-drive.html:
![Screenshot_2021-01-29_12-15-38](https://user-images.githubusercontent.com/2748555/106323127-c1d4da00-622b-11eb-9c36-b292212c8932.png)

The entire tutorial uses velocity-only, but the last figure uses position and velocity, so the gains don't match what is described. Furthermore, the feedback gains in the previous figures don't match the ending paragraph. Replacing the 8.5 with 43.6 or 20.2 would be invalid as well due to the wrong type of controller being selected.

The figure should be updated to use velocity only with the red box moved to highlight the feedback gains, and the paragraph should be updated to use the velocity gain from the new figure.

**Comment by jasondaming** [comment]
I think you opened the same issue as #1099.  We should probably consolidate this and also #953 into one rewrite/update of the frc-char part of the trajectory tutorial.

**Comment by Daltz333** [comment]
I think #957 can stay separate
