### ISSUE TITLE
Trajectory troubleshooting showcases passing 0 into RamseteCommand

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#1177]
How would non-commandbased teams handle this?

https://docs.wpilib.org/en/stable/docs/software/advanced-controls/trajectories/troubleshooting.html#verify-feedforward

**Comment by prateekma** [comment]
In the same way? You'd still use 2 PID Controllers in your drivetrain when not using command-based. Just set those feedback gains to zero.

**Comment by Daltz333** [comment]
I think a note or something should still be applied to step 2, as it was confusing for me following that step.
