### ISSUE TITLE
How can I display data using XY Graph on Shuffleboard

### ISSUE THREAD

**Issue by Cabbage27** [wpilibsuite/frc-docs#1183]
I want to display data using XY Graph on Shuffleboard, but it seems that only Graph which is similar to Waveform Chart in LabVIEW can show the waveform there.

**Comment by Daltz333** [comment]
I believe shuffleboard only supports single Axis data points.

**Comment by Cabbage27** [comment]
> I believe shuffleboard only supports single Axis data points. Take a look at [Glass](https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/glass/index.html)

Thank you for your reply. But I want to display the data measured by 2-Dimensional LIDAR on a graph. Would you give me some advice?

**Comment by Cabbage27** [comment]
Btw, how could I display the picture files like .png on raspberry pi to the shuffleboard. If someone could answer me, it will help me a lot, thank you!

**Comment by AustinShalit** [comment]
> Thank you for your reply. But I want to display the data measured by 2-Dimensional LIDAR on a graph. Would you give me some advice?

Shuffleboard does not have support for this out of the box. You might want to create your own Shuffleboard plugin to create a widget to do this. https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/shuffleboard/custom-widgets/index.html

> Btw, how could I display the picture files like .png on raspberry pi to the shuffleboard. If someone could answer me, it will help me a lot, thank you!

Just a static picture or are you connected to a camera?

**Comment by Cabbage27** [comment]
> > Thank you for your reply. But I want to display the data measured by 2-Dimensional LIDAR on a graph. Would you give me some advice?
> 
> Shuffleboard does not have support for this out of the box. You might want to create your own Shuffleboard plugin to create a widget to do this. https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/shuffleboard/custom-widgets/index.html

Thank you, I'll take a look.

> 
> > Btw, how could I display the picture files like .png on raspberry pi to the shuffleboard. If someone could answer me, it will help me a lot, thank you!
> 
> Just a static picture or are you connected to a camera?

just a picture, I want to operate the picture using the functions of openCV and show it on the shuffleboard.

**Comment by Cabbage27** [comment]
I forget to say that I am using c++ to program.

**Comment by Daltz333** [comment]
I'm not sure on C++. You might get some better look asking on Chief Delphi.

**Comment by Cabbage27** [comment]
> I'm not sure on C++. You might get some better look asking on Chief Delphi.

Thank you very much, I'll take a look.
