### ISSUE TITLE
Mention SPARKMAX in Zero to Robot as that is in the Rookie KOP

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#1184]
https://www.chiefdelphi.com/t/command-style-programming-1st-attempt-not-working/391009/11

**Comment by Kevin-OConnor** [comment]
Thanks Jason, looks like we had a lack of communication on the HQ side that this change in KOP controllers was being made. I will be working on updating Zero to Robot ASAP to reflect this change

**Comment by sciencewhiz** [comment]
Are you going to update it to include CAN control of them, or just to make sure that PWM control of them is mentioned?

**Comment by Kevin-OConnor** [comment]
I plan to fully document PWM control of them. I do think we should mention CAN as an option and refer to either Rev's documentation and/or create documentation on wiring CAN motor controllers.

**Comment by jasondaming** [comment]
REV's documentation was good for bring up and such of the SPARKMAX's IMO we shouldn't duplicate any of that but it was lacking it basic CAN wiring fundamentals.  That is something I think we should have and link to in ZTR.  I can work on that.

**Comment by Kevin-OConnor** [comment]
Short term I will likely just link to Revs bring up with references to specific sections. Long term, I don't think REV's documentation is arranged well to accomplish what Zero-To-Robot is trying to do (particularly with regards to making the PWM connection) and I would likely prefer to replicate at least some parts, if not all. My plan would likely be to document the wiring and "mode button" method of configuration on FRC Docs and refer out to REV's documentation for any testing or configuration with the Spark Hardware Client.

**Comment by Kevin-OConnor** [comment]
I think CAN wiring makes sense to document generally in a hardware agnostic way (probably in hardware section?) and then we can link to that and REV's docs for CAN (on the software side) from ZTR as an alternative a team can explore if they want.

**Comment by jasondaming** [comment]
Is the setup in REV's [documentation](https://docs.revrobotics.com/sparkmax/gs-sm/connect-a-spark-max-over-usb) required to make PWM control work?  I thought that would work out of the box and it would only be required for CAN control or troubleshooting?

**Comment by Kevin-OConnor** [comment]
No, much of that "bring up" part is not required for PWM control, but to control a brushed motor the mode has to be changed, and that is buried in that "bring up" which is one of the reasons I lean towards replicating only the needed bits in FRC Docs.

**Comment by jasondaming** [comment]
Both @Bankst and @Starlight220 mentioned in Discord that they thought the motor controller would auto detect the interface.  Do you know for sure or do we need to ask REV on this?

**Comment by Kevin-OConnor** [comment]
It will autodetect the interface (PWM vs CAN). It will not autodetect the type of motor. Out of the box they are configured for brushless (as operating a brushed motor in this mode does not cause damage while the opposite does). The user needs to use either the mode button or the Rev Hardware Client to change the device to brushed mode to operate the CIMs provided for the KOP drivetrain.

**Comment by jasondaming** [comment]
@Kevin-OConnor What do you think about replacing the bottom traditional Spark picture (the top one demonstrates a ring terminal so I think it is fine) with this one of the SPARK MAX that shows where the PWM connector goes?
![image](https://user-images.githubusercontent.com/15695521/106827705-8896d280-664e-11eb-81c6-8b6dc1fdf2c1.png)

**Comment by jasondaming** [comment]
I also think this last sentance: "From here, you should connect to the roboRIO and try uploading your code!" Should be removed.  If users are following the guide they haven't even installed software yet!
