### ISSUE TITLE
Known Issues: Gradle Cache

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#1185]
I've heard a few reports of corrupt Gradle caches this year:

https://www.chiefdelphi.com/t/gradle-issue-on-fresh-issue-and-default-template/389519/8
https://www.chiefdelphi.com/t/wpilib-build-error/390971/16

We should add a note to the known issues page about how to solve this.

**Comment by Daltz333** [comment]
It's usually do to multiple Gradle builds at the same time doing crazy things

**Comment by Daltz333** [comment]
I can work on this.
