### ISSUE TITLE
Add Section Explaining CAN wiring

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#1186]
Not sure if this should go in Zero to Robot or Hardware Basics.  My opinion is to get teams started wiring CAN as soon as possible and at least offer that as an alternative in ZTR.

**Comment by jasondaming** [comment]
What do you think should be the position on talking about other topologies:

1. Don't mention them
2. Mention but strongly advise daisy chained.
3. Present all without recommendation

My understanding is:
Daisy Chain - do this please
Star - Never do this, just don't
Multi drop - Contested, and not recommended by CTRE but has worked for some teams and does have some advantages.

**Comment by sciencewhiz** [comment]
I vote for 1.

**Comment by jasondaming** [comment]
@Kevin-OConnor  do you think I should mention alternate topologies namely the bus or CAN connector types?

**Comment by Kevin-OConnor** [comment]
I would stick with just describing daisy chain I think. I think it would take a lot of space to explain pros/cons of other topologies and I don't think an article on CAN basics is the right place for that.

**Comment by gerth2** [comment]
If you need external references, ISO 11898 is the standard that shows what you should and should not do wiring-wise. [TI's digest of it](https://www.ti.com/lit/an/slla270/slla270.pdf) is pretty good and reasonably approachable.

Copying the opinion from Discord: A full-detail document would eventually have to address the standard, but more likely starts with the prescriptive "do this and you'll be fine" approach.
