### ISSUE TITLE
SmartDashboard - LiveWindow needs a port

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#119]
https://wpilib.screenstepslive.com/s/currentCS/m/smartdashboard/c/92707 needs a port

**Comment by yellowjaguar5** [comment]
I'll try it. (take a look [here](https://github.com/yellowjaguar5/frc-docs/tree/SmartDashboard-LiveWindow/source/docs/software/wpilib-tools/SmartDashboard/test%20mode%20and%20live%20window))
