### ISSUE TITLE
Double Clarify that the Encoder Class is just for Encoders plugged into the RIO

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#1191]
https://docs.wpilib.org/en/latest/docs/software/sensors/encoders-software.html

We say what an encoder is and there are many times of encoders now that don't get plugged into the RIO so many are getting confused using this Encoder class because they have an encoder...just not the right type.  They should realize that when they try to construct and the parameter requires a digital line but lets make it extra super clear.

**Comment by Daltz333** [comment]
I assume you are referring to devices such as CTREs mag encoder. We can mention and provide links to vendors documentation, but we shouldn't provide examples.

**Comment by jasondaming** [comment]
Completely agree.  I wanted to add a note that was essentially "Only use the `Encoder` class when using an encoder that is directly connected to the roboRIO via a digital port." We could link to other common encoders or we could just add something like "If you encoder is connected another way please see the manufacturers documentation on how to use that encoder in software"
