### ISSUE TITLE
Analog Links are broken

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#1192]
https://wiki.analog.com/first/first_robotics_donation_resources#adis16448_imu_board_for_first_robotics

See https://pipelines.actions.githubusercontent.com/A3P5ePvyFrxDa4giKegrMzAQaP3YEJ6sOnVKePIADjvCdCRhS4/_apis/pipelines/1/runs/1537/signedlogcontent/3?urlExpires=2021-02-06T14%3A47%3A26.2364288Z&urlSigningMethod=HMACV1&urlSignature=V5HK%2FPldfcAYSb2dUx8LR0mW9INXuHl3qjtJrjJ7AU8%3D

**Comment by mukul2310** [comment]
I am new to open source, I want to contribute to your repo can you guide me how to do this? how to set up?

**Comment by Daltz333** [comment]
Hi! Thanks for wanting to contribute! Are you familiar with using Git/Github?

**Comment by mukul2310** [comment]
Yes I am familiar with Git and Github

**Comment by Daltz333** [comment]
The pipeline log is available [here](https://github.com/wpilibsuite/frc-docs/actions/runs/542352449), click on `Link check` then click on the settings bar in the top right, then click `View Raw Log`

If you `Ctrl + F` the log for `Error` you will find broken links.

https://store.digilentinc.com/dmc60c-digital-motor-controller-approved-for-first-robotics/

which is in file ``docs/controls-overviews/control-system-hardware``.

The link can be replaced with `https://www.digikey.com/en/product-highlight/d/digilent/dmc60c-digital-motor-controller`

Now a couple of analog links are broken, we have
`https://wiki.analog.com/first/first_robotics_donation_resources` on `docs/hardware/sensors/gyros-hardware`

`https://wiki.analog.com/first/first_robotics_donation_resources#adis16448_imu_board_for_first_robotics` and `https://wiki.analog.com/first/first_robotics_donation_resources#adis16470_imu_board_for_first_robotics` on `docs/software/vscode-overview/3rd-party-libraries`

These three analog links should get replaced with a reputable source or alternative link. In this case, it should be  (in order of what should be replaced from above).

`https://www.analog.com/en/landing-pages/001/first.html`

**Comment by mukul2310** [comment]
Thank you! I did it with your help!

**Comment by mukul2310** [comment]
Please review the PR it is showing something wrong

**Comment by AustinShalit** [comment]
@mukul2310 Congrats on your first contribution

**Comment by mukul2310** [comment]
Thank you sir
