### ISSUE TITLE
Add warning admonition to discontinued motor controllers

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#1195]
The Hardware Overview page should state under each discontinued motor controller

"While this motor controller is still legal for FRC use, the manufacturer has discontinued this product".

**Comment by sciencewhiz** [comment]
Danger seems too strong. Note would be better.

**Comment by Daltz333** [comment]
I think a warning would be better. Lack of manufacturer support means there is virtually no support except from a niche group.
