### ISSUE TITLE
Merge Glass and Simulation TOCs

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#1200]
Duplicate TOC entries of Glass into Simulation where applicable. Make adjustments were applicable.

- Glass will get widgets that are not available in simulation (camera server).

**Comment by jasondaming** [comment]
I would propose to keep the Glass section and rename it "Glass / Simulation GUI".  Then move the Simulation GUI specific pieces into this section.

Then "Robot Simulation" can be moved from tools to Advanced Programming.

**Comment by Daltz333** [comment]
I'm not sure I agree. If we want to keep all the dashboards in one spot, and there are plans in the future to have some major differences. Having the same section isn't scalable and we'll have to split it again in the future.
