### ISSUE TITLE
Drivetrain model gear ratio description inverted?

### ISSUE THREAD

**Issue by chauser** [wpilibsuite/frc-docs#1206]
The [Drivesim tutorial page on creating a drivetrain mode](https://github.com/wpilibsuite/frc-docs/blob/stable/source/docs/software/examples-tutorials/drivesim-tutorial/drivetrain-model.rst) says in three places that the gear ratio is reckoned as output over input and is typically greater than 1. I'm reasonably sure that this should be input over output (i.e. the motor shaft (input) turns faster than the wheels (output)).

**Comment by prateekma** [comment]
When talking about ratios, we usually mean torques, so output torque over input torque. We can add clarification for this however.

**Comment by chauser** [comment]
I see. I agree a clarification is needed since the only thing that is
really being considered in this document's context is distances; torques
don't show up here.
