### ISSUE TITLE
The driving of the robot has been reversed

### ISSUE THREAD

**Issue by nbhalala27** [wpilibsuite/frc-docs#1211]
When I turn left with the controller, it goes right. Vice-Versa. 
Please help to fix this issue in the code.

**Comment by Daltz333** [comment]
Could you please share your code and your robot motor controller setup?

**Comment by jasondaming** [comment]
I am assuming this is your [code](https://github.com/nbhalala27/Testing/blob/master/src/main/java/frc4388/robot/subsystems/Drive.java)?

Can you tell us what the lights on the motor controllers are doing when you run it forwards, backwards, left and right?

If both your left and right sides were inverted this would make perfect sense.  I notice that you are just pulling the Y axis of the left stick.  An Xbox controller or similar will give a positive value when pressed down.  That means if forwards/back is "working" for you then it is actually backwards in the motor controllers as you have 2 things inverted.  This would also explain turning the wrong direction.

**Comment by Daltz333** [comment]
Closing as stale, please re-open if there is still an issue.
