### ISSUE TITLE
Remove smart quotes

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#1224]
Smart quotes like `“` and `”` can introduce errors when translating. We should remove all of the smart quotes and add a check to make sure they do not get introduced in the future.

**Comment by Daltz333** [comment]
I'm not going to mark this as a good first issue yet, as I think the proper solution is a linter.

**Comment by Daltz333** [comment]
In the meantime, somebody can find/replace currently. I'll leave this issue open.
