### ISSUE TITLE
Kalman Filters article references the orange plot; no such plot exists

### ISSUE THREAD

**Issue by mcm001** [wpilibsuite/frc-docs#1231]
> In the above chart, the orange plot (with a state standard deviation of 3.0 and measurement standard deviation of 0.2) produced a filter that reacted quickly to disturbances while rejecting noise, while the magenta filter was barely affected by the velocity dips.
The color references should be changed to indicate position in the plot array

**Comment by jasondaming** [comment]
I see an orange plot here:
![image](https://user-images.githubusercontent.com/15695521/110060132-096aec00-7d2b-11eb-95ca-59f6f2b0111a.png)

**Comment by jasondaming** [comment]
We spoke and the orange plot is not the issue here.  It is the reference to the "magenta filter" which doesn't exit although it possibly used to.  The intent here is to highlight the filter in the upper right so I will change it to that.
