### ISSUE TITLE
Create Code Formatter Article (Clang + Spotless)

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#1233]
- Put next to CI article for now.
- Probably create a "Best Practices" section that will be the successor of Basic Programming.

**Comment by Starlight220** [comment]
Why next to the unit test one and not next to the CI one? It seems much more relevant. All three should definitely be in a "Best Practices" section though.

**Comment by Daltz333** [comment]
My bad, I meant the CI one. The unit testing article should stay with simulation.

**Comment by Starlight220** [comment]
In Clang for C++, is the intention to Clang-Format or wpiformat?

**Comment by Daltz333** [comment]
Probably wpiformat.

**Comment by AustinShalit** [comment]
Should this get an accompanying PR to update the templates to support the formatters?

**Comment by Daltz333** [comment]
There is a couple of issue with supporting formatters:
- C++ is a no-go besides having the style files sit in their project due to the heavy dependency requirements.
- Java requires spotless, which is an online dependency
  - We'd have to store this ourselves or have the initial plugin apply commented out.
  - This really doesn't lighten up any documentation work, besides the fact that it removes ~8 lines the user has to copy/paste.
  
This is probably fine with just a doc article.
