### ISSUE TITLE
Command Groups - Unclear include requirements

### ISSUE THREAD

**Issue by davidorser** [wpilibsuite/frc-docs#1236]
#include statement requirements should be added to this Article:
https://github.com/wpilibsuite/frc-docs/blob/stable/source/docs/software/commandbased/command-groups.rst

For example (C++):
#include <frc2/command/SequentialCommandGroup.h>
#include <frc2/command/ParallelCommandGroup.h>
#include <frc2/command/ParallelDeadlineGroup.h>
#include <frc2/command/ParallelRaceGroup.h>

SequentialCommandGroup.h is in the example at the top, but the rest are not mentioned at all. Omitting these includes results in a typically unhelpful error message, "incomplete type is not allowedC/C++(70)".

Particularly, this is a stumbling block for people progressing to using more in-line and more complex Command Groups (very likely common this year.)

**Comment by Daltz333** [comment]
I'm actually divided on this. 

We've been moving away from including package imports in the Java documentation, as it gets incredibly verbose with some articles using 60+ includes. Includes and Package imports should be general language knowledge, and we shouldn't really sacrifice valuable article space for them. Especially when have a whole page is covered by includes. This is especially relevant in the drivetrain simulation and ramsete tutorials which import a *lot* of stuff.

The general recommendation is to have the students use VS Code intellisense for handling package imports or includes.

Mind you, I don't use C++ myself. This poses the question:

How good is C++ at detecting the right import in VS Code? If it's unusable, I'd be open to being more clear on necessary includes. Generally, C++ users are more skilled on average than Java (note the API differences in some areas).

I am going to mark this as "Needs Design Decision" as this pends further discussion.

**Comment by calcmogul** [comment]
C++ intellisense in VS Code breaks often for my team.

**Comment by Daltz333** [comment]
That's fair. We can likely just add the includes into the code snippet themselves. Aka:

```cpp
#include <units/voltage.h>
...
my code
```

**Comment by jasondaming** [comment]
I have found the lighbulb in VSCode to be very good at adding imports.  Getting people to actually use it can be a challenge but once they do imports of anything standard like this (at least in Java) are trivial.

**Comment by Daltz333** [comment]
That's what I was talking about earlier. The lightbulb often just doesn't work for C++
