### ISSUE TITLE
createKitbotSim example Incorrect

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#1241]
https://docs.wpilib.org/en/stable/docs/software/examples-tutorials/drivesim-tutorial/drivetrain-model.html

SixInch not kSixInch.  Do we want to stay consistent with this?  Motor and gearing both use the k.

Use 10.71 as that is the default as it is the default and what is shipped with the kitbot.

**Comment by Daltz333** [comment]
Ideally, we should use the WPILib style guide and use kConstant, m_member, etc.

**Comment by jasondaming** [comment]
@prateekma that was fast.  I am made an issue on allwpilib

https://github.com/wpilibsuite/allwpilib/issues/3201
