### ISSUE TITLE
Battery Article

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#1246]
Battery tip, tricks, and best practices.

**Comment by jasondaming** [comment]
Things to include:
DONT CARRY BY THE CABLES
Should I leave batteries on the charger?
How to store batteries when unused?
What is a good battery resistance?
How to identify a bad cell, what does that mean?
Tighten battery terminals
Best hardware for securing the battery terminals
Battery Beak
Battery Discharge Tester
Link roboRIO brownout article
Link battery troubleshooting

Link from hardware overview, brownout, and battery troubleshooting to this article.

Please add them if you have others!

**Comment by Daltz333** [comment]
In terms of linking a battery beak or discharge tester, we have to be careful about providing vendor specific links. IE, not just link to one if multiple vendors offer.

**Comment by jasondaming** [comment]
I wasn't going to link to a specific device, but rather describe the limitations / applications of each type of device.

Is there really a competitor to the beak?  Seems like linking to it wouldn't hurt but also wouldn't be necessary.
