### ISSUE TITLE
Better explanation of AlongWith, RaceWith, and DeadlineWith

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#1247]
https://docs.wpilib.org/en/latest/docs/software/commandbased/convenience-features.html#alongwith-java-only

**Comment by prateekma** [comment]
What do you mean by "better explanation"? Should we link to the command groups page explaining what each command group is?

**Comment by jasondaming** [comment]
Removing the text and linking the command groups is an option but I propose making the text more clear and linking. 

Each one uses its title in the definition which really says nothing:
.alongWith
"The alongWith() decorator returns a parallel command group containing the command, along with all the other commands passed in as arguments."
Could be:
The alongWith() decorator returns a parallel command group.  All commands will execute at the same time and each will end independently of each other.
