### ISSUE TITLE
Make changed pages easier to find in PR builds

### ISSUE THREAD

**Issue by TheTripleV** [wpilibsuite/frc-docs#1275]
For PRs, there should be a `What's New, Scooby Doo` page that contains a list of pages that were changed in the PR.

**Comment by Daltz333** [comment]
Should an action that comments on PRs suffice? What's the use case? Easier reviewing?

**Comment by TheTripleV** [comment]
Yeah, a comment would be enough.
It's for easier reviewing.

**Comment by TheTripleV** [comment]
Though, a comment would get messy for big PRs (homepage redesign for one)

**Comment by Daltz333** [comment]
I think a page on frc-docs is a bit excessive, and I don't want to bloat CI specific stuff to it

**Comment by Daltz333** [comment]
Would this be something you are willing to do?
