### ISSUE TITLE
Update Hall Effect Sensor to Magnetic Limit Switch

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#1279]
https://docs.wpilib.org/en/stable/docs/hardware/sensors/proximity-switches.html

West Coast discontinued the specified product, update to https://www.revrobotics.com/rev-31-1462/?

Need to update diagram and section.

**Comment by AustinShalit** [comment]
This is a mistake due to the new WCP website and will be resolved on their side.
