### ISSUE TITLE
Change instances of NT to use the :term: NetworkTables

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#1282]
I don't think it is as rare as you think, from our docs:
Twice [here](https://docs.wpilib.org/en/latest/docs/software/vision-processing/roborio/using-multiple-cameras.html?highlight=NT#switching-the-driver-views)
Once [here](https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/shuffleboard/custom-widgets/builtin-plugins.html?highlight=NT#networktables-plugin)
The rPi abbreviates is this way in the logs [here](https://docs.wpilib.org/en/latest/docs/software/vision-processing/wpilibpi/the-raspberry-pi-frc-console.html?highlight=NT#vision-status)
[Here](https://docs.wpilib.org/en/latest/docs/software/networktables/multiple-instances.html?highlight=NT#creating-multiple-instances-of-networktables)

There are probably more.

**Comment by Daltz333** [comment]
Blocked until #1276
