### ISSUE TITLE
Merge state space and controls glossary

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#1286]
We should merge the controls and state-space glossary as they're fairly related and in the same section.

controls: https://docs.wpilib.org/en/stable/docs/software/advanced-controls/introduction/controls-glossary.html
state-space: https://docs.wpilib.org/en/stable/docs/software/advanced-controls/state-space/state-space-glossary.html

**Comment by Daltz333** [comment]
- Move controls to root of advanced controls at bottom of TOC
- Merge state-space into controls glossary
