### ISSUE TITLE
Improve PIDController Article

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#1290]
Improve https://docs.wpilib.org/en/stable/docs/software/advanced-controls/introduction/tuning-pid-controller.html to reference a real world example (arm positioning?)

**Comment by gerth2** [comment]
Starting some work on this in my fork.

Key technical thing I'm looking to do is get an interactive PID tuning simulation in place. I am planning this to be custom JavaScript that runs on the client side. 

From a structure standpoint, looking at the existing doc- there is a lot of back and forth with the model-based sysid tuning, and feedback-only control. 

From a pedagogy standpoint, I'm wondering if a bit of scope creep might help doc flow.

What I have in mind now: for advanced controls,

1) introduce the "burning platform" of why a team would need to start looking into feedback or feed forward controls at all
2) describe feed forward and feed back controls concepts at a high level.
3) indicate that there's lots of possible paths which will be sufficient for most FRC applications, and teams should advance along to more complex solutions as they feel comfortable.
4) let the PID explanation and manual tuning focus solely on feedback control (as they do today)
5) insert one "bridge" document showing how to do trivial, non-linrar-algebra feed forward designs, with tuning exercises to show how it's easier to achieve the control goals
6) dive into the model-based controls for the general case, introducing sysid and how it can cover both feedback and feed forward tuning

The overall goal is to provide a "path" which moves from simple ideas to complex ideas, but maximizes the chance that for the a verage FRC mechanism, students can stop wherever they feel comfortable, and still get something to the field which scores points. Furthermore, at each level, the "next step" would be available, along with some guidance of what the team's gain would be, and a rough sense of the difficulty involved.

In all cases, we should see if we can get some shiny gifs to motivate the examples for the visual learners, and try to coax students along that learning path described above.

**Comment by Daltz333** [comment]
I definitely like your suggestions. Animated gifs (MP4 instead of gif however) would speak a thousand words.

**Comment by gerth2** [comment]
Can the mp4's be pulled from robot footage with team permission? Or do we need to stay team agnostic?

**Comment by Daltz333** [comment]
They can be pulled from team footage with permission for them to be licensed as CC (free to use by anyone).

**Comment by Starlight220** [comment]
Is this resolved by #1821?
