### ISSUE TITLE
Add "Knowledge Recommendations" to the trajectory tutorial

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#1303]
https://docs.wpilib.org/en/stable/docs/software/examples-tutorials/trajectory-tutorial/trajectory-tutorial-overview.html

This will hopefully prevent teams from diving into this without some of the other controls experience needed to be successful.

**Comment by Daltz333** [comment]
We have to be careful with the language here, and it should be a recommendation, not a hard requirement.

**Comment by jasondaming** [comment]
The note is already there: "Before following this tutorial, it is helpful (but not strictly necessary) to have a baseline familiarity with WPILib’s PID control, feedforward, and trajectory features."
