### ISSUE TITLE
Add section for Feedback on WPILib, docs, DS, and other common control system software.

### ISSUE THREAD

**Issue by marshallmassengill** [wpilibsuite/frc-docs#1304]
I could be wrong and have completely missed it but a section detailing how teams can provide feedback to HQ/WPILib Devs/NI/Etc would be useful.  I did not find one doing a few searches and looking at the docs outside of opening an issue here.

**Comment by Daltz333** [comment]
Many forms of feedback can be contributed to various organizations linked on this page https://docs.wpilib.org/en/stable/docs/software/support/support-resources.html. 

Unfortunately, WPILib is the only real one out of the examples you've linked with a dedicated route for contributing and feedback. The rest ties into emails and support forums for feedback. I am sorry.

WPILib feedback can be added via the "Report an Issue" page or "Contributing to WPILib" in the bottom left".

**Comment by marshallmassengill** [comment]
Is there a reason other emails can't be linked on that same page as well?  Should I open a merge to add them?  I notice that CTRE support is listed but REV (support@revrobotics.com) is not and neither is the team support email (firstroboticscompetition@firstinspires.org) for FIRST?  Wasn't looking for the docs to outline the "How to" of the support process but more of the "where to direct feedback and get support" for teams.  It would be nice to have some of that in one spot so teams don't have to hunt it down.  For instance, where should a team direct feedback for the Driver Station if they have that feedback to provide?  I think it might be unclear for many teams on where they should direct their feedback.  Would love to see it documented and happy to help if I can.

**Comment by Daltz333** [comment]
REV Robotics and the support email would be welcomed to be added to the support page.

...

In regards to the "Where to direct", this just doesn't exist. You have to contact NI via the forum and work up from there. As far as I am aware, there is no alternative. The difficulty that exists in an external one, the fact that external vendors just don't have a dedicated platform for feedback. It is all focused on support. Unfortunately, I just don't see any content to add to a hypothetical article?

If you would like to put the effort to getting dedicated hotlines or locations for feedback that are non-support focused, I am open to reopening this issue.
