### ISSUE TITLE
Remove MikTex/PDF support for Windows

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#1323]
Needs updates, and tools does not exist

**Comment by Daltz333** [comment]
A bit more complicated actually. Something somewhere with SVG builds broke again

**Comment by Daltz333** [comment]
Re-investigating CairoSVG, since rsvg-converter for windows just completely broke :(

**Comment by Daltz333** [comment]
Update, it's time to drop windows PDF support. Cairo does not provide binaries for Windows at this time.

**Comment by TheTripleV** [comment]
I switched from miktex to texlive and it the pdf built fine.
