### ISSUE TITLE
Shuffleboard plugin sample build code uses gradle kts

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/frc-docs#1325]
https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/shuffleboard/custom-widgets/creating-plugins.html

Nothing uses gradle kts, we don't recommend it, so we should not have our examples use gradle kts.

**Comment by calcmogul** [comment]
On the FRC Discord, @ThadHouse suggested replacing
```groovy
dependencies {
   compileOnly("edu.wpi.first.shuffleboard", "api", "2020.+")
   compileOnly("edu.wpi.first.shuffleboard.plugin", "networktables", "2020.+")
}
```
with
```groovy
dependencies {
   compileOnly 'edu.wpi.first.shuffleboard:api:2021.+'
   compileOnly 'edu.wpi.first.shuffleboard.plugin.networktables.2021.+'
}
```

**Comment by ttchalakov** [comment]
> On the FRC Discord, @ThadHouse suggested replacing
> 
> ```groovy
> dependencies {
>    compileOnly("edu.wpi.first.shuffleboard", "api", "2020.+")
>    compileOnly("edu.wpi.first.shuffleboard.plugin", "networktables", "2020.+")
> }
> ```
> 
> with
> 
> ```groovy
> dependencies {
>    compileOnly 'edu.wpi.first.shuffleboard:api:2021.+'
>    compileOnly 'edu.wpi.first.shuffleboard.plugin:networktables:2021.+'
> }
> ```

You would need to change:
compileOnly 'edu.wpi.first.shuffleboard.plugin:networktables:2021.+'
to 
compileOnly 'edu.wpi.first.shuffleboard.plugin:networktables:2020.+'
because there is no 2021 version
https://frcmaven.wpi.edu/artifactory/release/edu/wpi/first/shuffleboard/plugin/networktables/
