### ISSUE TITLE
Sensors Image Refactor

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#1332]
# Analog Inputs

1st image - great

2nd image (of the Ultrasonic) - doesn’t seem very helpful to me with no labels on the pins of the sensor. If we want an already in-use image to go here, I think the ASXL193 image from the accelerometers article with the labeled pins is better than this one.

Totally fine to use this sensor as an example if we prefer that, but I think we should try to label the pins (hopefully labels in the sensor docs make sense, otherwise I think we should change the example to one that is somewhat obvious). I think as an image associated with an overview of analog sensors we want to try to bang over the head with what connects where, even though it should be fairly obvious from most sensor pin labels.

3rd image - seems great at conveying what it’s supposed to (though an error in the text describing it where describes being connected to 3 “digital input ports”)

# Potentiometers

1st image - great. Most pots will be like this and the text describes things well enough without pin labels for someone to hopefully understand if they have a real weird one that doesn’t somehow.

2nd image - Fine. I think this picture is trying to convey that an absolute encoder connects in a similar way to a pot and not the details of this specific sensor or what to wire where, so I think the sensor pins being unlabeled is fine and I think it would look awkward to try to label them in that graphic.

# DIO

1st image - great.
2nd image - great. I am probably going to propose some text here to go into just a touch more depth on NO vs NC. I typically recommend switches be wired NC because it’s easier to failure detect them in Test Mode or robot startup code but it definitely depends on application and there is no right or wrong answer (unplugged NC looks triggered, can be pretty bad in some applications)
3rd image - great. Sensor is labeled making things obvious
4th image - good. To me, purpose is to show multiple signal connections with a single Pwr/Gnd as described by the text and I think the image does that without sensor labels.

# Proximity Switches

All good

# Encoders

1st image (quadrature signals) - great
2nd image (greyhill) - One of the ones that sparked the conversation, I think based on the text (and my thoughts on philosophy) that the purpose of this image (and section of text) is to provide an example of a type of encoder, not provide wiring instruction for a Greyhill 63R when we don’t provide similar instruction for all types of encoders. I think reducing the image to the encoder itself and removing the wiring would be better.
3rd image (AMTs) - same as Greyhill, I think we’re trying to highlight mechanical differences and image focuses more on wiring
4th image (mag encoder) - Fine. I do think it’s a little tough to grasp exactly how this works from that image, but I think coming up with a better one could be tricky.
5th image (encoder wiring) - Ok, but I think one with the encoder  labeled with common terminology (A/B) like the AMT one we already have above may be better for this. And if that means we want to switch the multi DIO image (4th image in DIO article) to a labeled image too that seems fine.

# Gyros

all good

# Ultasonics

all good

# Accelerometers

all good

# Serial Buses

all good

**Comment by sciencewhiz** [comment]
There should probably also be wiring for a DutyCycleEncoder.
