### ISSUE TITLE
The headline: "Adding and deleting tabs" in the Shuffleboard section does not document how to delete a tab

### ISSUE THREAD

**Issue by Sargeanthost** [wpilibsuite/frc-docs#1344]
[This section](https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/shuffleboard/getting-started/shuffleboard-tabs.html#adding-tabs-and-deleting-tabs) has no mention of deleting tabs manually or programmatically.

**Comment by Daltz333** [comment]
There actually isn't a programmatic way to delete tabs, at least not easily. We can probably just document the little "x" button in shuffleboard.

**Comment by Sargeanthost** [comment]
I think you should also say that you cant do it programmatically, as I would assume people want to know that.
