### ISSUE TITLE
Document which network ports are available on the RIO

### ISSUE THREAD

**Issue by TheTripleV** [wpilibsuite/frc-docs#1364]

**Comment by ThadHouse** [comment]
This is something we need to be careful about, as these are explicitly listed in the game manual. Assuming you mean ports that are accessible from the DS. If you mean between coprocessors, best options are pick a port thats not listed as a legal port in the game manual, as over the wired connection on the robot nothing is blocked.

**Comment by Daltz333** [comment]
I think a note in the networking section referring to the game manual might be the safest bet here.

**Comment by Daltz333** [comment]
The decision here is just to have a note referencing the game manual.

**Comment by Daltz333** [comment]
Link to relevant sections in game Q&A
