### ISSUE TITLE
Update trajectory tracking tutorial for deprecated RamseteCommand functionality

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/frc-docs#1367]
Depends on wpilibsuite/allwpilib#3366.

Relevant RLIs should also be updated, I don't see any point in updating them until then.

**Comment by Daltz333** [comment]
Should update this tutorial to be non-commandbased focused? Then it'll be useful for both sides?

**Comment by Starlight220** [comment]
Perhaps split it with tabs?

**Comment by Daltz333** [comment]
I agree with that.

**Comment by Starlight220** [comment]
The allwpilib PR (wpilibsuite/allwpilib#3366) this depends on is stalled and possibly a wontfix, so no point in keeping this open in the meantime. If that PR gets revived and merged, we can reopen this.
