### ISSUE TITLE
Language Menu does not open on iOS

### ISSUE THREAD

**Issue by TheTripleV** [wpilibsuite/frc-docs#1394]
Clicking on `v: stable` or `v: latest` doesn't do anything.

Tested on:
Model - iPhone 12 Pro
Version - iOS 14.6
Browsers - Safari & Chrome
frc-docs Versions - stable & latest

**Comment by Daltz333** [comment]
Possible bug in dependency

**Comment by Daltz333** [comment]
Issue https://github.com/readthedocs/readthedocs.org/issues/8341
