### ISSUE TITLE
Videos not showing

### ISSUE THREAD

**Issue by PaulKeenan** [wpilibsuite/frc-docs#1418]
Maybe this is a just in Canada thing since I am in Canada but on the How to Wire a Robot page in the WPI FRC section the videos for Wago Connectors and Weidmuller Connectors don't play. The message is " This video is unavailable".

I hope this is able to be fixec.
Thanks.

**Comment by Daltz333** [comment]
This is a known issue due to YouTube making old unlisted videos private. Pinging relevant parties @bradamiller

**Comment by Daltz333** [comment]
Blocked until FIRST fixes, or we decide on a new alternative from REV or CTRE. Will revisit this issue :soon:
