### ISSUE TITLE
Add CAN Coder Status Lights To Quick Reference Page

### ISSUE THREAD

**Issue by mdurrani808** [wpilibsuite/frc-docs#1426]
http://www.ctr-electronics.com/cancoder.html

https://docs.wpilib.org/en/latest/docs/hardware/hardware-basics/status-lights-ref.html

Given the amount of teams that will be using CAN Coders for their swerve robots next year, these should be added to the quick reference.

**Comment by Daltz333** [comment]
It was decided internally against adding CANCoder. There are too many FIRST legal sensors that adding this opens an entire can of worms.

Additionally, all the other hardware on the status lights page is explicitly legal on the FIRST parts page.
