### ISSUE TITLE
Update roboRIO brownout page for roboRIO 2 behavior

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#1452]
https://docs.wpilib.org/en/latest/docs/software/roborio-info/roborio-brownouts.html 
New behavior described here: https://www.firstinspires.org/robotics/frc/blog/2021-ni-guest-blog-roborio2-0

**Comment by Daltz333** [comment]
Not 100% sure but some assumed information (may be incorrect)

Default: 6.75 volts, 0.25v increments
