### ISSUE TITLE
Add Interrupt Change to New for 2022 doc

### ISSUE THREAD

**Issue by Kevin-OConnor** [wpilibsuite/frc-docs#1480]
Interrupts were totally changed, need to document porting for teams.
Change is here:
https://github.com/wpilibsuite/allwpilib/commit/5c817082a0dbc032a3dab4a8b6b6fbfb8b451f75

**Comment by sciencewhiz** [comment]
It says that there was a change, but doesn't give any tips on porting. Rather then a class, like DigitalInput extending InterruptableSendableBase and all methods being accessed through the DigitalInput, you instead construct AsynchronousInterrupt or SynchronousInterrupt, and pass it the DigitalInput.
