### ISSUE TITLE
Enable Linkcheck

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#150]
I think it'll be beneficial in the long run to enable this check. It'll require some amount of configuration and tweaking to the docs to getting it run reliably (ignore anchor points in URLs, and ignore localhost URLs). Fortunately, Sphinx actually has linkcheck pretty well documented.

Pros: We know when a link will break.
Cons: All PRs will fail when a link breaks.

**Comment by yellowjaguar5** [comment]
I have verified that linkcheck runs without errors in #153, so do you think we should enable it as part of #153 or after that PR is merged?

**Comment by Daltz333** [comment]
It can enabled separately, that way we can revert if need be.
