### ISSUE TITLE
FMS Networking Ports Documentation

### ISSUE THREAD

**Issue by jonathandao0** [wpilibsuite/frc-docs#1510]
At the 2021 Beach Blitz off-season event, I discovered that I was unable to send data over port 4201 (My team number) when connected to the field. When trying to resolve this, I tried looking for in frc-docs, but couldn't find it so I matched the limelight/photonvision port of 5801 to solve my issue. Afterwards, I found this information on the FMS whitepaper, but this info should be included in the networking documentation so that it can be more easily referenced.

**Comment by ThadHouse** [comment]
This is actually something where the game manual is the source of truth. Its been in there for a long time. This year it's R60, and its often around there, in the Control, Command and Signals System section.

**Comment by Daltz333** [comment]
Please see https://docs.wpilib.org/en/latest/docs/networking/networking-introduction/networking-basics.html#available-network-ports for a list of available ports
