### ISSUE TITLE
Romi- can't open device "/dev/ttyACM0": No such file or directory

### ISSUE THREAD

**Issue by bakerworks** [wpilibsuite/frc-docs#1511]
Following steps from here: https://docs.wpilib.org/en/stable/docs/romi-robot/imaging-romi.html
to write the firmware image to the 32U4 Control Board. and get this message:
"avrdude: ser_open(): can't open device "/dev/ttyACM0": No such file or directory"

Tried two different USB cables from Pi to 32U4. Verified mode is Writeable.

**Comment by zhiquanyeo** [comment]
Are those USB cables known to be data cables? Can you try connecting the Romi32U4 board to a computer using one of those cables and see if a serial port shows up?
