### ISSUE TITLE
Add page for Vendor Example Projects

### ISSUE THREAD

**Issue by mdurrani808** [wpilibsuite/frc-docs#1515]
Suggestion: Adding a page under Examples / Tutorials that links to example projects for all vendors that have a vendor dependency and have examples easily accessible.

REV: https://docs.revrobotics.com/sparkmax/software-resources/spark-max-code-examples

CTRE: https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages

PhotonVision: https://docs.photonvision.org/en/latest/docs/examples/index.html

Kauai Labs: https://pdocs.kauailabs.com/navx-mxp/examples/

Don't know if this is allowed or if this preferences certain vendors over others, but if vendors are free to PR their own links onto this page, it should be fair in my eyes.

**Comment by jasondaming** [comment]
I think this article makes sense and will be useful.
