### ISSUE TITLE
Explain where WPILib is at Concerning Swerve Support

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#1517]
- Swerve simulation is hard but [this](https://github.com/wpilibsuite/allwpilib/pull/3374) is promising
- SysID doesn't currently support the 2 step nature needed to tune swerve PID
- Pathweaver would need to adopt waypoint headings and have the traj libs significantly changed to additionally take a heading.

**Comment by calcmogul** [comment]
To elaborate on SysID swerve support:

You can use simple motor project to tune the swerve module heading. However, you need all the modules to line up using feedback to be able to collect module velocity data. To support that, we'd either need to generate a swerve implementation in the various combinations, or have the user log SysID data using their own swerve project and SysID's logging classes.

If teams used their own swerve project, it would most likely be Java, which will have poor sampling determinism (data won't get sampled consistently at 5 ms or whatever).

Here's some more comments on this: https://github.com/wpilibsuite/sysid/issues/198#issuecomment-959836337

**Comment by shueja-personal** [comment]
> Pathweaver would need to adopt waypoint headings and have the traj libs significantly changed to additionally take a heading

This is my plan for a PathWeaver replacement I’m working on but I have no idea when that project will be ready.

**Comment by jasondaming** [comment]
You should probably talk to us more in depth about your plans on a different thread or PM.  There have been a lot of different people proposing different ways or replacing PathWeaver and we want to promote something that fits the overall vision and has the support to be a well maintained piece of software.

**Comment by shueja-personal** [comment]
I rephrased, to avoid proposing that WPILIB should advertise my project, simply that PathWeaver swerve/ independent heading support could be part of a potential replacement instead.
