### ISSUE TITLE
Show more information on the Checking Diagnostics Plots

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#1518]
The first plots [here](https://docs.wpilib.org/en/latest/docs/software/pathplanning/trajectory-tutorial/characterizing-drive.html) should be from "Combined Diagnostics"

**Comment by sciencewhiz** [comment]
Is this addressed by #1710?

**Comment by jasondaming** [comment]
No but I am talking with Oblarg about adding it now
