### ISSUE TITLE
Random Usages of Spanish While In English Setting of frc-docs

### ISSUE THREAD

**Issue by mdurrani808** [wpilibsuite/frc-docs#1525]
![image](https://user-images.githubusercontent.com/46766905/142297433-0f5783e0-3a70-4057-90d9-ae5d93d328d1.png)

See: Hardware: Basic and Contributing to frc-docs

On latest "branch" of the website
Browser: Microsoft Edge Version 95.0.1020.53

**Comment by jasondaming** [comment]
If I go here I see [this](https://docs.wpilib.org/en/latest/index.html) in Edge:
![image](https://user-images.githubusercontent.com/15695521/142306829-d7bbe00c-2a15-4369-8b3c-b7466697c7c7.png)

Are there any other steps you took to get that?  If you go to my link above do you see the same?  After clearing cache too?

**Comment by Daltz333** [comment]
You are likely on the spanish version of the website. Google sometimes likes to index it. Please try https://docs.wpilib.org/en/

**Comment by sciencewhiz** [comment]
I can't reproduce this either. Does it happen on other web browsers, computers, or networks?

**Comment by mdurrani808** [comment]
I believe the portuguese version was cached/indexed and then I was looking at that (I swear I checked that I was on English but alas), then got confused because only some pages were translated. Apologies for the confusion.
