### ISSUE TITLE
Add Example / Information about Calculating the Units Per Rotation

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#1542]
Not sure if it should go [here](https://docs.wpilib.org/en/latest/docs/software/pathplanning/robot-characterization/configuring-project.html) or probably [here](https://docs.wpilib.org/en/latest/docs/software/pathplanning/robot-characterization/characterization-routine.html) right after the connection

**Comment by Daltz333** [comment]
Can you explain more in depth on what exactly is wanted here?

**Comment by jasondaming** [comment]
There is a field in SysID that we don't explain what to put in it called Units Per Rotation.
![image](https://user-images.githubusercontent.com/15695521/145470144-d60e6b61-2732-4599-a7d5-cb8ee96591b5.png)

I think the easiest thing to do would be to walk through a simple example.  I would propose Falcon on a kitbot as that shows accounting for both gearing and wheel size.
