### ISSUE TITLE
Old RIO imaging tools allow flashing mismatched images

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/frc-docs#1543]
This is from experience:
Flashing the wrong image **works without a problem**, but then the RIO can't establish communication with the DS. Pinging the RIO (in our case, `10.67.38.2`) gets valid responses, but GradleRIO doesn't find the RIO at any address (the `discoverRoborio` task fails, and not with the version mismatch exception).
The Diagnostics tab in the DS has some indicators green and sporadically sees the RIO, but communications are never established.

The connection problems are because netcomm can't load due to different FPGA binaries between the RIO(1) and RIO2.

**Comment by sciencewhiz** [comment]
How did you flash the wrong image? The option for the wrong image was greyed out for me.

**Comment by Starlight220** [comment]
The 2021 version of the imaging tool doesn't have a problem with 2022 RIO2 images.
I know that outdated software isn't really supported, but I think that some teams will try to use it.

When using the 2022 imaging tool I used the RIO(1) image, so I didn't see that it doesn't let you flash the RIO2 image to a RIO.

**Comment by ThadHouse** [comment]
I'd argue theres nothing for us to fix or document here. Its always been the case that you have to use the correct imaging tool for the year you're trying to image. Most teams have done this forever, as unless you know how to do it you can't transfer images between years. So the point here is moot.
