### ISSUE TITLE
Point to Device Simulation page from Drivetrain Simulation tutorial

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/frc-docs#1565]
The [Device Simulation article](https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/robot-simulation/device-sim.html) was added after the [Drivetrain Simulation tutorial](https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/robot-simulation/drivesim-tutorial/simulation-instance.html), but now the latter should point to the former, decreasing redundancy (and there's a possibility that the whole first step of the tutorial is redundant).

**Comment by JTFrye** [comment]
Hello. 
I'm cruising around and making some simple open source contributions tonight. I'm fairly certain I know how to make the change you want, I just need a little more clarity.

When you say 'the latter should point to the former', are you saying that the 'Next' at the bottom of 'Drivetrain Simulation Tutorial' should take you to the Device Sim. Article? 

Or that they need simply rearranged in the column on the left with Drivetrain Simulation being put above Device Simulation?

Or do you want something else?

Sorry for being so basic with the questions. I can make the changes, I'm just new to this and still trying to decipher things quickly on projects I don't particularly know. Working on skills. 

Thank you for your time.

**Comment by Starlight220** [comment]
What I'm thinking about is replacing everything in Step 1 of the tutorial except the first paragraph with something like this:

> Creating and using these simulation objects is described in the Device Simulation article.

(link on the last four words)

Be sure to read [the contributing docs/guidelines](https://docs.wpilib.org/en/latest/docs/contributing/frc-docs/index.html); they specify how to create links and have some more info.

**Comment by Daltz333** [comment]
I don't think we necessary want to replace. The goal of the tutorial is to provide a streamlined process to get simulation up and running. The goal of the simulation docs is to inform and teach the reader. I do agree that it should be linked, that way the user can get a further understanding of how things work than just simply getting it up and running.

**Comment by JTFrye** [comment]
> 

It appears that the two pages are in sequence and can be navigated between with the 'Next' or 'Previous' button respectively. It appears that the first page is a primer on what to do (Device Simulation) and the next page is a primer for the next group of page(index) and the next page is Drivetrain Simulation Tutorial.

I'm assuming what you really want is for the middle page(index) to be eliminated as redundant?

**Comment by Starlight220** [comment]
That's not what I intended; there's no need to mess with the page order/structure or the next/previous buttons.

What I meant was to link to the Device Simulation article from the first step of the tutorial with an explanation similar to what I've enclosed in a previous comment. Per @Daltz333's comment, I think that simply adding another sentence to the first paragraph would be enough; something like this:
> See [link] for more info about these simulation hardware classes and simulation of vendor devices.
