### ISSUE TITLE
Romi supported classes

### ISSUE THREAD

**Issue by agasser** [wpilibsuite/frc-docs#1567]
The Romi Hardware Support [Compatible Classes](https://docs.wpilib.org/en/latest/docs/romi-robot/hardware-support.html#compatible-classes) section says "If a class is not listed here, assume that it is not supported and will not work." However, the example project uses the `Spark` and `BuiltInAccelerometer` classes. Are these classes supported? If so, they should be added to this list. If not, the example should be updated.

This section also says `RomiGyro` and `RomiMotor` are supported classes, but these classes do not exist in WPILib.

**Comment by Daltz333** [comment]
RomiGyro and RomiMotor will be WPILib 2022

**Comment by agasser** [comment]
Great! I checked beta 3 and they weren't there yet. Will the example be updated to remove the `Spark` class?
What about `BuildInAccelerometer`, will that no longer be supported in 2022?
Finally, if these are changing they should be added to the [Change Log](https://docs.wpilib.org/en/latest/docs/yearly-overview/yearly-changelog.html), especially if there will be breaking changes. I assume people will need/want to make updates to their 2021 projects if there are new classes.

**Comment by sciencewhiz** [comment]
I don't see those in 2022 and the examples still use Spark.

**Comment by agasser** [comment]
I just found out there is an undocumented vendordep that includes the Romi classes. I will take a shot at adding this information to the page and send a PR.
https://github.com/wpilibsuite/romi-vendordep/blob/main/RomiVendordep.json

**Comment by sciencewhiz** [comment]
Fixed by #1621
