### ISSUE TITLE
Driver Station with Romi?

### ISSUE THREAD

**Issue by agasser** [wpilibsuite/frc-docs#1568]
[Programming with Romi](https://docs.wpilib.org/en/latest/docs/romi-robot/programming-romi.html#programming-the-romi) says Driver Station can be used with Romi. Is this true? If it is true, can documentation be added for how to connect it?

**Comment by PeterJohnson** [comment]
Essentially, you just run it (on the same computer where you're running the code).

**Comment by agasser** [comment]
I was running WPILib 2021 and it did not work. With 2022-beta4 it is working. Thanks, I will close this issue.
