### ISSUE TITLE
Romi docs say right motor is inverted, it is not

### ISSUE THREAD

**Issue by agasser** [wpilibsuite/frc-docs#1571]
The [Getting to know your Romi page](https://docs.wpilib.org/en/latest/docs/romi-robot/getting-to-know-romi.html) says:

> The right motor is hardwired to spin in a forward direction when forward stick movement is applied on a joystick. Thus there is no need to invert the corresponding motor controller in robot code.

This does not appear to be true. Before 2022 the `DifferentialDrive` class inverted the right motor controller automatically, so maybe this was a misunderstanding. With 2022 beta 4 I have found that the right motor controller needs to be inverted.

**Comment by Daltz333** [comment]
@PeterJohnson @zhiquanyeo ?
