### ISSUE TITLE
Trajectory tutorial Drive Subsystem motor inversion

### ISSUE THREAD

**Issue by agasser** [wpilibsuite/frc-docs#1577]
[Step 3 of the Trajectory tutorial](https://docs.wpilib.org/en/latest/docs/software/pathplanning/trajectory-tutorial/creating-drive-subsystem.html) needs to be updated for 2022 since that `DifferentialDrive` does not invert the right motor controller.

The right `MotorControllers` or `MotorControllerGroup` need to be inverted, and the `tankDriveVolts()` method needs to be updated to _not_ invert the `rightVolts` parameter.

As is, the robot will spin in a circle when the `arcadeDrive()` method is used.

**Comment by Daltz333** [comment]
Waiting on example fix from allwpilib.
