### ISSUE TITLE
Give new command based programming its own branch

### ISSUE THREAD

**Issue by iboyperson** [wpilibsuite/frc-docs#158]
This new command based programming system has yet to be adopted and thus should likely live in its own branch until it is. It was originally moved to devel and was meant to remain there until the new framework was adopted (https://github.com/wpilibsuite/frc-docs/issues/27#issuecomment-487416627), however seeing how devel gets merged to master occasionally it should likely get its own branch until ready to be merged.

**Comment by calcmogul** [comment]
Develop was merged into master permanently. There will only be master from now on. C++ and Java new command-based are complete and are undergoing review, so they should be merged by beta. Screensteps is still the official docs for 2019, so there's nothing wrong with having beta features in the docs. In future years, we'll probably tag the season-end commit so master becomes beta in the offseason.

**Comment by AustinShalit** [comment]
+1 @calcmogul.  Closing in favor of that workflow.
