### ISSUE TITLE
mDNS related info seems to be gone?

### ISSUE THREAD

**Issue by virtuald** [wpilibsuite/frc-docs#1604]
There's text:

> For more information on mDNS resolvers, see the roboRIO Networking article.

But the linked article has nothing about mDNS resolvers. Maybe it did in the past? It also links to another article about mDNS resolvers, but they're nowhere to be found. Probably at least one of them should, and maybe the links should link directly to the section that talks about mDNS in case it moves again?

**Comment by Daltz333** [comment]
Can you link the page this appears on?

**Comment by virtuald** [comment]
https://docs.wpilib.org/en/stable/docs/networking/networking-introduction/roborio-network-troubleshooting.html

**Comment by sciencewhiz** [comment]
It should probably link here: https://docs.wpilib.org/en/stable/docs/networking/networking-introduction/networking-basics.html?highlight=Mdns#mdns

**Comment by TheTripleV** [comment]
It should probably link to https://docs.wpilib.org/en/latest/docs/networking/networking-introduction/networking-basics.html instead.
