### ISSUE TITLE
Add links to vendordep JSONs

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/frc-docs#1625]
We already have a page pointing to vendor websites, but the vendor websites don't make the vendordep JSONs easy to find. The vendordep JSON URL is required to actually install the vendordep in VS Code.

**Comment by Daltz333** [comment]
@koconnor was there a reason we didn't do this previously?

**Comment by Kevin-OConnor** [comment]
Nope! Just make sure it's in addition to not in place of because LV teams need something that's not the vendordep

**Comment by Bankst** [comment]
Here are all the URLs I have collected so far for the 2022 season

PhotonVision: https://maven.photonvision.org/repository/internal/org/photonvision/PhotonLib-json/1.0/PhotonLib-json-1.0.json
NavX: https://www.kauailabs.com/dist/frc/2022/navx_frc.json
Phoenix: https://maven.ctr-electronics.com/release/com/ctre/phoenix/Phoenix-frc2022-latest.json
REVLib: https://software-metadata.revrobotics.com/REVLib.json

**Comment by sciencewhiz** [comment]
One possible counterpoint is that some vendors don't recommend installing with the vendordep, but provide it anyway (CTRE). Additionally for both Rev and CTRE, you need additional software to configure the HW, so skipping the vendor's documentation with just the vendordep may make things worse.
