### ISSUE TITLE
It's MXP not the Onboard I2C Causing System Lockups

### ISSUE THREAD

**Issue by tom131313** [wpilibsuite/frc-docs#1644]
Our I2C sensors work perfectly with onboard I2C.  We take your advice to reduce risk and moved for testing to a MXP RevRobotics MoreBoard v2. 

Testing with a RevRobotics Color Sensor on the MXP yields exactly the **_reversed_** situation from the published issue.

With repeated trials the roboRIO locks up within 0 to 10 seconds from starting the color sensor on the MXP.  There is no response from webpage, SSH, or DS when using the MXP.  The roboRIO will not restart right until the sensor is unplugged from the MXP.  Change sensor back to onboard and everything is okay.  I am hopeful that this is just a documentation error and not actually a problem with BOTH the onboard and MXP (yikes!).

**Comment by Kevin-OConnor** [comment]
It is not a documentation error, the issue had previously only been observed/reported on the onboard I2C port. The MXP port uses a completely different implementation and previous testing, including a stress test that made the issue most likely to exhibit on the onboard port did not seem to trigger it on the MXP port. We will have to dig in further to see if we can replicate your finding. You can find the stress test code here: https://www.chiefdelphi.com/t/robot-keeps-losing-com-and-code-revisited/389391

**Comment by tom131313** [comment]
Our I2C MXP problem seems a bit different than the one described in Chief Delphi but the results are essentially identical so they may be related in some way. Further discussion in this issue isn't helpful to the documentation people and I have no problem with you closing this issue. I'd be glad to troubleshoot some more if further insight is helpful to anyone; just ask what you want us to do. We ran the stress test posted on CD for a few minutes on the onboard and MXP without failure. Our own stress test this afternoon can get instant results. The roboRIO can read the MXP port color sensor every 1 second indefinitely. The roboRIO can read the MXP port color sensor every 0.5 second for about 20 seconds then a couple of read errors were logged and the roboRIO hung. Setting the read cycle to 0.015 second causes an immediate hang. The roboRIO won't reboot even from power off/on unless the color sensor is disconnected. All of these tests run perfectly well on the onboard I2C port. We tested withRevRobotics color sensor v1 with our own software since it predates RevRobotics librariesRevRobotics MoreBoard 2 MXPNI roboRIO p/n 155213C - 01L  s/n 3053804 with a dead ethernet port (happened during a match years ago) so we use a ethernet to USB converter     

---------- Original Message ----------

**Comment by sciencewhiz** [comment]
I may have reproduced this. The symptoms were different then the lockup with the onboard i2c port, though. With the onboard lockup, there was no network communication at all. With the mxp, the DS lost communication, but the robot code kept running and printing to riolog.

**Comment by tom131313** [comment]
I don't want to hijack the documentation area for a non-documentation issue but I'm obliged to report that I cannot reproduce the problem of the roboRIO hanging because of something with the I2C MXP or onboard bus.  I believe I did have something wrong with my I2C attached sensors for the testing and valid errors killed the roboRIO.  Changing nothing but it's a new day and with repeated tests the I2C errors are currently being correctly handled. [The sensors used to work fine but now seem to demand more power than the roboRIO can deliver; I can work with that.]

**Comment by Daltz333** [comment]
Is there further activity on this issue? @sciencewhiz

**Comment by tom131313** [comment]
Our team abandoned I2C entirely as we could not explain and predict errors.  The onboard I2C seemed to work okay for us but we couldn't chance using it in light of the official statement not to use it.  The MXP I2C much of the time was inexplicably unreliable.  We failed to diagnose what the trouble is. With our navX micro, often only the first, single data packet and maybe a second packet was received, then it stopped working. Trying to circumvent I2C there is a problem with USB device discovery using the USB navX micro and a CANivore. We went with all CAN devices by procuring a Pigeon gyro. I don't care if this issue is closed for lack of information.  I'm sure it will be kept it in mind and maybe a pattern will evolve someday or next season's software might not have the problem.

**Comment by tom131313** [comment]
My failing test case of a color sensor on I2C MXP bus is repeatable by NI and they are working on the best correction or circumvention. They think it unlikely that the MXP error has anything to do with the ONBOARD I2C trouble which is still an open issue.
