### ISSUE TITLE
canonical metadata is broken

### ISSUE THREAD

**Issue by TheTripleV** [wpilibsuite/frc-docs#1650]
This affects the copy link share item on iOS.

**Comment by Daltz333** [comment]
Did we determine what causes it?

**Comment by Daltz333** [comment]
We have to be careful with the fix here too, we don't want to break ChiefDelphi links

**Comment by TheTripleV** [comment]
```diff
-html_baseurl = "https://docs.wpilib.org/"
+html_baseurl = "https://docs.wpilib.org/en/stable/"
```

might be all that's needed to fix this.
