### ISSUE TITLE
Online Update for Vendor Deps broken by WPILibNewCommands

### ISSUE THREAD

**Issue by Lyanthropos** [wpilibsuite/frc-docs#1662]
Noticed this error while setting up a fresh 2022 WPI vs-code install. It can be worked around by uninstalling the WPILibNewCommands vendordep. Image below.

<img width="306" alt="Screen Shot 2022-01-15 at 20 45 47" src="https://user-images.githubusercontent.com/11381726/149645351-a3a3e8a7-9988-4ab0-b517-0d5b20a9fa33.png">

**Comment by Daltz333** [comment]
This will be fixed in the next release.

**Comment by ThadHouse** [comment]
Fix being tracked by https://github.com/wpilibsuite/vscode-wpilib/issues/516

**Comment by sciencewhiz** [comment]
This is listed in the known issues: https://docs.wpilib.org/en/stable/docs/yearly-overview/known-issues.html#vs-code-vendor-check-for-updates-broken

**Comment by Lyanthropos** [comment]
My bad, I realize now that I was looking in the wrong repo
