### ISSUE TITLE
Don't generate responsive images on the zip build

### ISSUE THREAD

**Issue by TheTripleV** [wpilibsuite/frc-docs#1686]
The zip build shouldn't have multiple copies of images. Either the originals should to be kept, or the originals should be deleted and replaced with the webp s.

**Comment by Daltz333** [comment]
We should do the webp. Thad will thank us for saving a couple MBs on the installer 😆

**Comment by TheTripleV** [comment]
Sure. That will require modifying the extension.
https://github.com/wpilibsuite/sphinxext-photofinish/blob/main/sphinxext/photofinish/__init__.py#L179 would need to be toggleable.

**Comment by sciencewhiz** [comment]
Fixed by #2034
