### ISSUE TITLE
Video on Weidmuller Connectors section is private

### ISSUE THREAD

**Issue by denommenm** [wpilibsuite/frc-docs#1720]
https://docs.wpilib.org/en/latest/docs/zero-to-robot/step-1/how-to-wire-a-robot.html#weidmuller-connectors

Video is private in this section.

**Comment by denommenm** [comment]
![image](https://user-images.githubusercontent.com/14928822/152913514-b41045f5-af9a-43fb-83ff-7784357e19d6.png)

**Comment by sciencewhiz** [comment]
There's an archived version of the video here: https://web.archive.org/web/20160205225447/https://www.youtube.com/watch?v=kCcDw3lDYis

**Comment by TheTripleV** [comment]
@Kevin-OConnor This video is private on the FIRSTRoboticsCompetition (previously FRCTeamsGlobal channel?). Could you make it public?

If that's not possible, there is also https://www.youtube.com/watch?v=NmmIXMIfdSs which is close in content.
