### ISSUE TITLE
C++ Custom triggers example broken

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#1744]
The directions for creating a custom trigger by subclassing Trigger in C++ is broken because https://github.com/wpilibsuite/allwpilib/pull/2259 removed the virtual Get() method. I'm not sure that there is a solution other then removing subclass example and only referencing the the lambda method for C++.

https://docs.wpilib.org/en/stable/docs/software/commandbased/binding-commands-to-triggers.html#creating-your-own-custom-trigger

**Comment by Starlight220** [comment]
I'm all for removing the subclassing option for both languages; it's unidiomatic and not recommended.
Teams should be using the lambda ctor, *maybe* as a `super()` call from a subclass (like `NetworkButton` etc).
