### ISSUE TITLE
Disable highlighting of search terms in linked result URL.

### ISSUE THREAD

**Issue by Oblarg** [wpilibsuite/frc-docs#1764]

**Comment by sciencewhiz** [comment]
Is there a problem that this causes?

**Comment by Oblarg** [comment]
If you want to share the link (common use-case) you have to trim the URL manually, which sucks.

**Comment by Daltz333** [comment]
It has been an annoyance to myself, and really doesn't benefit that much to the search results.

**Comment by Daltz333** [comment]
Relies on https://github.com/sphinx-doc/sphinx/pull/9551

**Comment by Daltz333** [comment]
Tagged as "Waiting on: FIRST" due to waiting for the competition season to be over before doing a major dependency update.

**Comment by Daltz333** [comment]
You can press "esc" to remove the highlighting from the URL now.
