### ISSUE TITLE
Correct WPILib VSCode Command Name

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#1766]
[Here](https://docs.wpilib.org/en/stable/docs/software/vscode-overview/wpilib-commands-vscode.html?highlight=Simulate%20Robot%20Code%20on%20Desktop#wpilib-commands-in-visual-studio-code) should be "WPILib: Simulate Robot Code" (remove "on Desktop")

Should be: "WPILib C++: Select Current C++ Toolchain"

**Comment by Daltz333** [comment]
I'm confused. ![Screenshot_20220321-140409.png](https://user-images.githubusercontent.com/10674555/159336156-1114b9e6-156e-491a-9a3a-d171813a0db3.png)

**Comment by jasondaming** [comment]
In VSCode it says: "WPILib: Simulate Robot Code"
