### ISSUE TITLE
Typo in Command Based example for Command Binding

### ISSUE THREAD

**Issue by MC42** [wpilibsuite/frc-docs#177]
On [this page](http://docs.wpilib.org/en/latest/docs/software/commandbased/binding-commands-to-triggers.html#binding-a-command-to-a-joystickbutton) the example given would not compile due to the first semicolon on the whenPressed binding.

```
driverController.getButton(XboxController.Button.kX.value)
    // Binds a FooCommand to be scheduled when the `X` button of the driver gamepad is pressed
    .whenPressed(new FooCommand());
    // Binds a BarCommand to be scheduled when that same button is released
    .whenReleased(new BarCommand());```

**Comment by Oblarg** [comment]
Has been addressed in the recent update.
