### ISSUE TITLE
Document how to make angle errors wrap with LQR

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/frc-docs#1786]
Instead of calling `lqr.Calculate(x, r)` to get a voltage, the user can do the following, assuming the angle state is in radians.
In C++:
```cpp
auto error = lqr.R() - x;
error(0) = frc::AngleModulus(units::radian_t{error(0)}).value();
Eigen::Vector<double, 2> u = lqr.K() * error;
```
In Java:
```java
var error = lqr.getR().minus(x);
error.set(0, 0, MathUtil.angleModulus(error.get(0, 0)));
var u = lqr.getK().times(error);
```

**Comment by jasondaming** [comment]
Would this go in the [introduction](https://docs.wpilib.org/en/stable/docs/software/advanced-controls/state-space/state-space-intro.html)?  It doesn't seem to really fit there, but where?

When / why would this be used?

**Comment by Daltz333** [comment]
Maybe using LQR for swerve modules? I'm not sure. Honestly I think having a comprehensive swerve tutorial would be a huge benefit to teams...

**Comment by calcmogul** [comment]
Anything with angles, including turrets, swerve modules, and drivetrains.
