### ISSUE TITLE
Units doc page

### ISSUE THREAD

**Issue by nholthaus** [wpilibsuite/frc-docs#1865]
Not really an issue, feel free to close.

https://github.com/wpilibsuite/frc-docs/blob/stable/source/docs/software/basic-programming/cpp-units.rst

What a a great, succinct introduction. I think you hit all the key points, and probably did a better job than I did!

**Comment by Daltz333** [comment]
On behalf of WPILib and the contributors who helped with that article, thanks. It's readers like you who make it all worthwhile!

**Comment by Daltz333** [comment]
I've been informed that you're actually the author of the library that the article is written about. I just wanted to give a huge thank *you* for writing it and the excellent resources that act as a foundation!
