### ISSUE TITLE
Advanced Controls Simulations - replace system graphic plant with "plant"

### ISSUE THREAD

**Issue by gerth2** [wpilibsuite/frc-docs#1879]
The current system diagram contains a literal picture of a plant. Certain users may or may not get this means "plant"

We should use a less humorous photo, but also find a way to incorporate humor elsewhere.

#funisacorevalue

**Comment by calcmogul** [comment]
Yea, it doesn't really work without context. My controls instructor used that visual pun all the time, but they said it was a plant while they were drawing it the first time.

**Comment by PeterJohnson** [comment]
Could it just be labeled "plant" in addition to the picture?
