### ISSUE TITLE
C++ code examples in dashboard

### ISSUE THREAD

**Issue by SpencerGreene** [wpilibsuite/frc-docs#1908]
Is there a reason why https://github.com/wpilibsuite/frc-docs/blob/stable/source/docs/software/dashboards/shuffleboard/layouts-with-code/configuring-widgets.rst and other dashboard pages have Java examples only, ie are they not supported in C++?  Or, if there's not a technical or policy reason, I'm happy to test and contribute C++ examples.

**Comment by calcmogul** [comment]
The API exists, so I think someone just has to write the examples.

**Comment by Daltz333** [comment]
Yes. Feel free to submit a PR adding C++ examples
