### ISSUE TITLE
RobotContainer initialization in C++ (ref issue #1739)

### ISSUE THREAD

**Issue by SpencerGreene** [wpilibsuite/frc-docs#1909]
Issue #1739 includes a fix in Java example but the same problem remains in the C++ example code.  The C++ code as written creates an infinite loop - `getInstance` finds `m_robotContainer` empty so makes a new one, which then creates a new `TankDrive` command, which calls `getInstance` again until the rio crashes.

**Comment by sciencewhiz** [comment]
This should have been fixed by #1904
