### ISSUE TITLE
Document that mecanum/swerve odometry and pose estimator classes replaced speeds with positions in 2023 changelog

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/frc-docs#1966]
From https://github.com/wpilibsuite/BetaTest/discussions/14#discussioncomment-4103776:
> * SwerveDriveOdometry requires SwerveModulePositions instead of SwerveModuleState, and the distinction between the two wasn't immediately clear, or even whether the Positions class was intended as a replacement or not.

**Comment by rzblue** [comment]
We also need to update the documentation to add the starting SwerveModulePositions to the constructor of SwerveDriveOdometry
