### ISSUE TITLE
Command-based docs rewrite

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/frc-docs#1977]
A lot of the content is outdated, and still has a lot of inertia from commands v1.
<details>
<summary>
Let's start with the problems, going down the TOC:
</summary>

### 2020 Rewrite
I'm questioning whether this page is still needed, even more so at the beginning of the category.
In any case, a fair amount of the information here is outdated.

### "What is Command-based?"
Code samples here are outdated.
Explanations are kindof stilted and bulky, and haven't really been updated from v1.
A lot of content here is duplicate of other articles; due to this being an overview article it wouldn't necessarily a problem if there were links to the in-depth articles.

### Creating a robot project
For some reason, this appears as a TOC item (despite not showing in the index source code), but is only a three-sentence section pointing to the "creating a project" portion of the vscode docs.

### Subsystems
The content here is relatively ok, though the recommendations regarding code structure are rather hostile to command factory methods in the subsystems.

### Commands
This page is great; titles and such could be updated to reflect more accurately that class commands are far from the only way to create commands.

### Command Groups
This should probably be adapted to be more "command compositions". Something feels very outdated, I'm not entirely sure how to explain. Diagrams (maybe with Mermaid? or just drawio as usual) would be great.
Maybe also pull in the decorators article.

### The Command Scheduler
Content here isn't bad, maybe needs some cleanup. The "command event methods" section at the bottom is great.
Might be just on my laptop, but the diagrams are _huge_! Converting them to Mermaid, or even just transposing them (left to right, instead of top to bottom) would help a lot. They could possibly also be rethought a bit, I'm not sure they're helpful and relevant.

### Binding commands to triggers
This article got updated a lot recently.

### Structuring a command-based project
Most of the info here is correct for non-command-based as well, I'm not sure this is a good place for this article. Also, nowadays with projects being generated by VS Code, I'm not sure how much this article is needed at all.

### Convenience Features , Builtin command classes , Decorators 
After being broken out to separate articles about builtin classes and decorators, the "convenience features" article feels empty and unneeded.
Also, it perpetuates the idea that decorators, factories, and builtin command classes are merely "convenience features" and not first-class members of the framework.
Providing a full list of the classes, decorators, and factories could be useful, though there's room to think whether the API docs do that already and linking to them would be enough.
Especially now that decorators and factories are expanding beyond command classes, I think they should be used, shown, and explained throughout the other articles, and less as a separate article.

### (PID | TrapezoidProfile | ProfiledPID) (Subsystem | Command)
Not much to do about these articles.
They're a bit repetitive, maybe there's a way to fold them?
I noticed one of the code examples overriding `ProfiledPIDCommand.isFinished` ; I'm somewhat apprehensive about teams seeing that and overriding methods that are needed for inherent command functionality -- decorators (or some sort of composition) should be used instead.

### Organizing Command-based projects
The title here is somewhat confusing with the "Structuring a command-based project" article, but that should be solved by renaming this article and/or addressing my comments about that article being out of place.
As for content, this article is new and great.

### Technical C++ Discussion
Most of this is accurate, but some updates for CommandPtr need to be made.

</details>

---

<details>
<summary>
Suggested Refactored Structure:
</summary>

### Overview
- First few paragraphs from "What is Command-based?", explaining that it's a declarative paradigm, etc.
- Introduce the concept of commands, that they represent actions. Show a requirement-less example with `Commands.runOnce()` (printing, opening a piston, something like that). 
- Bind to trigger. (maybe merge this with the above for coherence). Link to separate trigger article.
- Introduce the concept of subsystems, in the context of requirements. Link to separate subsystem article.
- Show command compositions? (maybe this should be merged into something earlier?) Link to separate compositions article.

### Commands
In-depth article about commands, similar to current article, covering:
- command lifecycle methods (init, exe, isFinished, end) and mention class commands. Take 
- command properties (requirements, interruptionBehavior, runsWhenDisabled)

### Command Compositions
(maybe merge this with the above Commands article?)
Describe compositions (group classes, factories, decorators) in general, and go into details about specific compositions.

### Subsystems
Not many changes from existing doc needed, just needs to not be hostile to command factories in the subsystem. If the factories in the `Subsystem` interface get merged, document them here.

### Triggers
As is. Maybe change a bit to highlight more usage of non-HID triggers.

### Organizing Commands, aka "Where to write this command?"
I don't think this needs deep changes, maybe some links.

### Scheduler
Go over relatively niche technical details:
- enabling/disabling the scheduler
- command event listeners
- operation orders (maybe even RLI the impl here?)
This is fairly similar to the current article.

### Technical C++ Discussion
Update for CommandPtr, but other than that, as-is.

### (PID | TrapezoidProfile | ProfiledPID) (Subsystem | Command)
If we don't come up with a way to fold these, keep them as-is.

</details>

---
Thoughts?

**Comment by sciencewhiz** [comment]
Given that old commands was only removed this year, the migration guide should be retained and updated. But it could be removed next year. It could also be moved down the TOC.

**Comment by Oblarg** [comment]
We should deprecated PIDCommand/PIDSubsystem entirely, and remove the articles that reference them ;)
