### ISSUE TITLE
Add a common terminology glossary page

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#198]
There should be a description of deprecated somewhere. Most high school students don't know what it means, and when they see warnings they think their code is broken.

**Comment by Daltz333** [comment]
I feel like this is something we shouldn't need to define, as thats a quick google search. And the definition can also be insinuated from context clues.

**Comment by ThadHouse** [comment]
Students don't know how to read context clues. Especially because we use it a decent amount, this is absolutely something extremely useful

**Comment by sciencewhiz** [comment]
besides the definition that can be looked up, it also gives a chance to define what it means for wpilib (will be maintained for at least 1 year, may be removed after that).

**Comment by Daltz333** [comment]
We'll probably be creating a vocabulary or common FRC terminology page.

**Comment by sciencewhiz** [comment]
Here's an example where someone thought deprecated wouldn't work on the field. https://www.chiefdelphi.com/t/what-will-happen-if-ill-use-the-old-command-based-programming-method/371412

**Comment by Starlight220** [comment]
This can easily be done using a tooltip, perhaps with expansion in a future terminology page

**Comment by Daltz333** [comment]
I'm going to rename this issue to represent adding a terminology page.

**Comment by Starlight220** [comment]
Needed Terms:
- [ ] Deprecated
- add here

**Comment by Daltz333** [comment]
Tooltips are bound using the following

```
Sometimes I like eating :term:`apples`
```
or
```
Sometimes I really like eating :term:`apples <Apples>`
```

**Comment by Starlight220** [comment]
And then I assume that there is a file/section with definitions for all the terms? If something like that exists, why not use it as a glossary/terminology page and that's it?

**Comment by Daltz333** [comment]
Currently there is only one glossary section for mathematics terms.

**Comment by jasondaming** [comment]
I am working on this now.  Searching for terms that should be included, let me know if you have some!
