### ISSUE TITLE
Add note that wpilib must be installed to use Shuffleboard and SmartDashboard

### ISSUE THREAD

**Issue by rzblue** [wpilibsuite/frc-docs#1985]
Currently this is only mentioned on the wpilib installation page- it should be mentioned somewhere on a Driver Station page, whether that's install or dashboard setup. It's not otherwise clear that the game tools installer does not install the dashboards listed in the driver station drop-down.

**Comment by Daltz333** [comment]
Note, it is mentioned here

https://frc-docs--1924.org.readthedocs.build/en/1924/docs/software/driverstation/driver-station.html

![image](https://user-images.githubusercontent.com/10674555/202283226-c13879a3-3a38-4e70-8eee-5b590b980699.png)
