### ISSUE TITLE
Document standard installation procedure

### ISSUE THREAD

**Issue by yellowjaguar5** [wpilibsuite/frc-docs#199]
I can't find an equivalent page to the [`Installing C++ and Java Development Tools for FRC`](https://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/999999-installing-c-and-java-development-tools-for-frc) on Screensteps. Does this need to be ported or is it just in a new location? If it's already been ported, can it be prominently located on the home page or in another prominent position?

**Comment by Daltz333** [comment]
Its just a navigation page for the windows Mac and Linux setup guides in getting started.

**Comment by Daltz333** [comment]
http://docs.wpilib.org/en/latest/docs/software/getting-started/windows-setup.html
