### ISSUE TITLE
Unable to access WPILib Java Docs

### ISSUE THREAD

**Issue by Rmccawley** [wpilibsuite/frc-docs#1997]
Unable to access WPILib Java Docs. 

Error:
“Forbidden

You don't have permission to access /wpilib/allwpilib/docs/release/java/index.html on this server.”

**Comment by Starlight220** [comment]
We're aware of the issue and working on a solution. 
A mirror of the API docs is also available at https://github.wpilib.org/allwpilib/docs/release/java/index.html
