### ISSUE TITLE
Spelling error on AprilTag docs page

### ISSUE THREAD

**Issue by mdurrani808** [wpilibsuite/frc-docs#2008]
"Many of the pictures in this documentation are from the 32H11 family, which are similar (but not identical) to the 16H5 actually in use for FRC. All the underlying concepts are the same."

Should be 36h11.

**Comment by mdurrani808** [comment]
It says that all tags will be 8in wide but the picture says 6in. 6in is the correct value.

**Comment by mdurrani808** [comment]
"Using a camera, identify the _centroid_ of the apriltags in view. "
underline shouldnt be there

**Comment by gerth2** [comment]
@sciencewhiz I just pushed again specifically to close out this issue. It'll likely conflict - sorry - moto poked me on discord about it, looks like we ended up doing it at the same time. I'll hold off on more pushes till I get back to faster internet. However stuff gets merged in is fine by me.
