### ISSUE TITLE
Invalid escape sequence

### ISSUE THREAD

**Issue by sou-maru** [wpilibsuite/frc-docs#2016]
OS : Windows 10
Software : FRC VS Code 2020 (1.41.1)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project '?????'.
Exception thrown while executing model rule: NativeBinaryRules#assignTools(NativeBinarySpec, NativeToolChainRegistryInternal, ProjectLayout)
   **com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 16 column 38 path $[0].description**   

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

**Comment by sciencewhiz** [comment]
Is this for WorldSkills?

**Comment by sou-maru** [comment]
> Is this for WorldSkills?
Yes.

**Comment by sciencewhiz** [comment]
As WorldSkills uses a forked very old version, you should seek support from them.
