### ISSUE TITLE
Benchtop Test program is a bad name for introductory docs

### ISSUE THREAD

**Issue by mdurrani808** [wpilibsuite/frc-docs#2020]
https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-4/creating-benchtop-test-program-cpp-java.html

As a rookie, benchtop test program won't make sense to me. I want code that will get my robot working.

Rename to creating your first robot program

**Comment by Daltz333** [comment]
Note that references in the corresponding hardware article should be updated.
