### ISSUE TITLE
3rd party libraries bad sentence

### ISSUE THREAD

**Issue by mdurrani808** [wpilibsuite/frc-docs#2027]
https://github.com/wpilibsuite/frc-docs/blob/stable/source/docs/software/vscode-overview/3rd-party-libraries.rst

spark max in kop yet still need 3rd party library

**Comment by Daltz333** [comment]
Not really. We only provide wiring and code examples for PWM control. And the spark max is the only item where additional software *could* be required. Additionally, the verbiage does use "likely" here.
