### ISSUE TITLE
Add Hardware Section about Pneumatics

### ISSUE THREAD

**Issue by yellowjaguar5** [wpilibsuite/frc-docs#203]
I understand this project is primarily interested in software and (electronic) hardware for FRC (please correct me if I'm wrong), but I'm interested to know if there could be an additional section on pneumatics. Articles could include wiring of solenoids, example schematics, tubing tips and more. Please let me know if frc-docs is the right place for this sort of information, and if not, where it could go.

**Comment by sciencewhiz** [comment]
I think a lot of that exists in the pneumatics manual. https://firstfrc.blob.core.windows.net/frc2017/pneumatics-manual.pdf

**Comment by yellowjaguar5** [comment]
Thanks, @sciencewhiz. I just discovered that the page on [Using the Compressor in LabView](https://docs.wpilib.org/en/latest/docs/software/labview/resources/using-the-compressor-in-labview.html) links to that document, but it's not mentioned anywhere else. Should it also be mentioned on the [Wiring Pneumatics](https://docs.wpilib.org/en/latest/docs/hardware/getting-started/wiring-pneumatics.html) page? I also noticed that it was last updated in 2017; has anything changed for pneumatics since then?

**Comment by samneff72** [comment]
@yellowjaguar5 does this address your issue? 

Nothing that a team building a kit of parts based pneumatics system would care about has changed since 2017.

**Comment by yellowjaguar5** [comment]
#218 addresses my issues. Thanks!

**Comment by samneff72** [comment]
@yellowjaguar5 do you want to leave this open for an additional commit to add more images/details - or close as addressed by #254 ?

**Comment by yellowjaguar5** [comment]
I think this has been fixed by #254.
