### ISSUE TITLE
How to wire a PDH robot

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/frc-docs#2030]
How to wire a robot (https://docs.wpilib.org/en/latest/docs/zero-to-robot/step-1/how-to-wire-a-robot.html) only describes how to wire a PDP.  It does not provide instructions for how to wire a REV PDH.  Maybe there should be two versions of this article?

**Comment by Kevin-OConnor** [comment]
This is on my to-do for later this week. I just took a bunch of the pictures for it when we built a board for a video on basic robot wiring that should be up sometime in the next month

**Comment by sciencewhiz** [comment]
Fixed by #2080
