### ISSUE TITLE
Add a known issue to stable about GitHub connections

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#2037]
Need to update VS Code or use alternate git client. https://www.chiefdelphi.com/t/wpi-lib-issues-connecting-with-github/419575 
https://www.chiefdelphi.com/t/please-upgrade-vs-code-publish-branch/413734

**Comment by Starlight220** [comment]
The 2023 release in less than a month (and the betas already released) would resolve the issue. Do we want to add a known issue for that short a time?
