### ISSUE TITLE
Add link to AdvantageScope

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/frc-docs#2057]
[AdvantageScope](https://github.com/Mechanical-Advantage/AdvantageScope)  is a standalone data log analysis (viewer) application that implements most of what we originally envisioned for such a tool.  Adding a link in the data log section would bring greater visibility to teams.

**Comment by sciencewhiz** [comment]
Note that AdvantageKit is linked here: https://docs.wpilib.org/en/latest/docs/software/telemetry/3rd-party-libraries.html?highlight=Advantagekit#third-party-telemetry-libraries

**Comment by PeterJohnson** [comment]
Note these are two different things, as AdvantageScope does not require use of AdvantageKit, and is a tool (like Pathplanner) rather than a library.
