### ISSUE TITLE
Add instructions on targeting Java 17

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/frc-docs#2061]
We're testing JDK17 this year, but it's opt-in, so unless we document how to target it, I doubt it'll get much testing.

**Comment by Daltz333** [comment]
The testing is for loop times and performance, not features.

**Comment by Daltz333** [comment]
I disagree that we should have instructions in frc-docs. The testing is to ensure that the Java 17 JVM ensures accurate loop times, not for features. We shouldn't recommend it either. If a team opts-in and we are forced to revert, they could potentially have to rewrite portions of their robot program. I would argue documentation here belongs in the GradleRIO README.
