### ISSUE TITLE
CTRE vendordep link is still 2022

### ISSUE THREAD

**Issue by superpenguin612** [wpilibsuite/frc-docs#2081]
On https://docs.wpilib.org/en/stable/docs/software/vscode-overview/3rd-party-libraries.html, the CTRE Phoenix Framework vendordep URL is still the 2022 version, even after the kickoff release. Additionally, the Phoenix Pro vendordep should also probably be mentioned.

**Comment by sciencewhiz** [comment]
Has the 2023 version been released? It's not mentioned here: https://store.ctr-electronics.com/software/

**Comment by sciencewhiz** [comment]
> but the link will still be valid and doesn't need to change.

Won't there be a new link for 2023? The vendordep link has 2022 in the url.

**Comment by JCaporuscio** [comment]
Correct - I edited my response above.

**Comment by SprinterDave** [comment]
Although it appears to be a 2022 link, (https://maven.ctr-electronics.com/development/com/ctre/phoenix/Phoenix-frc2022-latest.json) leads to a page not found error.  The correct 2022 link appears to be https://maven.ctr-electronics.com/release/com/ctre/phoenix/Phoenix-frc2022-latest.json

**Comment by sciencewhiz** [comment]
Fixed in #2105
