### ISSUE TITLE
GenericEntry error not documented

### ISSUE THREAD

**Issue by blu28** [wpilibsuite/frc-docs#2093]
**Describe the bug**
With the 2023.1.1 WPILib, after import my robot build fails with the error "incompatible types: GenericEntry cannot be converted to NetworkTableEntry".  The code was following the example Shuffleboard code that looks like this:

private NetworkTableEntry m_maxSpeed;
 m_maxSpeed =
        Shuffleboard.getTab("Configuration")
            .add("Max Speed", 1)
            .withWidget("Number Slider")
            .withPosition(1, 1)
            .withSize(2, 1)
            .getEntry();

The example has been changed in the current code base to change "NetworkTableEntry" to "GenericEntry".  This change was made as part of the Network Tables 4 project. Since the example was changed this was obviously a known issue, but it is not mentioned in the docs as a known issue, breaking change or any other kind of change. I don't know if the docs need to be changed or if it is a bug that GenericEntry cannot be converted to a NetworkTableEntry, but one or the other should be fixed.

**To Reproduce**
Compile the Shuffleboard example from 2022.

**Expected behavior**
The example compiles.
Instead you get the error.

**Desktop (please complete the following information):**
 - WPILib Version: 2023.1.1
 - OS: Windows 10
 - Java version 17.0.5

**Comment by PeterJohnson** [comment]
Yes, it needs to be documented as a breaking change.  The fix is easy, just change NetworkTableEntry to GenericEntry.
