### ISSUE TITLE
gradle failing to build, errors not displaying

### ISSUE THREAD

**Issue by GreggChase** [wpilibsuite/frc-docs#2123]
gradle is failing to build every time, displaying this message:
* Where:
Build file '/Users/greggchase/Documents/GitHub/c2023/build.gradle' line: 4

* What went wrong:
Plugin [id: 'com.peterabeles.gversion', version: '1.10'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.peterabeles.gversion:com.peterabeles.gversion.gradle.plugin:1.10')
  Searched in the following repositories:
    MavenLocal(file:/Users/greggchase/.m2/repository)
    Gradle Central Plugin Repository
    frcHome(file:/Users/greggchase/wpilib/2023/maven/)
and errors are not displaying.

**Comment by Starlight220** [comment]
Is this with an unmodified `build.gradle` generated by the WPILib project creator?
Are you sure that plugin exists?

**Comment by sciencewhiz** [comment]
Are you connected to the internet when building so that plug-in can be downloaded?

**Comment by GreggChase** [comment]
the build.gradle file seems to have additional code added, when I create a new project, it works. it appears the issue is the additional code.
