### ISSUE TITLE
Code in pose estimator article out of date

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/frc-docs#2162]
The code [here](https://docs.wpilib.org/en/stable/docs/software/advanced-controls/state-space/state-space-pose-estimators.html) doesn't compile. The code should be replaced with RLIs to the DifferentialDrivePoseEstimator example.

Adding another section showing calls to `update` and/or `updateWithTime` would also be a good improvement, as will mentioning the default stddevs.

**Comment by calcmogul** [comment]
We should also add guidance on the odometry and vision standard deviations, like this:
> "In general, trust vision rotation data as little as possible, trust gyro rotation data more, and scale the vision x and y trust by distance to the tag."
