### ISSUE TITLE
Missing information/ incorrect information

### ISSUE THREAD

**Issue by ThomasCrund** [wpilibsuite/frc-docs#217]
Issues:

- [x] The c++ [Compressor snippet](https://frc-docs.readthedocs.io/en/latest/docs/software/actuators/pneumatics.html#generating-and-storing-pressure) When creating the compressor object after the changes in 2018 you now need the frc namespace before. `frc::Compressor *c = new frc::Compressor(0);` Also the asterix is missing for the pointer. 
- [ ] On the [Smartdashboard examples](https://frc-docs.readthedocs.io/en/latest/docs/software/wpilib-tools/smartdashboard/displaying-expressions.html) there is no c++ examples/explanations for setting values for Smartdashboard
- [x] The c++ [Servo snippet](https://frc-docs.readthedocs.io/en/latest/docs/software/actuators/servos.html#repeatable-low-power-movement-controlling-servos-with-wpilib) also does not have the frc namespace included `frc::Servo *exampleServo = new frc::Servo(1);`

**Comment by sciencewhiz** [comment]
The first one is fixed by #314. The last one is fixed by #310.

**Comment by Starlight220** [comment]
I think the second one is resolved too. The Java and C++ code is functionally identical, neither has comments/documentation.
