### ISSUE TITLE
Operating Pneumatic Cylinder references now-illegal methods

### ISSUE THREAD

**Issue by Billfred** [wpilibsuite/frc-docs#2176]
https://github.com/wpilibsuite/frc-docs/blob/stable/source/docs/software/hardware-apis/pneumatics/pneumatics.rst#generating-and-storing-pressure, emphasis mine:

> Pressure is created using a pneumatic compressor and stored in pneumatic tanks. **The compressor doesn't necessarily have to be on the robot**, but must be powered by the robot's pneumatics module.

This has not been legal for the last couple seasons (for 2023, R805-a and R806 indicate it's required).  The page probably needs the standard "read the manual" note at a minimum.

**Comment by sciencewhiz** [comment]
Fixed by #2172
