### ISSUE TITLE
Fix Git Data in Deploy not being correct

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/frc-docs#2182]
https://docs.wpilib.org/en/stable/docs/software/advanced-gradlerio/deploy-git-data.html

That task will run entirely during configuration time, and theres no point in even having it being a task. It either needs to mostly be in a doLast, but to do so will require some other changes as well.

**Comment by ctorek** [comment]
Hi! I'm the original author of this: I understand it isn't optimal but i wasn't working from the best Gradle knowledge (and still am not) and there are definitely not a lot of resources available on the proper idiomatic ways to have implemented that

My understanding of this is that it does not matter when the `writeBranchName` and `writeCommitHash` tasks run (in terms of functionality), as long as it happens once per deploy task before the `src/main/deploy/` directory is copied to the roborio. Last I was aware, this functions as intended. That being said, I am open to working on this to make it more idiomatic.

Are you saying that there should be a `doLast` that runs after the `deploy` task and copies the files to the rio over ssh? This was something I considered initially but I figured the extra steps could be bypassed by taking advantage of the static file deploy.

**Comment by ThadHouse** [comment]
The issue with it currently is that it doesn't write the files when the `writeBranchName` and `writeCommitHash` tasks actually run. Instead, they run whenever the task is configured.

Its one of the gradle isms that takes a long time to get used to. What happens inside a task block doesn't run when the task executes, but is instead part of configuring the task. You either have to use a custom task type or a doLast block to actually have things run as part of test execution.

What exists now would work exactly the same as if you removed the task completely, and just moved everything out to global scope. There would be no difference in be behavior. 

That would mostly be fixed by the following code 

```
tasks.register("writeBranchName") {
  doLast {
   // Define an output stream to write to instead of terminal
   def stdout = new ByteArrayOutputStream()

   // Execute the git command
   exec {
      commandLine "git", "rev-parse", "--abbrev-ref", "HEAD"
      // Write to the output stream instead of terminal
      standardOutput = stdout
   }

   // Parse the output into a string
   def branch = stdout.toString().trim()

   // Create a new file
   new File(
      // Join project directory and deploy directory
      projectDir.toString() + "/src/main/deploy",
      // File name to write to
      "branch.txt"
   ).text = branch // Set the contents of the file to the variable branch
}
}
```

But that wouldn't handle incremental properly, and wouldn't run every time the hash changes. Theres some extra work needed to make all of that work correctly.

**Comment by ctorek** [comment]
I don't think it'd matter if it runs every time the hash changes, since the main intention is only that the hash at the time of the deploy is captured.

Can you elaborate on how incremental builds might impact this? Would Gradle attempt to optimize/cache this task so that it doesn't run under certain circumstances?
