### ISSUE TITLE
Dataset directory structure for uploading from Supervisly

### ISSUE THREAD

**Issue by gofmannir** [wpilibsuite/frc-docs#2198]
Hi,
Created a dataset in Supervisly and Im downloading the tar file to upload to the Axon app. (Built with Docker)
In Supervisly there are a lot of options to export the dataset like:
"Export only labled iteam", "Export to COCO", "Export to supervisly format", "Export metadata" and so on..
When I uploaded the zip/tar file and click "Start training" it's prompting for success but there nothing happend.
So I opened the logs of the app and I saw that Axon looking for _annotations.csv file (and others) but Supervisly doesn't export the dataset that way.
How to export the dataset from Supervisly so that the Axon work with the required format?

Thanks, 
Nir.

**Comment by Daltz333** [comment]
Axon is no longer maintained and I don't think any of us active are able to give support. You could try posting on ChiefDelphi or related forums for help.
