### ISSUE TITLE
Creating a custom Shuffleboard widget needs to be updated

### ISSUE THREAD

**Issue by Tyson453** [wpilibsuite/frc-docs#2215]
The current [documentation](https://github.com/wpilibsuite/frc-docs/blob/aa6d88760a4bc8c6cf6eb066e879cba98ca0c497/source/docs/software/dashboards/shuffleboard/custom-widgets/creating-a-new-widget.rst) uses imports from `edu.wpi.first.shuffleboard` which does not exist in the [wpilib api](https://github.wpilib.org/allwpilib/docs/release/java/index.html)

**Comment by PeterJohnson** [comment]
Shuffleboard plugins are not part of the WPILib API.  They're part of the Shuffleboard plugin API.  See https://docs.wpilib.org/en/stable/docs/software/dashboards/shuffleboard/custom-widgets/creating-plugins.html#building-plugin

**Comment by Tyson453** [comment]
@PeterJohnson Is there something special I need to do to import from `edu.wpi.first.shuffleboard`? I tried doing the same thing that is done in the documentation but get an error.
