### ISSUE TITLE
Romi not available on WPILibPi -Romi image

### ISSUE THREAD

**Issue by gbuckholtz** [wpilibsuite/frc-docs#2239]
1. Downloaded image
2. sudo dd if=/dev/disk4 of=WPILibPi_64-v2023.2.1_2023-02-19-Romi.img bs=512
3. Wifi not broadcasting
4. connect through ethernet
5. navigate to http://wpilibpi.local
6. No Romi in the navigation blade
<img width="1023" alt="Screen Shot 2023-04-04 at 4 38 42 PM" src="https://user-images.githubusercontent.com/1216916/229915742-4dda073d-d137-417e-a437-0a2401683f13.png">

**Comment by PeterJohnson** [comment]
I guess something must have broken in our build scripts such that the Romi pieces weren’t installed in that version of the image.  I assume there’s no `/boot/romi.json` file?

**Comment by gbuckholtz** [comment]
Correct,  there is no romi.json.

**Comment by PeterJohnson** [comment]
I can't reproduce this--at least when checking the raw image, the WPILibPi_64_image-v2023.2.1_2023-02-19-Romi.img file definitely has the Romi bits in it.

**Comment by sciencewhiz** [comment]
Note that your dd command is backwards

**Comment by gbuckholtz** [comment]
I will give It another try.

**Comment by gbuckholtz** [comment]
> Note that your dd command is backwards

That would do it. :P

I should probably download the image again before flashing to the SD card. :D
