### ISSUE TITLE
Incorrect CAN ID or API ID for heartbeat

### ISSUE THREAD

**Issue by grnnja** [wpilibsuite/frc-docs#2241]
https://github.com/wpilibsuite/frc-docs/blob/f2b037b939284fd4bb3e21cc6b3cb70de6236e64/source/docs/software/can-devices/can-addressing.rst?plain=1#L194

Here it says the CAN ID for the heartbeat is: `0x01011840` and the api id is `0x062`

if you convert the CAN ID to binary and pad to 29 bits you get: `00001000000010001100001000000`

breaking up into device type(5 bits), manufacturer(8 bits), api id(10 bits) and device id(6 bits): `00001 00000001 0001100001 000000`

So the api id is `0001100001`

converting back to hex we get `0x061` which is not equal to `0x062`.

**Comment by Daltz333** [comment]
Pinging @ThadHouse

**Comment by ThadHouse** [comment]
The full arbitration id is correct, and the API ID is 0x61. So the API ID needs to be fixed in the docs.
