### ISSUE TITLE
Image Filenames and Accessibility

### ISSUE THREAD

**Issue by Modelmat** [wpilibsuite/frc-docs#225]
Images should be renamed from `imageXX` to a meaningful name.
Alt text should also be added in the RST.

**Comment by Modelmat** [comment]
A by no means exhaustive list of files which contain this issue are listed below, obtained through `find . -type f -exec file {} \; | awk -F: '{if ($2 ~/image/) print $1}' | grep "[0-9]\."`

<details>
<summary>List</summary>

./source/docs/hardware/sensors/images/serial-buses/roborio-rs232.png
./source/docs/hardware/hardware-basics/images/wiring-pneumatics/pcm01.jpg
./source/docs/networking/networking-introduction/images/om5p-ac-radio-modification-3.png
./source/docs/networking/networking-introduction/images/windows-firewall-configuration-6.png
./source/docs/networking/networking-introduction/images/measuring-bandwidth-usage-9.png
./source/docs/networking/networking-introduction/images/measuring-bandwidth-usage-1.png
./source/docs/networking/networking-introduction/images/om5p-ac-radio-modification-7.png
./source/docs/networking/networking-introduction/images/om5p-ac-radio-modification-4.png
./source/docs/networking/networking-introduction/images/measuring-bandwidth-usage-7.png
./source/docs/networking/networking-introduction/images/measuring-bandwidth-usage-5.png
./source/docs/networking/networking-introduction/images/windows-firewall-configuration-3.png
./source/docs/networking/networking-introduction/images/om5p-ac-radio-modification-10.png
./source/docs/networking/networking-introduction/images/om5p-ac-radio-modification-8.png
./source/docs/networking/networking-introduction/images/om5p-ac-radio-modification-2.png
./source/docs/networking/networking-introduction/images/measuring-bandwidth-usage-8.png
./source/docs/networking/networking-introduction/images/om5p-ac-radio-modification-1.png
./source/docs/networking/networking-introduction/images/windows-firewall-configuration-5.png
./source/docs/networking/networking-introduction/images/measuring-bandwidth-usage-2.png
./source/docs/networking/networking-introduction/images/om5p-ac-radio-modification-9.png
./source/docs/networking/networking-introduction/images/om5p-ac-radio-modification-6.png
./source/docs/networking/networking-introduction/images/measuring-bandwidth-usage-4.png
./source/docs/networking/networking-introduction/images/measuring-bandwidth-usage-6.png
./source/docs/networking/networking-introduction/images/om5p-ac-radio-modification-5.png
./source/docs/networking/networking-introduction/images/measuring-bandwidth-usage-10.png
./source/docs/networking/networking-introduction/images/windows-firewall-configuration-2.png
./source/docs/networking/networking-introduction/images/measuring-bandwidth-usage-3.png
./source/docs/networking/networking-introduction/images/windows-firewall-configuration-1.png
./source/docs/software/driverstation/images/programming-radios-for-fms-offseason-4.png
./source/docs/software/driverstation/images/programming-radios-for-fms-offseason-1.png
./source/docs/software/driverstation/images/troubleshooting-dashboard-connectivity-1.png
./source/docs/software/driverstation/images/programming-radios-for-fms-offseason-9.png
./source/docs/software/driverstation/images/troubleshooting-dashboard-connectivity-2.png
./source/docs/software/driverstation/images/programming-radios-for-fms-offseason-3.png
./source/docs/software/driverstation/images/programming-radios-for-fms-offseason-8.png
./source/docs/software/driverstation/images/programming-radios-for-fms-offseason-7.png
./source/docs/software/driverstation/images/imaging-your-classmate/confirmation-dialog-2.png
./source/docs/software/driverstation/images/imaging-your-classmate/confirmation-dialog-1.png
./source/docs/software/driverstation/images/programming-radios-for-fms-offseason-5.png
./source/docs/software/driverstation/images/troubleshooting-dashboard-connectivity-3.png
./source/docs/software/driverstation/images/programming-radios-for-fms-offseason-6.png
./source/docs/software/driverstation/images/programming-radios-for-fms-offseason-2.png
./source/docs/software/old-commandbased/commands/images/scheduling-commands/image1.png
./source/docs/software/old-commandbased/commands/images/scheduling-commands/image4.png
./source/docs/software/old-commandbased/commands/images/scheduling-commands/image3.png
./source/docs/software/old-commandbased/commands/images/scheduling-commands/image2.png
./source/docs/software/old-commandbased/commands/images/synchronizing-two-commands/image1.png
./source/docs/software/old-commandbased/commands/images/synchronizing-two-commands/image3.png
./source/docs/software/old-commandbased/commands/images/synchronizing-two-commands/image2.png
./source/docs/software/old-commandbased/commands/images/commands-joystick-input/image1.png
./source/docs/software/old-commandbased/commands/images/using-limit-switches/image1.png
./source/docs/software/old-commandbased/basics/images/adding-commands-subsystems/image1.png
./source/docs/software/old-commandbased/basics/images/adding-commands-subsystems/image6.png
./source/docs/software/old-commandbased/basics/images/adding-commands-subsystems/image5.png
./source/docs/software/old-commandbased/basics/images/adding-commands-subsystems/image4.png
./source/docs/software/old-commandbased/basics/images/adding-commands-subsystems/image3.png
./source/docs/software/old-commandbased/basics/images/adding-commands-subsystems/image2.png
./source/docs/software/old-commandbased/basics/images/what-is-commandbased/image1.png
./source/docs/software/old-commandbased/basics/images/what-is-commandbased/image6.png
./source/docs/software/old-commandbased/basics/images/what-is-commandbased/image5.png
./source/docs/software/old-commandbased/basics/images/what-is-commandbased/image4.png
./source/docs/software/old-commandbased/basics/images/what-is-commandbased/image3.png
./source/docs/software/old-commandbased/basics/images/what-is-commandbased/image2.png
./source/docs/software/vision-processing/raspberry-pi/images/the-raspberry-pi-frc-console/vision-settings-2.png
./source/docs/software/vision-processing/raspberry-pi/images/the-raspberry-pi-frc-console/vision-settings-1.png
./source/docs/software/vision-processing/raspberry-pi/images/the-raspberry-pi-frc-console/application-2.png
./source/docs/software/vision-processing/raspberry-pi/images/the-raspberry-pi-frc-console/vision-settings-3.png
./source/docs/software/vision-processing/raspberry-pi/images/the-raspberry-pi-frc-console/application-1.png
./source/docs/software/vision-processing/raspberry-pi/images/the-raspberry-pi-frc-console/application-3.png
./source/docs/software/labview/resources/images/add-an-independent-motor-to-a-project/4.png
./source/docs/software/labview/resources/images/add-an-independent-motor-to-a-project/2.png
./source/docs/software/labview/resources/images/add-an-independent-motor-to-a-project/3.png
./source/docs/software/labview/resources/images/add-an-independent-motor-to-a-project/1.png
./source/docs/software/labview/resources/images/making-a-one-shot-button-press/4.png
./source/docs/software/labview/resources/images/making-a-one-shot-button-press/7.png
./source/docs/software/labview/resources/images/making-a-one-shot-button-press/2.png
./source/docs/software/labview/resources/images/making-a-one-shot-button-press/6.png
./source/docs/software/labview/resources/images/making-a-one-shot-button-press/3.png
./source/docs/software/labview/resources/images/making-a-one-shot-button-press/1.png
./source/docs/software/labview/resources/images/making-a-one-shot-button-press/5.png
./source/docs/software/labview/resources/images/waiting-for-target-to-respond/problem-1.png
./source/docs/software/labview/resources/images/local-and-global-variables-in-labview-for-frc/4.png
./source/docs/software/labview/resources/images/local-and-global-variables-in-labview-for-frc/2.png
./source/docs/software/labview/resources/images/local-and-global-variables-in-labview-for-frc/6.png
./source/docs/software/labview/resources/images/local-and-global-variables-in-labview-for-frc/3.png
./source/docs/software/labview/resources/images/local-and-global-variables-in-labview-for-frc/1.png
./source/docs/software/labview/resources/images/local-and-global-variables-in-labview-for-frc/5.png
./source/docs/software/labview/resources/images/how-to-use-joystick-buttons-to-control-motors-or-solenoids/2.png
./source/docs/software/labview/resources/images/how-to-use-joystick-buttons-to-control-motors-or-solenoids/3.png
./source/docs/software/labview/creating-robot-programs/images/command-and-control-tutorial/step-3.jpg
./source/docs/software/labview/creating-robot-programs/images/command-and-control-tutorial/step-2.jpg
./source/docs/software/labview/creating-robot-programs/images/command-and-control-tutorial/step-1.jpg
./source/docs/software/labview/creating-robot-programs/images/command-and-control-tutorial/step-4.jpg
./source/docs/software/labview/creating-robot-programs/images/command-and-control-tutorial/project-explorer-1.png
./source/docs/software/labview/creating-robot-programs/images/command-and-control-tutorial/step-5.jpg
./source/docs/software/labview/creating-robot-programs/images/command-and-control-tutorial/project-explorer-2.jpg
./source/docs/software/labview/creating-robot-programs/images/tank-drive-tutorial/block-diogram-3.png
./source/docs/software/labview/creating-robot-programs/images/tank-drive-tutorial/block-diogram-2.png
./source/docs/software/basic-programming/images/image1.png
./source/docs/software/basic-programming/images/image6.png
./source/docs/software/basic-programming/images/image9.png
./source/docs/software/basic-programming/images/image5.png
./source/docs/software/basic-programming/images/image4.png
./source/docs/software/basic-programming/images/image3.png
./source/docs/software/basic-programming/images/image8.png
./source/docs/software/basic-programming/images/image2.png
./source/docs/software/basic-programming/images/image7.png
./source/docs/software/roborio-info/images/recovering-a-roborio-using-safe-mode-1.png
./source/docs/software/wpilib-tools/path-planning/pathfinder/images/pathweaver-4.png
./source/docs/software/wpilib-tools/path-planning/pathfinder/images/pathweaver-5.png
./source/docs/software/wpilib-tools/path-planning/pathfinder/images/pathweaver-6.png
./source/docs/software/wpilib-tools/path-planning/pathfinder/images/pathweaver-2.png
./source/docs/software/wpilib-tools/path-planning/pathfinder/images/pathweaver-9.png
./source/docs/software/wpilib-tools/path-planning/pathfinder/images/pathweaver-8.png
./source/docs/software/wpilib-tools/path-planning/pathfinder/images/pathweaver-3.png
./source/docs/software/wpilib-tools/path-planning/pathfinder/images/pathweaver-1.png
./source/docs/software/wpilib-tools/path-planning/pathfinder/images/pathweaver-7.png
./source/docs/software/wpilib-tools/smartdashboard/images/expressions-1.png
./source/docs/software/wpilib-tools/smartdashboard/images/display-properties-1.png
./source/docs/software/wpilib-tools/smartdashboard/images/display-properties-3.png
./source/docs/software/wpilib-tools/smartdashboard/images/smartdashboard-intro-2.png
./source/docs/software/wpilib-tools/smartdashboard/images/smartdashboard-intro-3.png
./source/docs/software/wpilib-tools/smartdashboard/images/smartdashboard-intro-4.png
./source/docs/software/wpilib-tools/smartdashboard/images/smartdashboard-intro-5.png
./source/docs/software/wpilib-tools/smartdashboard/images/display-properties-2.png
./source/docs/software/wpilib-tools/smartdashboard/images/display-properties-4.png
./source/docs/software/wpilib-tools/smartdashboard/images/smartdashboard-intro-1.png
./source/docs/software/wpilib-tools/smartdashboard/images/display-properties-5.png
./source/docs/software/wpilib-tools/shuffleboard/layouts-with-code/images/organizing-widgets-1.png
./source/docs/software/wpilib-tools/shuffleboard/layouts-with-code/images/widgets-2.png
./source/docs/software/wpilib-tools/shuffleboard/layouts-with-code/images/widgets-1.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/list-2.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/widgets-4.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/preferences-1.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/recording-4.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/list-4.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/preferences-3.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/data-sources-2.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/preferences-4.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/tabs-2.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/recording-2.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/list-5.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/preferences-2.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/graphs-3.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/camera-stream-2.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/graphs-2.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/recording-5.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/widgets-3.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/list-1.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/graphs-4.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/graphs-5.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/graphs-1.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/recording-3.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/tabs-1.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/recording-1.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/camera-stream-1.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/widgets-2.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/list-3.png
./source/docs/software/wpilib-tools/shuffleboard/getting-started/images/widgets-1.png
./source/docs/software/wpilib-tools/shuffleboard/advanced-usage/images/commands-subsystems-3.png
./source/docs/software/wpilib-tools/shuffleboard/advanced-usage/images/tuning-pid-1.png
./source/docs/software/wpilib-tools/shuffleboard/advanced-usage/images/hierarchies-2.png
./source/docs/software/wpilib-tools/shuffleboard/advanced-usage/images/commands-subsystems-2.png
./source/docs/software/wpilib-tools/shuffleboard/advanced-usage/images/hierarchies-1.png
./source/docs/software/wpilib-tools/shuffleboard/advanced-usage/images/commands-subsystems-1.png
./source/docs/software/wpilib-tools/robotbuilder/writing-code/images/writing-subsystem-code-1.png
./source/docs/software/wpilib-tools/robotbuilder/writing-code/images/generating-code-2.png
./source/docs/software/wpilib-tools/robotbuilder/writing-code/images/generating-code-1.png
./source/docs/software/wpilib-tools/robotbuilder/writing-code/images/pid-subsystem-1.png
./source/docs/software/wpilib-tools/robotbuilder/writing-code/images/writing-command-code-1.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-created-code-3.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/creating-subsystem-1.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/creating-commands-1.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-created-code-5.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/starting-robotbuilder-2.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/creating-subsystem-8.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-interface-5.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/operator-interface-command-1.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-overview-8.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/testing-with-smartdashboard-1.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/driving-with-mecanum-1.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-overview-7.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-overview-4.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/creating-subsystem-2.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-overview-3.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/creating-subsystem-9.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/operator-interface-command-3.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-created-code-4.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-overview-2.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-interface-1.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/creating-subsystem-6.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-overview-6.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-overview-5.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/creating-subsystem-7.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-interface-2.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-overview-1.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/creating-commands-2.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/default-autonomous-command-1.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-setup-1.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/creating-subsystem-5.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/creating-commands-3.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/creating-subsystem-3.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-created-code-2.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-interface-4.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/operator-interface-command-2.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/testing-with-smartdashboard-2.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/creating-commands-4.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/starting-robotbuilder-1.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-interface-3.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/robotbuilder-created-code-1.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/creating-commands-5.png
./source/docs/software/wpilib-tools/robotbuilder/introduction/images/creating-subsystem-4.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/driving-with-joysticks-1.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/custom-components-1.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/custom-components-3.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/driving-with-joysticks-3.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/custom-components-8.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/driving-with-mecanum-1.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/setpoint-command-3.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/custom-components-6.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/pidsubsystem-actuators-3.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/command-run-commands-2.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/driving-with-joysticks-4.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/custom-components-2.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/driving-with-joysticks-2.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/command-run-commands-5.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/custom-components-5.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/command-run-commands-4.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/setpoint-command-1.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/command-run-commands-3.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/custom-components-4.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/pidsubsystem-actuators-2.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/pidsubsystem-actuators-1.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/command-run-commands-1.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/custom-components-9.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/setpoint-command-2.png
./source/docs/software/wpilib-tools/robotbuilder/advanced/images/custom-components-7.png
./source/docs/contributing/images/build-instructions-1.png
./source/docs/contributing/images/build-instructions-2.png
./source/docs/contributing/images/build-instructions-3.png
./source/docs/getting-started/getting-started-frc-control-system/images/linux/java-11.png
./source/docs/getting-started/getting-started-frc-control-system/images/update-suite/ni-activation-wizard-3.png
./source/docs/getting-started/getting-started-frc-control-system/images/update-suite/ni-activation-wizard-4.png
./source/docs/getting-started/getting-started-frc-control-system/images/update-suite/ni-activation-wizard-2.png
./source/docs/getting-started/getting-started-frc-control-system/images/labview/labview_license_2.png
./source/docs/getting-started/getting-started-frc-control-system/images/labview/labview_license_1.png
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image19.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image0.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image6.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image16.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image5.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image7.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image20.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image12.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image17.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image15.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image21.png
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image13.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image22.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image14.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image2.png
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image4.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image3.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image18.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image1.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image11.jpg
./source/docs/getting-started/getting-started-frc-control-system/images/how-to-wire-a-robot/image8.jpg


</details>

**Comment by JonathanLindsey** [comment]
The [Style Guide - Image Files](https://docs.wpilib.org/en/latest/docs/contributing/frc-docs/style-guide.html#image-files) section specifies the desired file names as:
>They should follow the naming scheme of `document-title-1.png` so on and so forth.

If more descriptive names are desired, this section should be updated. There are several other places in the Style Guide that use image file names that would need to be updated as well.

**Comment by Daltz333** [comment]
Yeah, the style guide should get updated. The my-title-1 scheme is from when porting screensteps, it became very time consuming adding descriptive image titles. Especially as downloading the images from screensteps often gave the image name as a garbage mess.
