### ISSUE TITLE
 Tutorial:Identify section of Java Code that execute the Daisy Chain Byte/Data  Flow : I.E  Header ,Status, Addresses,Data

### ISSUE THREAD

**Issue by aedford** [wpilibsuite/frc-docs#2254]
Trying to look under the hood  and relate how the data flows inside  the  Daisy Chain wiring - Max Spark Contollers,  Rio , PDP circuit ( Green, Yellow wires )  What in the code segments initiates  the flow of data  and  how I can inter relate the code statements , variables ,values, functions to the  Header, Status, Address, Data ,Bytes  ( provide an example )
Using the 2023 Rev Ion Starter Bot for Hardware , Java Code for software ( for West Coast Drive Train ,, Manipulator ,Grippers- Neo bushless motors ). We like to walk thru the entire sequence , code ,transmission, hardware
Reference articles   Daisy Chain Implementation for Serial Peripheral interface ( for bushed motors ) by Texas Instruments 
Would like to be able to illustrate that interface  ( low level for them , higher level for me  ) to the FRG team #4398
if not a tutorial - can  some educate  me  ( Allan Edford , mentor ) - Team 4398   Thanks

**Comment by jasondaming** [comment]
Do you mean the [CAN](https://en.wikipedia.org/wiki/CAN_bus) wiring?

The [article](https://www.ti.com/lit/an/slvae25a/slvae25a.pdf?ts=1683000004834) you mentioned seems to be talking about things via SPI and none of this is controlled with SPI (there is an SPI port on the RIO but it is usually only used for sensors and has issues at that).

**Comment by daltzctr** [comment]
We don't really go into low level into the docs, nor do we want to recommend teams to. Can your clarify your issue?

**Comment by aedford** [comment]
Yes

**Comment by aedford** [comment]
I'M  a retired engineer and this is mainly for my benefit  I like to take
things apart
Walking thru the Java code we are using on the frc team 4398 robot that got
my interest also  was exposed to SPI  thru robot on line workshops  and
projects at an Engineering Academy  where I 'm on  the Guidance board
Traverse City Mi
Most of this stuff I studied including AI  after retirement
I has become a hobby

**Comment by aedford** [comment]
Oh !
I would still be interest in the details of the communication platform to
get a feel and an understanding of it
I,'m amazed at the sophistication  that must have gone into the code
development in order for the K 12 kids to use it's top level

**Comment by aedford** [comment]
Have found Texas Instruments and other tutorials on CAN that have broaden my understanding of the network 
Also tutorials on Daisy Chains
Have sufficient info to feel more comfortable 
Thanks

Allan S . Edford

**Comment by aedford** [comment]
Have found Texas Instruments and other Tutorials on CAN 
Also tutorials on Daisy Chains
Have sufficient info now to feel more comfortable
Thanks 

Allan S . Edford
