### ISSUE TITLE
Duplicated Content and Images

### ISSUE THREAD

**Issue by Modelmat** [wpilibsuite/frc-docs#227]
The below pages contain duplicate images and content. There may be other pages that contain duplicate content.

- [Adding Widgets to SmartDashboard](http://docs.wpilib.org/en/latest/docs/software/wpilib-tools/smartdashboard/smartdashboard-intro.html#adding-widgets-to-the-smartdashboard) contains the same image as at the top of the page, [Introduction](http://docs.wpilib.org/en/latest/docs/software/wpilib-tools/smartdashboard/smartdashboard-intro.html#smartdashboard-introduction)
   + The images are [smartdashboard-intro-1](https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/software/wpilib-tools/smartdashboard/images/smartdashboard-intro-1.png) and [smartdashboard-intro-6](https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/software/wpilib-tools/smartdashboard/images/smartdashboard-intro-6.png)
- [Victor SP](https://docs.wpilib.org/en/latest/docs/getting-started/getting-started-frc-control-system/control-system-hardware.html#victor-sp) and [Victor SPX](https://docs.wpilib.org/en/latest/docs/getting-started/getting-started-frc-control-system/control-system-hardware.html#victor-spx)
  + [victor-sp-motor-controller.png](https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/getting-started/getting-started-frc-control-system/images/control-system-hardware/victor-sp-motor-controller.png) and [victor-spx-motor-controller.png](https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/getting-started/getting-started-frc-control-system/images/control-system-hardware/victor-spx-motor-controller.png)
- [Camera Webpage](https://docs.wpilib.org/en/latest/docs/software/vision-processing/introduction/configuring-an-axis-camera.html#camera-webpage) and [Manual Camera Configuration](https://docs.wpilib.org/en/latest/docs/software/vision-processing/introduction/configuring-an-axis-camera.html#manual-camera-configuration)
  + [camera-webpage.png](https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/software/vision-processing/introduction/images/configuring-an-axis-camera/camera-webpage.png) and [manual-camera-configuration.png](https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/software/vision-processing/introduction/images/configuring-an-axis-camera/manual-camera-configuration.png)
- [Control Panel](http://docs.wpilib.org/en/latest/docs/networking/networking-introduction/windows-firewall-configuration.html#control-panel) and [Open Control Panel](http://docs.wpilib.org/en/latest/docs/networking/networking-introduction/windows-firewall-configuration.html#open-control-panel)
   + [windows-firewall-configuration-1.png](https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/networking/networking-introduction/images/windows-firewall-configuration-1.png) and [windows-firewall-configuration-4.png](https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/networking/networking-introduction/images/windows-firewall-configuration-4.png)

**Comment by RishabRao** [comment]
The other issues linked are not problems

**Comment by Daltz333** [comment]
I think the idea is that they use two separate files, when they only need to use one.

**Comment by sciencewhiz** [comment]
According to md5sums, the following are duplicates

docs/software/old-commandbased/commands/images/scheduling-commands/image1.png and docs/software/old-commandbased/commands/images/synchronizing-two-commands/image3.png

docs/software/wpilib-overview/images/creating-robot-program/cpp-configurations.png and docs/software/wpilib-overview/images/importing-eclipse-project/cpp-configurations.png


docs/getting-started/running-a-benchtop/images/creating-benchtop-test-labview/labview-create-project.png and docs/software/labview/creating-robot-programs/images/creating-building-and-loading-your-benchtop-test-program/configuring-project.png

docs/getting-started/running-a-benchtop/images/creating-benchtop-test-labview/labview-home.png and docs/software/labview/creating-robot-programs/images/creating-building-and-loading-your-benchtop-test-program/creating-a-project.png


docs/getting-started/getting-started-frc-control-system/images/labview/ni_activation_login.png and docs/getting-started/getting-started-frc-control-system/images/update-suite/ni-activation-wizard.png

docs/hardware/sensors/images/encoders-hardware/encoding-direction.png and docs/software/sensors/images/encoders-software/encoding-direction.png


docs/getting-started/running-a-benchtop/images/creating-benchtop-test-labview/labview-benchtop-deploy-startup.png and docs/software/labview/creating-robot-programs/images/creating-building-and-loading-your-benchtop-test-program/deploying-the-program.png


docs/software/labview/creating-robot-programs/images/command-and-control-tutorial/ni-logo.png and docs/software/labview/creating-robot-programs/images/creating-building-and-loading-your-benchtop-test-program/ni-logo.png and docs/software/labview/resources/images/ni-logo.png and docs/getting-started/getting-started-frc-control-system/images/labview/ni_logo.png

**Comment by Daltz333** [comment]
In terms of duplicated images, I think referencing images out of directory would be very confusing.
