### ISSUE TITLE
Fork the doc8 extension

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#228]
Probably should fork the unmaintained non-updated extension to fix a couple of bugs, and do some style-guide specific linting. Will get to it eventually.

**Comment by TheTripleV** [comment]
I don't think doc8 has to be forked. doc8 searches and runs checks via plugin extensions that we can write. They just have to be discoverable by stevedore (https://pypi.org/project/stevedore/)

**Comment by Daltz333** [comment]
Looking at the plugin extension framework, it seems very non-trivial. Going to mark this issue as help wanted, as I don't think I'll have the time to work on this.

**Comment by TheTripleV** [comment]
I got a basic demo working. It's not that bad, just undocumented. To use custom formatters, we need to put them in a separate python package, so probably a new repo.

**Comment by Daltz333** [comment]
Could you link me your example?

**Comment by TheTripleV** [comment]
https://github.com/TheTripleV/doc8extension

If you install it, then doc8 should automatically pick it up the next time it runs.
