### ISSUE TITLE
Document how to set JVM args in user projects

### ISSUE THREAD

**Issue by rzblue** [wpilibsuite/frc-docs#2317]
```
frcJava(getArtifactTypeClass('FRCJavaArtifact')) {
  jvmArgs << 'argOne' << 'argTwo'
}
```

**Comment by sciencewhiz** [comment]
This seems more appropriate for gradlerio documentation then in frc-docs, since it's not something we'd normally expect users to do. It is there already for setting GC settings.

**Comment by Daltz333** [comment]
I actually wouldn't mind this for advanced gradlerio usage. It's fairly common to touch up the args a bit if you want remote debugging.
