### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by aizeeland** [wpilibsuite/frc-docs#2334]
I found a build error after I am using the WPILib to create a project on an Ubuntu 22.04 system. I manage to install the WPILib package version for Linux-2024.0.0--alpha-1 by following the installation guide. After VSCode opens I follow the steps on the page "Creating your Test Drivetrain Program" as described in the documents (ttps://docs.wpilib.org/en/stable/docs/zero-to-robot/step-4/creating-test-drivetrain-program-cpp-java.html). After I created a new project by using the creator window I get the following build error: 

![image](https://github.com/wpilibsuite/frc-docs/assets/77146959/5fde6919-fec6-45dc-a8e5-c3c8f182a581)

Could anybody help me solve this error.

**Comment by sciencewhiz** [comment]
Why are you using the alpha version? The release page says the following, so you should probably be installing the 2023 release not the 2024 alpha. And if you want to get a head start on 2024, watch the frc blog for the 2024 beta announcement and sign up.
> This is an early preview release of WPILib for the 2024 season. This release is not intended for competition or full-size robot use. The purpose of this release is to provide an easy-to-use installation of WPILib for users of the [XRP robot](https://experientialrobotics.org/).

With that said, you don't actually show the error. You need to scroll up in the terminal window to see the true error. Please copy and paste the full error, not just a screenshot.

**Comment by aizeeland** [comment]
Thanks for the comment. I did not see the error was shown above. I solved it, a package was missing.

**Comment by aizeeland** [comment]
Build error solved after installing missing package.

**Comment by aizeeland** [comment]
The error message indicated that I was missing the RoboRio Toolchain so the problem was fixed after running the command "./gradlew installRoboRioToolchain".
