### ISSUE TITLE
Document how to add compiler flags to GradleRIO C++

### ISSUE THREAD

**Issue by spacey-sooty** [wpilibsuite/frc-docs#2392]
In a C++ GradleRIO project we can do something like this in our build.gradle
```groovy
binaries.all {
  cppCompiler.args "-Werror"
}
```

This is not documented well at all. 
It should probably be documented under the Advanced GradleRIO section.

**Comment by ThadHouse** [comment]
We can document it, but thats not the correct way we'd want to document. That would break simulation.

```
nativeUtils.platformConfigs.named('windowsx86-64').configure {
    it.cppCompiler.args.add("/utf-8")
}
```

Instead the right way is to add flags per platform. And to document what the platforms are.
