### ISSUE TITLE
Update Test Drivetrain Program for Phoenix 6 instead of Phoenix 5

### ISSUE THREAD

**Issue by daltzctr** [wpilibsuite/frc-docs#2400]
The TalonFX class is deprecated for removal in v5. Users should use TalonFX in v6 instead.

**Comment by sciencewhiz** [comment]
Is this an upcoming change? It doesn't appear to be deprecated in the current beta release.

**Comment by daltzctr** [comment]
It will be formally deprecated in one of the upcoming beta releases.

**Comment by sciencewhiz** [comment]
Since there's still supported products that can only use Phoenix 5, I think the example should be changed to use TalonSRX with Phoenix 5 and another example added that uses TalonFX with Phoenix 6.

**Comment by mjbergman92** [comment]
Does this refer to this documentation page?

https://github.com/wpilibsuite/frc-docs/blob/main/source/docs/zero-to-robot/step-4/creating-test-drivetrain-program-cpp-java-python.rst 

I know how to use the Phoenix 6 libraries. I just need a bit more collaborative direction before I try to make some changes and submit a pull request.
