### ISSUE TITLE
Version warning isn't shown on latest

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#2402]
latest should show the following version warning, but no warning is shown: https://github.com/wpilibsuite/frc-docs/blob/cc1166fb8f4f8fbec76a562c4329b95085120777/source/conf.py#L70-L78

**Comment by rzblue** [comment]
Additionally, 2022 doesn't show a warning, and 2020 and 2021 point to 2022 as the latest version

**Comment by sciencewhiz** [comment]
I think those have been issues for a while, where as latest worked up until the upgrade to Sphinx 7.

**Comment by sciencewhiz** [comment]
There's the following warnings in the js console

```
latest/_static/js/?v=ace65d95../../_static/data/versionwarning-data.json:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
versionwarning.js?v=ace65d95:1  Error loading versionwarning-data.json Error: Network response was not ok
    at versionwarning.js?v=ace65d95:1:2359
```
```
versionwarning.js?v=ace65d95:1  Error loading versionwarning-data.json Error: Network response was not ok
    at versionwarning.js?v=ace65d95:1:2359
```

**Comment by sciencewhiz** [comment]
Looks like the checksum added by https://github.com/sphinx-doc/sphinx/pull/11415 is what broke it and the version warning extension will need an update @GrahamSH-LLK

**Comment by GrahamSH-LLK** [comment]
I have a working version on pypi (v1.1.6) but I won't be able to PR until later today. If somebody wants to pr bumping modern-sphinx-version-warning, that's all that's required.

**Comment by sciencewhiz** [comment]
#2427 didn't update requirements
