### ISSUE TITLE
Difficult to firmware reset XRP Robot 

### ISSUE THREAD

**Issue by REVSIX** [wpilibsuite/frc-docs#2415]
There is currently no documentation or instruction on how to reset the firmware on an XRP Robot. As labeled in my previous issue regarding wifi, the only way to change the password is through the online UI, and since we are unable to connect to the WiFi, we are unable to use our robot wirelessly.

**Comment by zhiquanyeo** [comment]
I'll update the docs shortly, but the solution here is to download the special UF2 Nuke firmware (e.g. from https://learn.adafruit.com/getting-started-with-raspberry-pi-pico-circuitpython/circuitpython#flash-resetting-uf2-3083182), installing that on the Pico (same way you would install the firmware). This will wipe the flash memory completely. Then you can re-install the WPILib firmware.
