### ISSUE TITLE
More actively discourage users from using Shuffleboard and SmartDashboard

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#2419]
With the amount of good dashboard options these days it really doesn't make sense to present these as viable options.  Unless you insist on code based generation and are okay dealing with all of shuffleboards problems, I really can't make a logical case for either of them.

I think there should be more information [here](https://docs.wpilib.org/en/stable/docs/software/dashboards/index.html) and on the first page for both [Shuffleboard](https://docs.wpilib.org/en/stable/docs/software/dashboards/shuffleboard/index.html) and [SmartDashboard](https://docs.wpilib.org/en/stable/docs/software/dashboards/smartdashboard/index.html)

We should also link to the AS section here
https://github.com/wpilibsuite/frc-docs/pull/2418

**Comment by calcmogul** [comment]
Same goes for PathWeaver vs PathPlanner. Going a step further, I guess the main requirement for dropping Shuffleboard, SmartDashboard, and PathWeaver entirely is having stable, long-lived alternatives.

**Comment by Kevin-OConnor** [comment]
AdvantageScope is not intended to be a dashboard replacement. None of these other projects have been around longer than a year or so. Until there is something appropriate to refer people to, dissuading them from working, if flawed, tools that we are still packaging seems inappropriate.

**Comment by calcmogul** [comment]
That's the thing though. Shuffleboard doesn't work a lot of the time. It's laggy and slow, eats a lot of RAM, and has unusable plots.

**Comment by jasondaming** [comment]
> AdvantageScope is not intended to be a dashboard replacement.

In my experience even though AdvantageScope isn't targeted as a in match dashboard it still works better than Shuffleboard in that respect.  I agree it doesn't cover all that shuffleboard does, but do most users need custom plugins (completely unused) or many of the other features that aren't present.

I am not saying that we shut shuffleboard down only that we truly open the users eyes to all of the possibilities.  There are constantly teams I meet that come and complain about shuffleboard (both in person and on places like discord) knowing nothing about any of the alternatives (and how shuffleboard is not being actively fixed).  I like to think (and many teams do to) that when they see a program from WPILib they instantly assume it is the best available.  In order for us to keep that reputation and respect it is critical that we are upfront about both our and 3rd party applications capabilities and if there is really any reason they should consider and alternative to WPILib we should help them make that informed choice.

**Comment by jasondaming** [comment]
I agree completely.  I also wouldn't recommend AS as a driver dashboard.  I think it functions really well in a lot of other dashboard ways like glass.  We put glass on the "dashboards" page and don't recommend it as a "driver dashboard".

Our team had great success with FRC-web-components.  I understand Kevin's trepidation about solutions that haven't been around long and I worry about that too.  I think I should put a PR together for this and hopefully the language I use would be fair and put everyone's fears in this thread to rest, but at least that will give us something concrete to talk about.
