### ISSUE TITLE
Split On-Robot Telemetry Recording Into Data Logs into Recording and Downloading

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#2422]
[This page](https://docs.wpilib.org/en/stable/docs/software/telemetry/datalog.html) talks about both writing to datalog files and downloading those datalog files to your computer.  Both are large important topics and should have their own pages.

**Comment by PeterJohnson** [comment]
This is particularly needed as the DS will also have a way to download logs (as does AdvantageScope).

**Comment by jasondaming** [comment]
Fixed by #2418
