### ISSUE TITLE
'XRP Template' Not found

### ISSUE THREAD

**Issue by PapaMarsh** [wpilibsuite/frc-docs#2426]
When starting a new WPILib project in VS Code, 'XRP Template' does not show up in the list of examples as the [Programming the XRP](https://docs.wpilib.org/en/latest/docs/xrp-robot/programming-xrp.html) page on the WPILib wiki says it should.

**Comment by sciencewhiz** [comment]
What version of WPILib did you install? XRP requires the 2024 beta

**Comment by PapaMarsh** [comment]
That appears to be the issue. The installer I downloaded from the website says it's for 2023. Downloading the 2024 one now, hopefully that fixes it, thank you!
