### ISSUE TITLE
Add to styleguide

### ISSUE THREAD

**Issue by Kevin-OConnor** [wpilibsuite/frc-docs#243]
Styleguide should be updated to be specific about how to format role directives such as "note" and "warning" as our formatting does not match Sphinx examples.

Should also specify desired indent (or in this case not) for lists.

**Comment by Daltz333** [comment]
Non-indent for lists is default in Sphinx examples, is it necessary to include?

**Comment by Kevin-OConnor** [comment]
I mean, the fact that I just did it wrong seems to suggest that it should be
