### ISSUE TITLE
Document all pieces of the universal heartbeat

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/frc-docs#2440]
https://docs.wpilib.org/en/stable/docs/software/can-devices/can-addressing.html#universal-heartbeat is incomplete--it only documents byte 5 of the 8-byte frame.

**Comment by jasondaming** [comment]
Where is the rest of the information located?  Is it information important enough / pertinent enough to document in frc-docs?

**Comment by Gold856** [comment]
The entire heartbeat was documented in #2270.
