### ISSUE TITLE
Streamline Appearance of Code in Downloaded PDF

### ISSUE THREAD

**Issue by tom131313** [wpilibsuite/frc-docs#2445]
The HTML version of the docs uses tabs for the different languages (currently Java and C++ including Header and Source) so only the language of interest to readers is visible.

The PDF download expands all programming language tabs inline and significantly clutters the view. This will be more acute with the addition of Python.

To make the document more inviting to read I suggest an option to select which programming language to download in the PDF.

**Comment by sciencewhiz** [comment]
I think this would be very invasive, if its possible at all. The tabs are from the sphinx-design extension, so there's likely need to be changes there. I think it would also have to hook into the sphinx latex builder. It would also need readthedocs support to have multiple pdf options. Then comes the question of how to decide what tabs go into which PDF. For example, sometimes a tab title is C++ and other times it's C++ (Header) and C++ (Source), and probably other variations. Also need to consider other times tabs are used. Different PDFs for Windows/Mac/Linux? Rev / CTRE?

**Comment by tom131313** [comment]
@sciencewhiz ideas for even more customization of the download are great. Too bad they think it isn't practical with the current builder so I'll close the issue.

**Comment by PeterJohnson** [comment]
It would be hacky, but one possible way would be a script that goes through and removes the non-relevant tabs from the source files, then runs the PDF build.  Do this 3 times (once for each language).  We'd also have to host the PDF somewhere else due to lack of RTD support.  We've talked from time to time about removing the PDF build entirely as it's unclear who actually uses it and why.  @tom131313 why are you using the PDF version instead of the HTML version?

**Comment by tom131313** [comment]
@PeterJohnson It's easy to manage a single PDF file - trivial to update versions or copy to another folder. I like seeing the whole context of an article within the complete document. Easy to search. Many hundreds fewer files that clog my other file searches. A bunch of little things make PDF feel better. I can live without PDF and will work with the HTML. I don't disagree with removing PDF  support if it consumes precious WPILib resources better spent elsewhere.
