### ISSUE TITLE
Use JS to detect if Cloudflare's .dev domain is blocked and swap out the download link to Artifactory

### ISSUE THREAD

**Issue by TheTripleV** [wpilibsuite/frc-docs#2503]
(Or just add a link to https://wpilib.jfrog.io/ui/native/installer/ and call it a day)

edit: the wpi.edu url is probably better here

**Comment by TheTripleV** [comment]
re https://frccsa.slack.com/archives/C995S4W2C/p1704649935271629?thread_ts=1704581136.292359&channel=C995S4W2C&message_ts=1704649935.271629

**Comment by TheTripleV** [comment]
Another report:

https://www.chiefdelphi.com/t/wpilib-blog-2024-kickoff-release-of-wpilib/448056/17?u=vasista

**Comment by sciencewhiz** [comment]
https://www.chiefdelphi.com/t/fortinet-prevents-download-wpilib-software/455224

**Comment by Gold856** [comment]
This can be closed
