### ISSUE TITLE
Coordinate System field image confusing

### ISSUE THREAD

**Issue by agasser** [wpilibsuite/frc-docs#2516]
The image on the [Coordinate Systems](https://docs.wpilib.org/en/stable/docs/software/advanced-controls/geometry/coordinate-systems.html) page show the red alliance on the left and the blue alliance on the right. These are backwards from the way field images are presented in Shuffleboard and other common tools (PathPlanner, AdvantageScope etc.)
![image](https://github.com/wpilibsuite/frc-docs/assets/1993518/54da6e34-95fb-4b42-a3db-423d3aca43d4)

It has been four years since the 2020 game, so it took me a long time to figure out if the origins were wrong, or if the image was rotated. It might be helpful for this figure to also highlight which alliance driver stations are on each side. Most of the kids in FRC today were not around for the 2020 game.

As an aside, I'm contemplating creating an update page with practical guidance on the coordinate system for teams. I've worked with three teams this season alone who had rotation backwards, and X and Y on the wrong axes.

**Comment by sciencewhiz** [comment]
I'll update the image, but I think many people would benefit from your experience and tips, because I think lots of people have had trouble.
