### ISSUE TITLE
Robot disabling when enabled due to loss of coms

### ISSUE THREAD

**Issue by ConnorJNorris** [wpilibsuite/frc-docs#2528]
The driver station is disabling anywhere from about 10 second-2 minuets. The driver station flashes that it lost communication with the robot for a fraction of a second, but this is enough to disable it. When this happens, the message "Internal issue with print and error tags'' shows up repeatedly on the driver station. Other have had this same issue see https://github.com/wpilibsuite/allwpilib/issues/6174

**Comment by PeterJohnson** [comment]
Please post your DS log file from when this happens.  The DS timeouts have been tightened up this year and it sounds like you’re tripping one of them.

**Comment by jasondaming** [comment]
Is there something to document?  Do we want to move this issue?

**Comment by ConnorJNorris** [comment]
I will post the log file here tomorrow afternoon.

**Comment by Starlight220** [comment]
Add a `.log` at the end of the name (after the `.dslog` part)

**Comment by ConnorJNorris** [comment]
Thanks

[2024_01_16 17_14_02 Tue.dslog.log](https://github.com/wpilibsuite/frc-docs/files/13959917/2024_01_16.17_14_02.Tue.dslog.log)

**Comment by jasondaming** [comment]
There is also a .dsevents file that goes with it that is very handy if we can have that too?  Were the problem(s) at the very beginning of this log or can you briefly describe what you experienced?

**Comment by ConnorJNorris** [comment]
[2024_01_16 17_14_02 Tue.dsevents.log](https://github.com/wpilibsuite/frc-docs/files/13966016/2024_01_16.17_14_02.Tue.dsevents.log)
Here is the dsevents file. Whenever the message "Internal issue with print and error tags'' shows up in the dsevents, the robot showed loss of coms very briefly, then disabled. Generally, this occurs a lot at start up,  and then periodically while the robot is running. I can send a smaller dslog and dsevents file if it would be more helpful, but I'll have to do it when I go into our build space this afternoon. Thank you for working with me.

**Comment by sciencewhiz** [comment]
See the update posted here: https://github.com/wpilibsuite/allwpilib/issues/6174#issuecomment-1900519490

Closing this so the discussion stays in one place
