### ISSUE TITLE
Inaccurate NT example Python

### ISSUE THREAD

**Issue by Suave101** [wpilibsuite/frc-docs#2534]
On the following page, the Python example is not accurate:
https://docs.wpilib.org/en/stable/docs/software/networktables/tables-and-topics.html
There is no such thing as a `new DoubleTopic()` in python. Only a `ntcore.DoubleTopic()`
Here is a picture of the page:
![image](https://github.com/wpilibsuite/frc-docs/assets/57422635/5987da8f-2dc4-4c13-b542-de3f30dc3a18)

**Comment by jasondaming** [comment]
I see a [DoubleTopic here](https://robotpy.readthedocs.io/projects/robotpy/en/stable/ntcore/DoubleTopic.html)

You are absolutely right that `new` shouldn't be there.  It should be: `ntcore.DoubleTopic(topic)` That was a copy over from Java.

Let me know if you have any issues with my PR linked above.
