### ISSUE TITLE
Coordinate System has incorrect images

### ISSUE THREAD

**Issue by WispySparks** [wpilibsuite/frc-docs#2558]
![image](https://github.com/wpilibsuite/frc-docs/assets/101812473/7516a2e2-412a-4b11-8253-5c4931b6b415)
Under Field Coordinate System there are two images describing the axis that contradict each other. It appears the top image is correct which defines the X-axis as pointing away from the alliance wall but the bottom image shows the X-axis as the vertical axis.

**Comment by sciencewhiz** [comment]
Please take a look at #2537 and see if it helps

**Comment by WispySparks** [comment]
https://github.com/wpilibsuite/frc-docs/pull/2537 solves this issue
