### ISSUE TITLE
Add ImgBot?

### ISSUE THREAD

**Issue by yellowjaguar5** [wpilibsuite/frc-docs#256]
I noticed that there's a neat Github app called [ImgBot](https://github.com/marketplace/imgbot) that does automatic image compression. This could help reduce the overall size of the repo and (I'm not sure, but maybe) speed up page loading times and CI builds. Just curious if people think it would be helpful.

**Comment by Daltz333** [comment]
This will conflict with #129. And the the thing that takes time in CI is installing deps and latex.
