### ISSUE TITLE
Incorrect coordinate system shown on 2024 Field diagram

### ISSUE THREAD

**Issue by jamesra** [wpilibsuite/frc-docs#2561]
The pictures and text description of the coordinate system are inconsistent with the graphics for the 2024 field: https://docs.wpilib.org/en/stable/docs/software/advanced-controls/geometry/coordinate-systems.html  X should be increasing away from the team's wall.  (Compare coordinate system in B&W image vs 2024 field color photo)

**Comment by sciencewhiz** [comment]
Fixed by #2537
