### ISSUE TITLE
Driver Station Docs Showing Raw RST Instead of Rendering

### ISSUE THREAD

**Issue by mfisher31** [wpilibsuite/frc-docs#2567]
See: https://raw.githubusercontent.com/wpilibsuite/frc-docs/main/source/docs/software/driverstation/driver-station.rst

**Comment by mfisher31** [comment]
Thinking about that again, this might be a bunk issue.  I didn't check if GitHub is supposed to render it or not..

**Comment by PeterJohnson** [comment]
GitHub renders it when you go through the normal browsing.  The raw URL gives you the raw content with no rendering.  E.g. https://github.com/wpilibsuite/frc-docs/blob/main/source/docs/software/driverstation/driver-station.rst

**Comment by mfisher31** [comment]
Oh I pasted the raw version.  Meant to paste the link you provided.  Got it!  Sorry for the confusion.
