### ISSUE TITLE
Zero-to-robot arcade drive example should use four motors and following

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/frc-docs#2587]
The kitbot has more than two motors, so following is required to get full performance. The example just needs some extra motor declarations and some `leader.addFollower(follower)` calls in robotInit().

See https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-4/creating-test-drivetrain-program-cpp-java-python.html.

**Comment by sciencewhiz** [comment]
It's based on the wiring instructions in step 1 which uses a PWM Y cable

**Comment by calcmogul** [comment]
A team I just dealt with on the discord apparently didn't do that, and had them all wired to individual ports.

**Comment by sciencewhiz** [comment]
I assume they didn't find this? https://docs.wpilib.org/en/stable/docs/software/hardware-apis/motors/wpi-drive-classes.html#multi-motor-differentialdrive

**Comment by jasondaming** [comment]
I think we can close this as not planned?  I struggle to see why we should support the use case not specifically following the instructions in this specific document.  Maybe there is a different issue and another place to address this but I don't see this as a common stumbling block.
