### ISSUE TITLE
WPILib.org completely obscures how to download WPILib

### ISSUE THREAD

**Issue by Billfred** [wpilibsuite/frc-docs#2610]
Not strictly an frc-docs issue but this seems the most logical spot to raise the issue.

The Squarespace-based WPILib.org website does not make it obvious where to download WPILib.  The link to the installation guide is below the fold on a standard laptop screen and labeled "How to use WPILib" which sounds a lot like documentation rather than how to install it (at best, it's ambiguous).  

Both placement and label should be adjusted to make things more obvious to newcomers and people in a rush who haven't downloaded a full WPILib install in a while.

**Comment by arbessette** [comment]
Label was changed and the size of the upper image decreased. 
Does this help?

**Comment by Billfred** [comment]
It's still below the fold on my screen (I'm on a MacBook Air 13"), but the label change is a palpable improvement.

It seems to be nowhere in the top nav bar; if y'all don't want to give it its own heading, perhaps at least under Resources?

**Comment by arbessette** [comment]
Thank you for your feedback. I have added it to the top, as well as under resources.

**Comment by sciencewhiz** [comment]
Closing since the site was updated
