### ISSUE TITLE
Status Light Printable Version

### ISSUE THREAD

**Issue by BrandeisBroncBotz** [wpilibsuite/frc-docs#2633]
I created a one page (front and back) printable Status Light Cheat Sheet! 
[CSA Cheat Sheet (4).pdf](https://github.com/wpilibsuite/frc-docs/files/15046732/CSA.Cheat.Sheet.4.pdf)

**Comment by jasondaming** [comment]
Would you like attribution for making this document?  If so what would you like it to say?

We are also going to put you on the hook for updating this in the future! 😄

**Comment by BrandeisBroncBotz** [comment]
Ya sure, that would be great! (I'll be honest, I have no idea what an
attribution is... just make it say something like "Head Coach of 3481 Bronc
Botz" or something like that.

And yes please, I'll do my best to keep it up to date and keep pushing it
to y'all but if I fall behind just message me or email me, I'm pretty easy
to reach :)

Thanks,
Rylee Lippenholz
Bronc Botz Head Coach & Alumni
FRC 3481, FTC 4008/4602/6976
FIRST In Texas Volunteer
(210) 710 - 5642
***@***.***
<http://www.broncbotz.org>
