### ISSUE TITLE
Datalog page doesn't specify the recommended format for USB drives

### ISSUE THREAD

**Issue by spacey-sooty** [wpilibsuite/frc-docs#2671]
It should specify that FAT32 is recommended

**Comment by sciencewhiz** [comment]
It's already there

https://github.com/wpilibsuite/frc-docs/blob/8c0a1239d1ab9941f888f2e9e55872fa4fa355a0/source/docs/software/telemetry/datalog.rst?plain=1#L20

**Comment by spacey-sooty** [comment]
🤦‍♀️I'm blind lol
