### ISSUE TITLE
Allow Python 3.12

### ISSUE THREAD

**Issue by WispySparks** [wpilibsuite/frc-docs#2682]
Would it be possible for the build/project to allow for Python versions above 3.11? And if not what's stopping that?
Reasoning being if I can keep from installing multiple versions of Python.

**Comment by TheTripleV** [comment]
When 3.12 first came out, all the packages didn't support it yet and we never checked again. It's probably fine now.

Either way, I'd recommend using something like pyenv or poetry to manage python versions on a per project basis.
