### ISSUE TITLE
Redown: issues with links with and around parentheses

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#2695]
If a link has a parentheses at the end of a link, redown adds a parentheses in the output. code: https://github.com/wpilibsuite/frc-docs/blob/f1894de897747b24ec9d552dca07f6502c57f55e/source/docs/software/commandbased/commands.rst?plain=1#L14 output: https://docs.wpilib.org/en/latest/docs/software/commandbased/commands.html#initialization

If a there is a closing parentheses after the link, redown adds an extra space before the after link parentheses. code: https://github.com/wpilibsuite/frc-docs/blob/f1894de897747b24ec9d552dca07f6502c57f55e/source/docs/software/advanced-controls/system-identification/creating-routine.rst?plain=1#L56 output: https://docs.wpilib.org/en/latest/docs/software/advanced-controls/system-identification/creating-routine.html#mechanism-callbacks

**Comment by TheTripleV** [comment]
Found a better regex in a markdown parser https://github.com/markedjs/marked/blob/master/src/rules.ts#L231
```!?\[((?:\[(?:\\.|[^\[\]\\])*\]|\\.|`[^`]*`|[^\[\]\\`])*?)\]\(\s*(<(?:\\.|[^\n<>\\])+>|[^\s\x00-\x1f]*)(?:\s+("(?:\\"?|[^"\\])*"|'(?:\\'?|[^'\\])*'|\((?:\\\)?|[^)\\])*\)))?\s*\)```

Now I just have to understand it...

**Comment by TheTripleV** [comment]
> redown adds an extra space

I did fix this in the header pr. After fixing the linter (preprocessing rd to rst before sending to doc8), it picked up on that.

**Comment by sciencewhiz** [comment]
> `[Java](Commandhtml#initialize)()` gets parsed as a single link instead of link then parenthesis. Would adding in a carve out just for a single () before the end of a link be ok?

I'm not seeing anything with that syntax in the docs, and I'm struggling to think of when you'd want to do that where you couldn't put the () as part of the link text, so I think I'm ok.

**Comment by sciencewhiz** [comment]
https://github.com/wpilibsuite/frc-docs/blob/c995ef4e9ff39dfdbc93eb093c90f563ab5b5067/source/conf.py#L164 Can be deleted when this is fixed
