### ISSUE TITLE
Change 4 space indents to 3 spaces to fix formatting for Furo

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#2729]
Per the style guide, all indents should be 3 spaces, but there are many places where 4 spaces are used for indent. 4 spaces means blockqote in rst (https://restructuredtext.readthedocs.io/en/latest/rst_guide.html). The current theme doesn't style blockquotes that way, but furo does, so the places with 4 spaces aren't rendered as intended with furo, so this blocks #2626

I think this is more complicated then a simple find and replace, because we don't want to change spacing within code blocks. There's also places where there's ambiguities. Is 12 spaces 3 sets of 4 space indents or 4 sets of 3 space indents. You can only tell by looking at the context.

**Comment by jasondaming** [comment]
Can you give examples of on what pages you see this problem on the Furo PR?  I wasn't seeing them.

**Comment by sciencewhiz** [comment]
This is not the root cause of at least most of the block quotes in furo
