### ISSUE TITLE
Find a more reliable article about rvalue

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#2784]
thbecker.net goes down very regularly

C:\Users\chris\Documents\Robotics\frc-docs\source\docs/software/commandbased/binding-commands-to-triggers.rst:75: WARNING: broken link: http://thbecker.net/articles/rvalue_references/section_01.html (403 Client Error: Forbidden for url: http://thbecker.net/articles/rvalue_references/section_01.html)

**Comment by PeterJohnson** [comment]
Maybe https://learn.microsoft.com/en-us/cpp/cpp/rvalue-reference-declarator-amp-amp ?
