### ISSUE TITLE
Search Improvements

### ISSUE THREAD

**Issue by Modelmat** [wpilibsuite/frc-docs#279]
PR #273 disables Read the Docs' custom search with the original Sphinx-doc search, which works better.

However, Sphinx search isn't perfect either. Searching for a single word (e.g. `into`) returns no results, nor does searching for an exact phrase (e.g. `new for 2020`) return the page `New For 2020`.

Some possible ways of improving this include:
- ~~[Subclassing the SearchAdapter class](http://www.sphinx-doc.org/en/master/usage/advanced/websupport/searchadapters.html)~~ This is for a Web Support application, which doesn't seem to be sphinx docs (entirely?)

Alternatively, it may be possible to use Read the Docs search, if the issue where there are duplicate and outdated search results is resolved. There should be an issue somewhere for this, although I can't seem to find it in the Read The Docs' GitHub. 

Related links:
- https://github.com/readthedocs/readthedocs.org/issues/4452
- https://github.com/readthedocs/readthedocs-sphinx-search
- https://docs.readthedocs.io/en/stable/guides/searching-with-readthedocs.html
- https://github.com/sphinx-doc/sphinx/issues/6692 [might be a fix?]

**Comment by Modelmat** [comment]
Some Sphinx-doc issues related to searching:
- [section headings are not prioritised](https://github.com/sphinx-doc/sphinx/issues/35)
- [searching fails in code blocks](https://github.com/sphinx-doc/sphinx/issues/4711)
- [exact search](https://github.com/sphinx-doc/sphinx/issues/3301)
- [incomplete search results](https://github.com/sphinx-doc/sphinx/issues/2930)
- [rebuilds breaking search (maybe not an issue anymore?)](https://github.com/sphinx-doc/sphinx/issues/3270)
- [two word searches failing](https://github.com/sphinx-doc/sphinx/issues/1486)
- [searching numbers fails](https://github.com/sphinx-doc/sphinx/issues/776)

**Comment by Daltz333** [comment]
#315 closes this
