### ISSUE TITLE
Markdown URL syntax is backwards

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/frc-docs#2797]
The .rst files currently use `(name)[url]`, but that's not valid Markdown according to https://spec.commonmark.org/0.31.2/#links. It should be `[name](url)` instead.

**Comment by TheTripleV** [comment]
It does use `[name](url)`. Where is it wrong?

**Comment by sciencewhiz** [comment]
https://github.com/wpilibsuite/frc-docs/pull/2690 has `[name](url)`

**Comment by spacey-sooty** [comment]
> It does use `[name](url)`. Where is it wrong?

https://github.com/wpilibsuite/frc-docs/blob/main/source/docs/yearly-overview/yearly-changelog.rst
