### ISSUE TITLE
Use more Sphinx directives.

### ISSUE THREAD

**Issue by Modelmat** [wpilibsuite/frc-docs#282]
This is a list of a few Sphinx directives that I think might be useful to add (if not just because Sphinx provides them), sorted in roughly "wantedness":

### `.. glossary` / `:term:`

Allows to create a glossary of terms. This would be quite useful, especially in more complex sections.

### `.. sectionauthor`
Specifies who wrote the majority of the current section. Useful for when clarification is needed.
Might be a pain if only one author is allowed.
Does not by default get rendered in output.

### `:file:`
Used for naming files. Apparently this looks different?

### `:kbd:`
Used to represent keyboard strokes. This uses the HTML tag `<kbd>` and hence draws a box around the key.

**Comment by AustinShalit** [comment]
glossary and term seem interesting.

I do not think we need section author.

Not sure what file will do/how it changes what end users see.

When do you think we would use kbd over tick marks?

**Comment by Modelmat** [comment]
`:kbd:` will allow expressions such as `ctrl + shift + t` to represented as <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>T</kbd>.

`:file:` seems to be when you have a part of the filename that changes - see http://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-file which italicises the section inside `{x}`
![image](https://user-images.githubusercontent.com/25718989/67153166-1b174380-f330-11e9-85aa-158d698a3dbc.png)
Maybe not that useful.

section author, I'm guessing no because we have git already?

**Comment by AustinShalit** [comment]
Oh... I see now about kbd. Seems cool.

I am not sure where we would use file because hopefully the documents are becoming year agnostic.

Yup. Section authors are redundant with git.

**Comment by sciencewhiz** [comment]
@Modelmat When I looked at the generated file from #295, there's very little distinction of the text in the :kbd: directive. It is not outlined like your example. Unless there's a way to make it more visually distinctive (like your example), I don't think it's worth it.

**Comment by sciencewhiz** [comment]
Looks like better formatting for the kbd directive will be in the next RTD theme release. https://github.com/readthedocs/sphinx_rtd_theme/pull/677

**Comment by Daltz333** [comment]
Closing as it's not really an issue, and we are using glossary. Something to keep in mind going forward
