### ISSUE TITLE
Additional CAN devices

### ISSUE THREAD

**Issue by Spaceman113138** [wpilibsuite/frc-docs#2822]
https://docs.wpilib.org/en/stable/docs/software/can-devices/third-party-devices.html 
This page is missing a lot of new CAN devices like the redux gyro and grapple laserCAN

**Comment by jasondaming** [comment]
Keep in mind that we keep stable pinned to the docs as the season ends and you probably want the [latest version](https://docs.wpilib.org/en/latest/docs/software/can-devices/third-party-devices.html) which has the Canandgyro and LaserCAN.

I am going to take this opportunity to add some of the recently announced motor controllers.
