### ISSUE TITLE
Full PIDCommand Example refers to removed GyroDriveCommands example Project

### ISSUE THREAD

**Issue by Advay17** [wpilibsuite/frc-docs#2843]
https://docs.wpilib.org/en/stable/docs/software/commandbased/pid-subsystems-commands.html#full-pidcommand-example

**Comment by sciencewhiz** [comment]
You're looking at the stable branch which documents the latest stable release (from 2024). The GyroDriveCommands example still exists in the 2024 WPILib release. For documentation of the 2025 beta, switch to the latest/main branch. That page has been updated and now references RapidReactCommmandRobot.
