### ISSUE TITLE
Use Sphynx imgconverter to convert .ai illustrations to .png files at compile time

### ISSUE THREAD

**Issue by yellowjaguar5** [wpilibsuite/frc-docs#285]
As proposed by [@Modelmat in PR #200](https://github.com/wpilibsuite/frc-docs/pull/200#issuecomment-544287577), if we add illustrations to a `source` folder in image folders, we could convert the .ai files to .png files at compile time. More information about the Sphynx plugin can be found [here](http://www.sphinx-doc.org/en/master/usage/extensions/imgconverter.html).

Edit: If people think that this is a good idea, I'm interested in implementing it.

**Comment by Modelmat** [comment]
I see no reason not too.
If we can automate it we should.

**Comment by Modelmat** [comment]
This probably semi-duplicates #237.

As an aside, the `sphinx.ext.imgconverter` doesn't have any options and is rather limited in its functionality.

I have an [extension](https://github.com/Modelmat/sphinxcontrib-drawio) which currently is designed to work for draw.io files. It would not be that difficult to extend this to support arbitrary commands (e.g. ImageMagick for converting ai->png, or similar). It would also be possible to select the converter based on the file extension.

Both would work but the latter already has more options (ie align/width/height) than the imgconverter extension.

**Comment by Modelmat** [comment]
@Daltz333 I've added support for the illustrator files in https://github.com/sphinx-doc/sphinx/pull/6998
Once that is merged, added `sphinx.ext.imgconverter` to the list of extensions should convert `.ai` images automatically to PNGs.

Depending on how the CI is set up, we may get the error `"convert: attempt to perform an operation not allowed by the security policy `gs'"`. This can be resolved by editing the ImageMagick security policy; see the note at the top of [this ArchLinux wiki page](https://wiki.archlinux.org/index.php/ImageMagick).

**Comment by Modelmat** [comment]
PR was accepted and merged; it will be coming out with sphinx 2.4.0.

**Comment by yellowjaguar5** [comment]
Yay! Great job @Modelmat!

**Comment by Daltz333** [comment]
@AustinShalit something for further review in the off-season, but are we fine with using Adobe Illustrator as the complex diagram creation tool of choice?

Is there any free utilities that can open Adobe Illustrator files that we can recommend to contributors?

**Comment by Modelmat** [comment]
We could always insist on SVG files instead; these would get converted to PNGs through `sphinx.ext.imgconverter`.

**Comment by AustinShalit** [comment]
This is something to review in the offseason.

**Comment by Daltz333** [comment]
Closes using SVGs instead
