### ISSUE TITLE
Add ssh information to Pi docs

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#287]
Add a note somewhere about the pi username and password for ssh. Its still the default but people have gotten it confused.

**Comment by PeterJohnson** [comment]
It was on screensteps here, did this not get copied over?  https://wpilib.screenstepslive.com/s/currentCS/m/85074/l/1027260-installing-the-image-to-your-microsd-card#logging-into-the-raspberry-pi

**Comment by Daltz333** [comment]
You right
