### ISSUE TITLE
[artf5907] Online Docs for "Installing the FRC Update Suite" Lack Screen for Restart / Reboot Now

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#288]
>We installed the FRC Update Suite, as we use Java for programming the roboRIO, but did not install the full LabVIEW software.

>We found that the installation of NI Beta Update 1 completed with a Restart / Reboot Now screen.  This screen is not shown at the end of the "Installing the FRC Update Suite" online documentation at https://frc-docs.readthedocs.io/en/latest/docs/getting-started/getting-started-frc-control-system/frc-update-suite.html

>The screen that we observed looked very similar (if not identical) to the screen at the end of the "Installing LabVIEW for FRC (LabVIEW only)" instructions, as shown at https://frc-docs.readthedocs.io/en/latest/docs/getting-started/getting-started-frc-control-system/labview-setup.html

>Recommend adding the Restart / Reboot Now screen to the end of the online instructions for "Installing the FRC Update Suite"

**Comment by sciencewhiz** [comment]
It should probably be conditional, as it didn't prompt when LabVIEW was installed, and this is used for both LabVIEW installed and LabVIEW not installed.

**Comment by sciencewhiz** [comment]
Fixed in #296.
