### ISSUE TITLE
[artf5911] New 2020 Online Docs Site - Left Panel Sometimes Lacks Scrollbar, which is a Problem if on a Laptop with no "ScrollWheel"

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#292]
>The New 2020 Online Docs site uses a website layout with a left pane providing an index to the documentation site.  At least in the situations I tried (Google Chrome on Windows 10 on multiple different computers), the left pane does not show a scrollbar unless the screen is zoomed out far enough to fit the entire pane on the screen (which, ironically, is the situation where the scrollbar isn't actually needed!)

>The attached screen snips help show the problem:

![WPILib-Docs-no-scrollbar](https://user-images.githubusercontent.com/3799260/67427392-19c66f00-f5ed-11e9-98da-239c1aeb508c.png)
![WPILib-Docs-scrollbar](https://user-images.githubusercontent.com/3799260/67427395-1cc15f80-f5ed-11e9-9a04-b1ad2d7b81c0.png)

>The first screen snip shows the scrollbar for the left pane, when the window is zoomed out completely.

>The second screen snip shows the window at a normal zoom level, and the scrollbar for the left pane disappears!

>On a computer with a scrollwheel mouse, this isn't a show-stopper, as the scrollwheel can be used to scroll the pane.  However, on a laptop (which typically does not have a scrollwheel) the navigation panel becomes practically useless and very confusing, particularly since it auto-expands sections and re-navigates automatically when clicking on links in the right panel.

>This problem seems like a Web UI issue, rather than being due to the content of the pages, but hopefully one that can be fixed somehow...

**Comment by AustinShalit** [comment]
This happens on macOS with Safari too.

**Comment by Kevin-OConnor** [comment]
It seems to be an intentional "feature" of the theme: https://github.com/readthedocs/sphinx_rtd_theme/issues/468

I agree that this is undesirable behavior. I'll take a look at the CSS described in that issue as a workaround.
