### ISSUE TITLE
Add uninstall instructions

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#299]
From: https://usfirst.collab.net/sf/discussion/do/listPosts/projects.frc2020beta/discussion.task_reports.topc1998?pageSize=-1#post_post6355

Should delete wpilib/YEAR directory (or frc2019 directory), delete shortcuts, delete environment variables.

**Comment by Daltz333** [comment]
I think a better solution would be to create an uninstaller. This was discussed earlier. We can't rely on the user to manually remove environment variables.

**Comment by sciencewhiz** [comment]
I agree that an uninstaller is better, but it requires a revamp of the installer to support an uninstaller. Given that we're already in beta I think it's too late to do a big change. An uninstall document can be written in a few hours for this year.
