### ISSUE TITLE
Document Joystick HID classes.

### ISSUE THREAD

**Issue by agasser** [wpilibsuite/frc-docs#303]
The docs [here](https://docs.wpilib.org/en/latest/docs/software/commandbased/binding-commands-to-triggers.html#creating-a-joystickbutton) talk about binding commands to a joystick button, but there is some code mixed into the examples for using an XBoxController button. I propose creating a separate section for binding to an XBoxController.

For instance, the first example is regarding creating a joystick button, but it also creates an instance of XBoxController:
```
Joystick exampleStick = new Joystick(1); // Creates a joystick on port 1
XboxController exampleController = new XboxController(2); // Creates an XboxController on port 2.
```

It's not until the [Composing Triggers](https://docs.wpilib.org/en/latest/docs/software/commandbased/binding-commands-to-triggers.html#composing-triggers) section until we see an XBoxController related example, but at that point it is not explained that the `XBoxController.Button.kX.value` enum can be used in place of a button number. I think a straightforward example could be helpful.

**Comment by Oblarg** [comment]
This should probably not be in the command-based documentation; we should have separate docs for the HIDs.  Anyone have a good idea where these should be located?

**Comment by agasser** [comment]
Personally, I'm OK with it being in the command-based documentation because it is part of the new wpilibNewCommands framework. It's also about running _commands_ using HID. Just my opinion.

**Comment by ItayZiv** [comment]
I don't know if this has been changed this the issue has been opened, but right now it does clarify and say its a `GenricHID` and its subclasses, which both `Joystick` and `XboxController` are, and they are both relevant because a JoystickButton needs to be created for both joysticks and controllers.

**Comment by Daltz333** [comment]
Ideally, I'd like to see this in a line of "Basic Programming" tutorials, as that's what I'd like to move the Basic Programming section towards.
