### ISSUE TITLE
how to read a stack trace and how to read a gradle error

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#325]
Many times people will post for help and only provide the last item in the stack trace (which isn't helpful) or the fact that gradlerio reports an error. It would be helpful to document how to read a stack trace to find where the problem really exists. It would also be helpful to document how far up the real error is in gradlerio. That way when someone asks for help, they can be pointed to this document instead of having to explain everything for each person that asks a question. Even if they can't figure it out, they will then have the information that they need to post to get the question answered.

Here's one example on CD, but there are many. https://www.chiefdelphi.com/t/error-message-from-robotbase/162791

**Comment by Daltz333** [comment]
@sciencewhiz could an implementation of this be similar to #515 where it brings up things like
- NullPointerException because a team forgot to instantiate their motor controller
- Duplicate CAN assignments, etc

or where you talking more about a general purpose java article? Perhaps just a link to a good resource would be fine?

**Comment by sciencewhiz** [comment]
I look at this as the more generic form of #515, and might be a lead-in for talking about specific issues. For example, gradle says build failed for a number of reasons, and you have to scroll up to find the specific reason (ie coding error, networking error, mismatched images). 

For stack trace, it might fall under a robots shouldn't quit article and then talk about how to decode the stack trace and then figure out if it's a general coding issue (like NullPointerException) or something wpilib specific (like duplicate WPILib hardware assignments) in which case it would go into more detail..

I haven't seen a general purpose stack trace article that I'm really happy with, but that would certainly be an option.

Do you get an error for duplicate CAN assignments? I think that would be vendor specific.
