### ISSUE TITLE
Create update guide for new command based

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#334]
From Beta Forms:
>I tried porting our code to use the new command framework in two different ways:

>a)	I took our old code and tried to make the changes in the right places ? e.g. changing Subsystem to SubsystemBase.  However, while this was initially quicker, I suspect that I missed some parts and the code didn?t work. The instructions were not that helpful in this process ? since it didn?t really give me a checklist of things to update. I could probably spend some more time and find the mistakes. If there is an automated script that did some of this, it might be helpful for teams.

>b)	I started by creating a new project from the template and cutting-and-pasting code from the original into the correct places. This worked better for the most part. It would still be useful to have an explicit list of porting steps for common code components. You may need to create different versions of this list. For example, a list of changes for needed to make the code work - E.g., For file ExampleCommand.java ? 1) change Command to CommandBase.  ExampleSubsystem.java needs similar changes (i.e. Sybsystem-->SubsystemBase). You could then  have list of changes to use the new coding style ? For Robot.java 1) move declarations/initialization of subsystems into RobotContainer.java

**Comment by Daltz333** [comment]
I'm not sure this is quite a large factor now with a "year" of maturity.

**Comment by ItayZiv** [comment]
In general not quite sure how convenient a guide about porting from old command based to new would be, being it’s a lot of manual work because of the changes...
