### ISSUE TITLE
Improve coupling

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#335]
>Some examples of using the PIDController in different situations (drive, lift, arm) would also be helpful. The same is true for the kinematic classes. For example, the documentation in https://frc-docs.readthedocs.io/ did not give guidance on where to use the kinematic classes and how they fit in with any other packages. I ended up looking at some of the updated example code to get a better idea.  A few more links to relevant coding examples within the documentation would help greatly.

**Comment by Daltz333** [comment]
Is this still valid with the incorporation of the examples section?

**Comment by AustinShalit** [comment]
I think so. More examples would help here.

**Comment by Daltz333** [comment]
> Some examples of using the PIDController in different situations (drive, lift, arm) would also be helpful.

Using and Tuning a PIDController

> For example, the documentation in frc-docs.readthedocs.io did not give guidance on where to use the kinematic classes and how they fit in with any other packages. I ended up looking at some of the updated example code to get a better idea. A few more links to relevant coding examples within the documentation would help greatly.

The kinematic articles as is very briefly outlies what they are and are focused on implementation. They do not go into *why* the user should use them, or common usecases. They should get expanded or detailed.

**Comment by Daltz333** [comment]
Closed in favor of 
#1290 
#1291
