### ISSUE TITLE
Port LabVIEW dashboard from screensteps

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#340]
https://wpilib.screenstepslive.com/s/currentCS/m/driver_station/l/144977-frc-driver-station-labview-dashboard

**Comment by Daltz333** [comment]
Was this ever ported? Because there is https://docs.wpilib.org/en/stable/docs/software/driverstation/troubleshooting-dashboard-connectivity.html#labview-dashboard

**Comment by sciencewhiz** [comment]
That's troubleshooting, not how the labview dashboard works. https://web.archive.org/web/20190830235558/https://wpilib.screenstepslive.com/s/currentCS/m/driver_station/l/144977-frc-driver-station-labview-dashboard

**Comment by yellowjaguar5** [comment]
@Daltz333 Whoops, sorry for opening a new issue. I'll add this page in #662.
