### ISSUE TITLE
Port Operating a compressor for pneumatics article from screensteps

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#354]
https://wpilib.screenstepslive.com/s/currentCS/m/java/l/599707-operating-a-compressor-for-pneumatics

Add link to this page once ported: http://frcdocs.wpi.edu/en/latest/docs/software/can-devices/pneumatics-control-module.html

**Comment by prateekma** [comment]
Isn't all this info already here?
http://frcdocs.wpi.edu/en/latest/docs/software/actuators/pneumatics.html#generating-and-storing-pressure

**Comment by AustinShalit** [comment]
I logged into ScreenSteps, all of the information on the Operating a compressor page is located on the pneumatics page in rtd.
