### ISSUE TITLE
Encourage Static IP for complex networks over mDNS

### ISSUE THREAD

**Issue by prateekma** [wpilibsuite/frc-docs#372]
For coprocessors and roboRIO, etc.

**Comment by Kevin-OConnor** [comment]
The documentation should not encourage static IP for the roborio. The documentation very intentionally encourages DHCP for the roborio

**Comment by Daltz333** [comment]
What if we specify it's only for advanced networks? AKA, networks with coprocessors where things become a bit more crucial.

**Comment by carbotaniuman** [comment]
Where would this to? Static IP is really the way forward for coprocessors.

**Comment by Daltz333** [comment]
To clarify, I think we can document that static IP is encouraged for advanced networks, including co-processors.

**Comment by Kevin-OConnor** [comment]
> 
> 
> To clarify, I think we can document that static IP is encouraged for advanced networks, including co-processors.

I mean, it's really only co-processors themselves. Static IP is not encouraged for DS PC or roboRIO under any network circumstances. It is much easier to do wrong than DHCP.

**Comment by Daltz333** [comment]
I think the following snippet under the static IP sections would solve this issue:

```
Static IP may be necessary for devices such as co-processors, where the ability to navigate to the device is necessary. Devices such as the roboRIO and Driver Station should remain in a DHCP configuration
```
Is this satisfactory @Kevin-OConnor

**Comment by JonathanLindsey** [comment]
Please correct me if I'm wrong but if a co-processor is set to a static IP address and the roboRIO is set to DHCP they will not be able to communicate when they are on the practice field communicating via WiFi because the co-processor will be in the 10.TE.AM.X/24 range and the roboRIO will be assigned an IP address in the 10.0.0.Y/24 range and these are different subnets.

**Comment by PeterJohnson** [comment]
Why is the co-processor netmask set to /24 instead of /8?  Just always use /8 when setting static and that case will work fine.

**Comment by JonathanLindsey** [comment]
That makes since. So we need to recommend setting ALL the subnet masks to 255.0.0.0 in the [IP Configurations - On the Field Static Configuration](https://docs.wpilib.org/en/stable/docs/networking/networking-introduction/ip-configurations.html#on-the-field-static-configuration) section.

**Comment by Daltz333** [comment]
@Kevin-OConnor

**Comment by JonathanLindsey** [comment]
Alternatively I think the practice field router DHCP service could be configured to give out subnet masks of 255.0.0.0. This way we don't have to worry about if teams heed the recommendation to use a 255.0.0.0 subnet mask on all their static devices and all the devices are able to communicate.

**Comment by Kevin-OConnor** [comment]
> Alternatively I think the practice field router DHCP service could be configured to give out subnet masks of 255.0.0.0. This way we don't have to worry about if teams heed the recommendation to use a 255.0.0.0 subnet mask on all their static devices and all the devices are able to communicate.

I'm not 100% certain but I feel like I recall that the Linksys APs used on the practice field can't be configured for a 255.0.0.0 subnet.

**Comment by Daltz333** [comment]
@Kevin-OConnor since there is a disagreement here, should this issue be closed as a ``wontfix``?
