### ISSUE TITLE
Add simulation tutorial

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/frc-docs#374]
The simulation GUI page as it currently exists is more of a reference, says what things are but doesn't walk through a use case.  A step-by-step tutorial which shows an example robot program, starting up the GUI, enabling the robot, hooking up a joystick, tweaking inputs and observing outputs, etc, would do a much better job of introducing teams to the utility of the GUI.

This could be followed by a step-by-step tutorial of showing how the manual testing the GUI provides can be automated via writing a unit test in code.

**Comment by Kython89** [comment]
Would this include how to use lowfi_simulation, halsimprint, halsim_ds_nt, halsim_ds_socket.  After poking around in some of the unit tests I think I've figured out some of it....however it isn't obvious from the current docs that those modules even exist or how to use them.

I think these resources could really empower the software teams across FIRST if they were well documented and easy to use.

**Comment by Daltz333** [comment]
Superceded by #704
