### ISSUE TITLE
Missing instructions to deploy code to robot in VS Code

### ISSUE THREAD

**Issue by Billfred** [wpilibsuite/frc-docs#387]
The instructions for creating a new WPILib project and going through the basics of each section are well-documented [here](https://frc-docs.readthedocs.io/en/latest/docs/getting-started/running-a-benchtop/creating-benchtop-test-program-cpp-java.html#creating-your-benchtop-test-program-c-java).

The steps to configure the driver station software, verify connectivity, and enable the robot for the first time as well-documented [here](https://frc-docs.readthedocs.io/en/latest/docs/getting-started/running-a-benchtop/running-benchtop-test.html).

However, my new programmer has pointed out that there are no instructions on the intermediate step of _actually putting the code on the robot so it can run_.  And as someone who does not program the robot himself, I'm stumbling around in screenshots looking for best guesses.

**Comment by prateekma** [comment]
They should be available here: https://docs.wpilib.org/en/latest/docs/software/wpilib-overview/deploying-robot-code.html

**Comment by prateekma** [comment]
Perhaps a link to that article should be added in the benchtop robot program series.

**Comment by Billfred** [comment]
Would agree with that; Getting Started tends to attract newbie students and mentors alike and I spent a good ten minutes trying to find that article before figuring this was somehow skipped in the documentation.  (I date someone who does not participate on a team, so I know how easily obvious things can get skipped.)

Thank you for your help!
