### ISSUE TITLE
Hardware Documentation Rewrite

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#40]
The hardware section is severely poor. The images are unclear, the language is confusing, and other such problems. Unfortunately, I don't have quite the knowledge to rewrite these articles. Contributors welcome!

**Comment by Kevin-OConnor** [comment]
What hardware documentation are you referring to specifically?

**Comment by Daltz333** [comment]
Wiring PWM, Can. More introduction on various mechanical systems. Would be great to have.

**Comment by yellowjaguar5** [comment]
How is this different from #55? Can the two issues be combined?
