### ISSUE TITLE
Clarify the behavior of the DS's diagnostics tab around CAN devices

### ISSUE THREAD

**Issue by PiNerd3** [wpilibsuite/frc-docs#419]
Currently http://docs.wpilib.org/en/latest/docs/software/driverstation/driver-station.html#diagnostics-tab mentions (list item 4) that "[t]hese items [the CAN device firmware version numbers] may not be present if the webdash plugin has not been installed using CTRE Phoenix Lifeboat". Pheonix Lifeboat is deprecated (and I believe the webdash plugin is as well), so this is out-of-date information. 

The fix might be as simple as deleting this sentence; I'm not familiar with what _would_ cause this info to break or not appear.

**Comment by prateekma** [comment]
I believe deleting the sentence should make it accurate. Deploying robot code to the roboRIO should probably be enough this year -- this is all that's needed for Phoenix Tuner to work as well.
