### ISSUE TITLE
NI Update uninstall instructions encourage blind removal of all installed software which uses NI components, including non-FRC products

### ISSUE THREAD

**Issue by PiNerd3** [wpilibsuite/frc-docs#429]
In reference to this page and section, on uninstalling previous versions of the NI Update / FRC Update / FRC Game Tools (I've seen it called all three): http://docs.wpilib.org/en/latest/docs/getting-started/getting-started-frc-control-system/frc-game-tools.html#select-components-to-uninstall (which is https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/getting-started/getting-started-frc-control-system/frc-game-tools.rst#select-components-to-uninstall in the source.)

Problem: Some students (like me) might have Vernier software, such as Vernier Power Amp, installed. If these students followed the instructions blindly and didn't read the confirmation box closely, they would end up uninstalling these products unwittingly. 

Proposed solution: A `Note` should be added that if students know they have any Vernier software installed, they should go carefully over the list of programs they're uninstalling before clicking remove. I'd be happy to do a PR; I just don't have time right now.

Vernier Power Amp might actually be the only program that would lead to this problem. I'm not sure if there are other programs, from Vernier or other companies, that would be included in the NI Package Manager. (Vernier Logger Pro doesn't show up on the list, fwiw.) Even if Power Amp is the only one, it's still worth a mention, imo.

Here's a screenshot of the section in the docs and of my NI Package Manager. I had to notice and uncheck the box for Power Amp (outlined in red in the screenshot).

![screenshot of http://docs.wpilib.org/en/latest/docs/getting-started/getting-started-frc-control-system/frc-game-tools.html#select-components-to-uninstall and my NI package manager](https://user-images.githubusercontent.com/18648574/71762288-61396900-2e82-11ea-804a-075a90779981.png)

**Comment by AustinShalit** [comment]
MultiSim would also be caught by this
