### ISSUE TITLE
Setup custom URL

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#43]

**Comment by Daltz333** [comment]
What exactly is this issue?

**Comment by AustinShalit** [comment]
To redirect something like `docs.wpilib.org` to the site.

**Comment by Daltz333** [comment]
Thats pretty sweet. I believe you have access to the direct readthedocs admin settings, so you can do https://docs.readthedocs.io/en/stable/custom_domains.html

Another option is for WPI to do the hosting itself, but then you lose valuable features. Such as RTD search, its PDF and EPUB generation, webhook auto-generation, etc. Sure those can be done automatically with a few scripts, but should it?

**Comment by AustinShalit** [comment]
My plan is option 1.  Just need to get around to it 🙂. It will happen before the beta.

**Comment by AustinShalit** [comment]
🎉 https://docs.wpilib.org 🎉
