### ISSUE TITLE
Reference 2020 trajectory generation in PathWeaver usage docs instead of Pathfinder

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/frc-docs#438]
https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/pathfinder/index.html still references Pathfinder, which has been superseded by the built-in 2020 trajectory generation. Perhaps it could link to https://docs.wpilib.org/en/latest/docs/software/advanced-control/trajectories/index.html instead.

**Comment by agasser** [comment]
The heading of the section is also "Autonomous Planning with **Pathfinder**", and the [introduction page](https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/pathfinder/introduction.html) says:
> Many teams and organizations have created path planning libraries for FRC, but the officially supported library for WPILib is **Pathfinder**

**Comment by AustinShalit** [comment]
Closed by #457
