### ISSUE TITLE
Update Contribution Guidelines to include link to WPILib Mission statement

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#44]
It can be found here: https://github.com/wpilibsuite/allwpilib/blob/master/README.md

We also probably need to update the mission statement but we can do that later.

**Comment by Daltz333** [comment]
Does frc-docs being under Creative Commons affect anything?

**Comment by AustinShalit** [comment]
Hmm. Let’s copy paste the first few lines before it starts talking about licensing.
