### ISSUE TITLE
Anaconda needed for Robot Characterization installation. 

### ISSUE THREAD

**Issue by EliasRojasC** [wpilibsuite/frc-docs#447]
I was just installing the robot characterization suite on windows and I was having a lot of issues downloading it. I had python 3.8 and did all the steps listed in the guide. However, I continued to get issues with it telling me that lapack/blas wasn't installed. I looked around and it said that these are packages that came with anaconda. I installed anaconda and it worked right away. It would be better if this was included in the documentation.

Thanks!

**Comment by Daltz333** [comment]
Python 3.7 is the recommended Python distribution.

**Comment by calcmogul** [comment]
frc-characterization requires the statsmodels package, and PyPi doesn't have a Python 3.8 build of it. It has 3.7 though.

**Comment by EliasRojasC** [comment]
Oh thanks! That makes sense.
