### ISSUE TITLE
many pages still say "Update Suite" -- potentially confusing

### ISSUE THREAD

**Issue by papaJupe** [wpilibsuite/frc-docs#449]
There are numerous references to "Update Suite" on various pages, e.g. imaging-your-roboRIO, but as far as I can see there's no such thing any more. So this text might confuse newcomers, et. al. It seems to have been replaced by the Game Tools download? What happens when there's updates to the Game Tools? Will the having the NI update checker enabled tell you about this? I didn't see anything about keeping "Tools" updated in the new documentation.

**Comment by Daltz333** [comment]
The Update Suite references do indeed need to be corrected to instead say "FRC Game Tools".

Additionally, the NI Update Checker is *not* the supported way to verify updates. All NI updates will be announced in a Team Update. 

NI Updates during the year can simply be installed over the existing NI installation. This is mentioned in [FRC Game Tools](https://docs.wpilib.org/en/latest/docs/getting-started/getting-started-frc-control-system/frc-game-tools.html#uninstall-old-versions-recommended). New year installations 2019 -> 2020 must have the previous year uninstalled, and only then can the new year installation be installed.
