### ISSUE TITLE
Linux Install Instructions do not including updating path

### ISSUE THREAD

**Issue by Modelmat** [wpilibsuite/frc-docs#454]
Every time I build the project on Linux, I get this error:
```
which: no arm-frc2020-linux-gnueabi-gcc in (/home/modelmat/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
```
This binary is located in `~/wpilib/2020/roborio/bin/`, but this is not in $PATH.
Looking at the Windows setup, and the [uninstall instructions](https://frc-docs.readthedocs.io/en/latest/docs/getting-started/getting-started-frc-control-system/wpilib-setup.html#uninstall-instructions), the Windows installer adds both `~/wpilib/2020/roborio/bin` and `~/wpilib/200/frccode` to $PATH.

Adding both of these to $PATH removes this error (warning?). Should instructions for adding these directories to $PATH be added to the Linux install instructions?

I believe this error will likely occur on macOS too. It would also be wise to add these to the uninstall instructions for both.

**Comment by ThadHouse** [comment]
You don't need to normally add those to path. GradleRio automatically knows to check the wpilib/2020 folder without having the compiler in the path. That message will still be printed in the info window, but the compiler should still be found with the direct lookup.

Usually, if that doesn't happen, it's because the compiler or the sub executables it uses are not marked executable.

**Comment by Modelmat** [comment]
Well, why would that message be printed?
I know it *works* (since I can build) but I don't see why it should be printed.
Probably not the right repository then..

**Comment by ThadHouse** [comment]
Some Linux platforms we've seen do that, haven't been able to pinpoint it and it's not all distros. 

The message normally goes into info, and happens because gradlerio tries 3 different methods to find the compiler. So it will always check the path one, even if the fixed location one is found.
