### ISSUE TITLE
Robot Characterization: Track Width

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#506]
There isn't any documentation of the track width characterization

**Comment by jasondaming** [comment]
What are you looking for regarding track width?  Details into how it is calculated?  How it is run (I think this is self explanatory)? Some common problems with it (ex. pneumatic wheels can have a track width 2x their actual because of their friction)?

**Comment by AustinShalit** [comment]
I think @sciencewhiz is talking about how the characterization tool has a mode for track width but this mode is not documented in the documentation here: https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/robot-characterization/characterization-routine.html
