### ISSUE TITLE
Limit switch doc should be in sensors

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#507]
The limit switch doc is in old-commandbased but should be in sensors. While it does have example for old command based it also has example code for other templates. 

https://docs.wpilib.org/en/latest/docs/software/old-commandbased/commands/limit-switches-control-behavior.html

**Comment by Starlight220** [comment]
Another problem with this is that it extends SimpleRobot, which was removed a while ago.
