### ISSUE TITLE
Test mode and dashboard documentation unclear and out of date

### ISSUE THREAD

**Issue by agasser** [wpilibsuite/frc-docs#514]
There are several places in the documentation that reference `addActuator()` or `addSensor()` but these methods no longer exist.
- [Enabling Test mode (LiveWindow)](https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/smartdashboard/test-mode-and-live-window/enabling-test-mode.html)
- [Using Test Mode](https://docs.wpilib.org/en/latest/docs/software/wpilib-overview/using-test-mode.html)

It's also unclear if subsystems, actuators, and sensors _need_ to be added with code, or if they will automatically populate.
- [This page](https://docs.wpilib.org/en/latest/docs/software/wpilib-overview/using-test-mode.html#adding-test-mode-code-to-your-robot-code) says to be sure to add your subsystems.
- [This page](https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/smartdashboard/test-mode-and-live-window/enabling-test-mode.html#explicitly-vs-implicit-test-mode-display) says everything will automatically populate, but you can customize the grouping.
- [This page](https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/shuffleboard/advanced-usage/shuffleboard-commands-subsystems.html#subsystems-in-test-mode) says RobotBuilder will generate the code but you can do it yourself with `setName()` but it's not clear if I do that on just my subsystems or on all of my actuators and sensors.
- There is a [Shuffleboard](https://github.com/wpilibsuite/allwpilib/blob/master/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/shuffleboard/Robot.java) example, but it doesn't seem to make use of the subsystem grouping, although I haven't tried executing it.

This [Test Mode in SmartDashboard](https://docs.wpilib.org/en/latest/docs/software/wpilib-overview/using-test-mode.html#test-mode-in-smartdashboard) section seems to be missing a screenshot. It says, "The above sample code produces the following output when the Driver Station is put into Test mode then enabled.", but there is no screenshot or output. Also, the [code sample](https://docs.wpilib.org/en/latest/docs/software/wpilib-overview/using-test-mode.html#adding-test-mode-code-to-your-robot-code) has a markup error so the tabs don't render correctly.

This is my third year in FRC and I am still confused with the difference between SmartDashboard, LiveWindow, and Shuffleboard. It would be really helpful to provide some guidance / recommendations. If I understand correctly, Shuffleboard is the newest option with the most features, so I image it is "recommended" for new code. But, would there be cases where I would use the other two? Also, it's confusing that Shuffleboard has SmartDashboard and LiveWindow tabs, are those just for backward compatibility? And lastly, if I am using Shuffleboard, should I still use `SmartDashboard.putData()` or should I be using the Shuffleboard class? The [first code example](https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/shuffleboard/getting-started/shuffleboard-displaying-data.html#displaying-values-in-normal-operating-mode-autonomous-or-teleop) for how to use `Shuffleboard` uses the `SmartDashboard` class.

It would be really helpful to include a description of the `BuiltInWidgets` with a screenshot of each one. For example, it's not clear what the difference is between a Toggle Switch, a Toggle Button, and a Boolean Box.

**Comment by Daltz333** [comment]
> Overall, I think this article needs a bigger overhaul. Putting a subsystem to SmartDashboard doesn't add the items to LiveWindow, they are added automatically. Putting a subsystem to SmartDasbhoard shows the scheduling status of that subsystem (what the default command is, and which commands its running).
