### ISSUE TITLE
Add links to roboRIO manual & specs

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#523]
Manual: https://www.ni.com/pdf/manuals/374474a.pdf
Specs: https://www.ni.com/pdf/manuals/374661a.pdf

These links should be added to the roboRIO information

**Comment by sciencewhiz** [comment]
The former already is: http://docs.wpilib.org/en/latest/docs/getting-started/getting-started-frc-control-system/control-system-hardware.html#national-instruments-roborio

**Comment by yellowjaguar5** [comment]
Added in #619
