### ISSUE TITLE
Instructions for continuous integration

### ISSUE THREAD

**Issue by Modelmat** [wpilibsuite/frc-docs#524]
There should be a page detailing how to set up continuous integration on the robot project. There is the roborio/WPILib docker image.

This probably should be vendor-agnostic although example configurations for azure/ other vendors would likely not hurt.

**Comment by ThadHouse** [comment]
Closing because of duplicate of #57 

Definitely something we want. Would likely choose azure because it's cross platform, free, and really easy to use.

**Comment by Modelmat** [comment]
Oops, the one time I forget to search :P.
