### ISSUE TITLE
Smart dashboard stale data article not ported

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#528]

**Comment by Daltz333** [comment]
It could probably just be added as a note somewhere instead

https://webcache.googleusercontent.com/search?q=cache:Lm0Zrx2dNUwJ:https://wpilib.screenstepslive.com/s/currentCS/m/smartdashboard/l/255408-stale-data-and-smartdashboard+&cd=1&hl=en&ct=clnk&gl=us&client=firefox-b-1-d
