### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Team2883** [wpilibsuite/frc-docs#547]
Example works, cant get it to work when we do our own just a straight line

Code
https://github.com/Team2883/Competition_Code_2020

**Comment by Oblarg** [comment]
What exactly isn't working?  I'll need something more specific to be able to provide reasonable help.

**Comment by Team2883** [comment]
We can get the robot to run on the example from path weaver, it works a nice.  Then when we run our own path it just goes straight.  No turn just straight forever.

**Comment by Oblarg** [comment]
For starters, your starting angle is -180 *radians*, which is probably not intentional.

**Comment by Team2883** [comment]
-180 was the example code with they set it to go backwards.

**Comment by AustinShalit** [comment]
Can you please share your path weaver project?

**Comment by Daltz333** [comment]
Closed as stale. Reopen if further questions.
