### ISSUE TITLE
Expand On Network Tables Beyond Basics - Missing Create Table and Create Subtable Examples

### ISSUE THREAD

**Issue by Sn3akyP3t3** [wpilibsuite/frc-docs#549]
Referring to:
https://docs.wpilib.org/en/latest/docs/software/networktables/networktables-intro.html

This seems to cover quite a bit, but assumes a table "datatable" exists, but doesn't really explain how that got created.  Would be great if there was examples on how to make sub-tables as well.

**Comment by ThadHouse** [comment]
The tables are virtual, so the call to getTable() will in essence create the table, and then on that object you can call getSubTable() to create a subtable of that table. There is no explicit create table calls, because just creating the an entry on the NetworkTable object is all that is needed.

**Comment by ThadHouse** [comment]
For a more precise answer, NetworkTables is at the low level just a flat list of keys, and the tables are just separators in the keys list.

So, a key like `/My/Special/Vision/Table/SomeString` will be an entry called `SomeString` nested in all of the paths listed before it. There is no actual entry for the individual tables in the data structures, as they are just virtualized based on the separators.

**Comment by Sn3akyP3t3** [comment]
I didn't even think to look for get methods creating things :)

Network tables went through an overhaul some years ago I believe and I saw getTable and getSubTable appear to be deprecated.  I didn't realize they were still available.  What is the alternative, if any?

**Comment by ThadHouse** [comment]
The ITable interface was deprecated, along with the NetworkTable class in `edu.wpi.first.wpilibj.networktables`. The NetworkTable class in `edu.wpi.first.networktables` is still fully supported, and is the recommended way to do these things.

The rewrite basically added multiple Instances of NetworkTables that could run independently at the low level, along with Entries to avoid always needing key lookups. The `NetworkTable` API in `edu.wpi.first.networktables` is still the recommended way to handle all the groupings, its just slightly different then the old one so it moved packages.
