### ISSUE TITLE
Update pages to follow style guide

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#55]
Various pages are outdated and poorly formatted.

**Comment by Daltz333** [comment]
Hardware pages need to be done, @yellowjaguar5 if you're bored and looking for something to do. I'm currently investigating docs for the new features such as kinematics and such.

**Comment by yellowjaguar5** [comment]
I’ll take a look and submit a PR soon @Daltz333. School has started for me, so it might be a little while.

**Comment by yellowjaguar5** [comment]
@Daltz333 Are there other sections of the docs that need a style-guide check?

**Comment by Daltz333** [comment]
I think hardware was the last one. Waiting for merge before I close this.
