### ISSUE TITLE
Add documentation for using flexible version of Ramsete Controller

### ISSUE THREAD

**Issue by HFocus** [wpilibsuite/frc-docs#552]
While the documentation on the Ramsete Controller in the docs is good, I was unable to find any tips on how to deal with the more flexible version of the Ramsete Controller. The most I could find is a hint towards it in the javadocs for the RamseteCommand class.

> Advanced teams seeking more flexibility (for example, those who wish to use the onboard PID functionality of a "smart" motor controller) may use the secondary constructor that omits the PID and feedforward functionality, returning only the raw wheel speeds from the RAMSETE controller.

I am having a particularly hard time giving the controller the outputMetersPerSecond parameter for the secondary constructor, and actually retrieving these values from the Controller. I assume that this is done in a very similar way to the outputVolts parameter in the primary constructor. If so then I think I know what to do to retrieve values, but to build the BiConsumer to be passed to the Ramsete controller I am at a loss for right now.

It would be super useful to clarify the outputMetersPerSecond parameter on the docs for teams who want a bit more flexability with RamseteCommand. I'll keep rooting around and post back here if I find how to construct the outputMetersPerSecond BiConsumer, so that we can at least document it here for now.

**Comment by HFocus** [comment]
I figured it out. Looking at this:

https://docs.wpilib.org/en/latest/docs/software/examples-tutorials/trajectory-tutorial/creating-following-trajectory.html
> The output consumer: This is a method reference (or lambda) to the drive subsystem method that passes the voltage outputs to the drive motors.

It seems we have to make our own method with (double, double) as params and reference it in the constructor in a very similar way to outputVolts. I'm not very familiar with BiConsumers so I didn't notice it right away.

I still think this should be addressed somewhere in the documentation, so I won't close the issue yet.

**Comment by ItayZiv** [comment]
Just to clarify, what could be useful is the documentation for Lambdas in general, anyone who is familiar with lambdas should be able to figure out any kind of Consumer/BiConsumer/Supplier etc...

Quite a few people seem to have a hard time grasping the concept of a lambda, being essentially a reference to some kind of method, which can be created inline, allowing something like RamseteCommand to directly output to the setVoltage/Velocity functions in your subsystems

**Comment by Alphyte** [comment]
Is this page what you were looking for? https://docs.wpilib.org/en/latest/docs/software/advanced-controls/trajectories/ramsete.html

**Comment by Daltz333** [comment]
I am going to close this as documentation for the Ramsete controller specifically exists, see @Alphyte comment. If you feel like things need to be narrowed down further, feel free to reopen with an explanation on what exactly needs to be expanded on.
