### ISSUE TITLE
WPILib Overview - Split VSCode docs into VSCode section

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#558]
The majority of "WPILib Overview" is just Visual Studio Code documentation

**Comment by Daltz333** [comment]
@AustinShalit any ideas where to put the "new for 2020" and "known issues" documents as they aren't really vscode related. I feel like these should be part of the first things teams see after the getting started section.

**Comment by AustinShalit** [comment]
They can stay in the overview for now because they do not have another appropriate home.

**Comment by Starlight220** [comment]
> The majority of "WPILib Overview" is just Visual Studio Code documentation

Is this still relevant / should I work on this?

**Comment by Daltz333** [comment]
I would say this is still open. New for 2020 and Known Issues should still stay in WPILib Ovreview unless a suitable replacement can be thought of.
