### ISSUE TITLE
Flesh out basic programming and advanced programming sections

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#56]
These sections should include a guide on various basic FRC tutorials as related to FRC

- PID (oblarg?)
- Feedforward (oblarg?)
- Controlling various robot components (elevator, shooter, etc)

**Comment by pgfisico** [comment]
Contributor info states new articles are not needed at this time - does that apply to this issue as well?

https://github.com/wpilibsuite/frc-docs/blob/3d529410abedc2223d732b29c933ee89ba9f0c3e/contributing.md#L5

Is this issue seeking a port of the existing documentation or something new? Personally I think the existing C++/Java documentation linked below is incomplete and not very useful. I have not looked through the LabVIEW documentation.

- https://wpilib.screenstepslive.com/s/currentCS/m/cpp/c/57249
- https://wpilib.screenstepslive.com/s/currentCS/m/java/c/57247
- https://wpilib.screenstepslive.com/s/currentCS/m/labview/c/57251

**Comment by Daltz333** [comment]
Ah. Thank you for the mention. That note is quite a bit old as most of the current screensteps as been ported over. Yes, new articles can be accepted. They will be a bit more *checked* then ports, so be patient if the review process takes some time.

**Comment by Daltz333** [comment]
@pgfisico See https://frc-docs.readthedocs.io/en/develop/contributing.html#note-on-new-articles

**Comment by Kevin-OConnor** [comment]
I disagree that we should be doing this. There are plenty of guides/etc. out there to teach you C++\Java\LabVIEW and without creating an entire curriculum I don't see why we would want to re-invent that wheel.

**Comment by Daltz333** [comment]
After discussion with Thad. I agree. Will update the description.

**Comment by Piphi5** [comment]
What is the difference between something like the "Basic PID" tutorial mentioned in the description and the [intro to PID](https://docs.wpilib.org/en/latest/docs/software/advanced-control/introduction/introduction-to-pid.html) under advanced controls?

**Comment by sciencewhiz** [comment]
This issue was created long before the intro to PID article was written.
