### ISSUE TITLE
Recommend StringBuilder over "+" Concatentation

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#563]
Plop this somewhere

**Comment by PeterJohnson** [comment]
Not without a benchmark on the Rio showing it’s better...

**Comment by sciencewhiz** [comment]
I ran the following code on the roboRIO with each of the 6 options, as well as without setting the StringConcatFactoryStrategy. The best was without setting anything, at 17 seconds. The next best was MH_INLINE_SIZED_EXACT which was about 20 seconds. The worst was setting BC_SB at 60 seconds. However the Stringbuilder was about 0.26 seconds. 

```
public void teleopInit() {
    double finish, start;
    String string = "Random Number: ";
    StringBuilder sb = new StringBuilder("Random Number: ");

    start = Timer.getFPGATimestamp();
    for (int i=0; i<10000; i++) {
      string += Math.random();
      
    }
    finish = Timer.getFPGATimestamp();
    System.out.println(string);
    System.out.println("10000 String Concat: " + (finish-start));

    start = Timer.getFPGATimestamp();
    for (int i=0; i<10000; i++) {
      sb.append(Math.random());
      
    }
    finish = Timer.getFPGATimestamp();
    System.out.println(sb);
    System.out.println("10000 String Builder: " + (finish-start));
  }
```

**Comment by Daltz333** [comment]
When I was testing. I noticed I got really inconsistent results between each test. If stringbuilder was first it would go slower than my other tests. Can you reproduce this by changing the order of your concatenations?

**Comment by sciencewhiz** [comment]
It was a little slower when first, but still more then an order of magnitude faster then string concatenation.

**Comment by sciencewhiz** [comment]
changing from a random number to a constant did improve the string concatenation a little, but string builder is still much faster.

**Comment by Daltz333** [comment]
Closing as https://github.com/wpilibsuite/GradleRIO/pull/411 has been merged

**Comment by sciencewhiz** [comment]
Even with that change, stringbuilder was still much faster
