### ISSUE TITLE
Add documentation on how to set up AzureCI for CI builds

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/frc-docs#57]
Low on the priority list, but it gets asked often enough it would be work doing as part of the simulation work.

**Comment by Daltz333** [comment]
Personal notes:
- add to readme
- also add docs for installing latex (windows)
- also add docs for installing graphviz (windows)
- convert readme to rst?

**Comment by Daltz333** [comment]
@ThadHouse Are you talking about how to setup Azure in general? Or for frc-docs?

**Comment by ThadHouse** [comment]
As a doc for teams to use to set up CI for their code.

**Comment by Daltz333** [comment]
I don't have enough knowledge of Azure to write an article on it 😅

**Comment by ItayZiv** [comment]
Does this specifically need to be azure though?

**Comment by Daltz333** [comment]
Github actions would also be suitable.

**Comment by AustinShalit** [comment]
All of the providers have similar features. I think the key steps are:
- Use docker to grab our docker image for building robot code
- `./gradlew check`

We use azure but I can see how GitHub actions are easier for teams.
