### ISSUE TITLE
Build example code

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#59]
We should build all of the code examples so that when something changes in WPILib, we know that the documentation needs to be updated.  What is the best way to do this?  Could we use the samples directory already in allwpilib and then as part of the build bring allwpilib in?  I really have no idea what is best to do.

**Comment by AustinShalit** [comment]
Seems like we could use `literalinclude`?

**Comment by Daltz333** [comment]
Looking at https://www.sphinx-doc.org/en/1.5/markup/code.html#includes. We could probably include a clone in the conf.py file to clone it into the config directory and then use the subsequent linking. I don't know how fast this may be tho.

**Comment by Daltz333** [comment]
Closed in favor of issue #163 which details how to make them testable.
