### ISSUE TITLE
Add docs on advanced WPILib functions

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/frc-docs#611]
Add docs on the different Filters, etc. in wpilib. Maybe add docs on advanced geometry/trajectory/kinematics usage (the docs on these are great to start and have working code, but I think the library has a much higher potential than many teams use and know how to use. 
Adding docs on more wpilib classes would increase usage of them, and help lower/medium-level teams have higher-level programming. This is less critical for high-level teams, as most of them have an extensive library of their own for more advanced features, and the advanced features that have been added to WPILib should be documented so that lower-level teams would be able to use them effectively. It will also help teams save time, since there is less of a chance that teams will be writing features because they don't know they exist in WPILib if those features are documented.

**Comment by calcmogul** [comment]
Filter docs:
https://docs.wpilib.org/en/stable/docs/software/advanced-control/filters/index.html

Kinematics docs:
https://docs.wpilib.org/en/stable/docs/software/kinematics-and-odometry/

Trajectory docs:
https://docs.wpilib.org/en/stable/docs/software/examples-tutorials/trajectory-tutorial/index.html
https://docs.wpilib.org/en/stable/docs/software/advanced-control/trajectories/trajectory-generation.html

**Comment by Starlight220** [comment]
Ok, thanks!
