### ISSUE TITLE
Adjust PID widget docs to new PIDController

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/frc-docs#612]
kind of self-explanatory.
Mainly remove the part with `enable`, as the controller output needs to be called periodically by the team.

**Comment by calcmogul** [comment]
Could you link to where in the docs that is?

**Comment by Starlight220** [comment]
[here](https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/shuffleboard/advanced-usage/shuffleboard-tuning-pid.html)

**Comment by Daltz333** [comment]
This would require a widget update for Shuffleboard to use the new PIDController.

**Comment by Starlight220** [comment]
I assume so, I created an issue about it there too.
