### ISSUE TITLE
Picture of FTC bot as example of mecanum

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/frc-docs#615]
[here](https://docs.wpilib.org/en/stable/docs/software/actuators/wpi-drive-classes.html#mecanum-drive)

**Comment by PeterJohnson** [comment]
That’s not a FTC bot, it has a cRio on it.  It was probably a demonstration robot.  What’s the concern?

**Comment by AustinShalit** [comment]
That is GearsBot v2 🙂 https://github.com/wpilibsuite/allwpilib/tree/master/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot
