### ISSUE TITLE
Odd Diagrams in Git Version Control Introduction

### ISSUE THREAD

**Issue by yellowjaguar5** [wpilibsuite/frc-docs#622]
The same diagram is currently shown in the [Branches section](https://docs.wpilib.org/en/latest/docs/software/basic-programming/git-getting-started.html#branches) and [Merging section](https://docs.wpilib.org/en/latest/docs/software/basic-programming/git-getting-started.html#merging). Is this intentional? What should be show differently (if anything) in the second diagram?

---

![image](https://user-images.githubusercontent.com/15172054/79419490-c0bc1000-7f6b-11ea-8fc0-656dc499f1de.png)

**Comment by ItayZiv** [comment]
It seems like it's on purpose, the merge section simply talks about how merging different branches looks like, and what happens when merge conflicts happen.
However, the diagram itself seems to lack actually showing the merge, it seems like FeatureB should be merging into Feature A by the wording of the text surrounding both uses of the diagram.
Personally I don't think its the worst idea to just redo the diagram, so the first one shows branches and a merge, and the second one shows just a merge, such that the text below it, still can be accurate (the merge conflict makes sense)

**Comment by AustinShalit** [comment]
This is an idea of what it could look like:

![image](https://user-images.githubusercontent.com/3799260/79473948-ad846100-7fba-11ea-8b23-b2b9f3882bb7.png)

**Comment by yellowjaguar5** [comment]
Sounds good, thanks for your input @ItayZiv and @AustinShalit. I'll add a merge step to both diagrams and try to clarify the second to emphasize the merge. Does this look okay?

---
1st diagram: 
![image](https://user-images.githubusercontent.com/15172054/79475936-356b6a80-7fbd-11ea-9f0e-9551ad973c2b.png)


2nd diagram: 
![image](https://user-images.githubusercontent.com/15172054/79476604-0bff0e80-7fbe-11ea-9037-44de67efc64a.png)

**Comment by AustinShalit** [comment]
Maybe rename Feature A to be "master"?

**Comment by AustinShalit** [comment]
I think the Example Repo at the top does not make sense because all of this is contained within the example repo rather than under it. Any ideas to make that clearer?

**Comment by yellowjaguar5** [comment]
What do you think about this @AustinShalit? I'm curious if there's a better name for `Remote Git Server`?
![image](https://user-images.githubusercontent.com/15172054/79479388-8aa97b00-7fc1-11ea-9370-dcc105cd803c.png)

**Comment by AustinShalit** [comment]
I guess the issue is that it does not look like every other git diagram out there. Here are examples:


![](https://git-scm.com/book/en/v2/images/advance-master.png)
![](https://www.nobledesktop.com/image/gitresources/git-branches-merge.png)

![](https://gitbookdown.site/img/git_branch_merge.png)

**Comment by AustinShalit** [comment]
Thinking more about it... maybe it is because branches and the repos are first class objects in the diagram. That is not how git works which is why all of the other diagrams do not represent git this way.

**Comment by yellowjaguar5** [comment]
How about this?
![image](https://user-images.githubusercontent.com/15172054/79503176-91e28000-7fe5-11ea-97dd-9f9b1ef20b71.png)

**Comment by AustinShalit** [comment]
I think that this is a more accurate depiction of branches and commits 👍

**Comment by yellowjaguar5** [comment]
Great, I'll go ahead and adapt the wording of the article to this diagram. Thanks for your help!

**Comment by yellowjaguar5** [comment]
Okay, one more draft @AustinShalit 

Branches:
![image](https://user-images.githubusercontent.com/15172054/79511870-fbb65600-7ff4-11ea-85e7-9fb1801c8457.png)

Merge Conflicts:
![image](https://user-images.githubusercontent.com/15172054/79511909-17b9f780-7ff5-11ea-801f-04c184843b21.png)
