### ISSUE TITLE
Add relay description to actuator overview

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#626]
https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/software/actuators/overview.rst

This page contains a brief description of motor controllers and pneumatics but nothing for relays. We should add something short and sweet describing their use.

**Comment by jasondaming** [comment]
@Daltz333 I don't know when this was solved but it looks like there is relay info here now:
https://docs.wpilib.org/en/latest/docs/software/actuators/overview.html
