### ISSUE TITLE
Add docs about non-VSCode vendor utility

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/frc-docs#633]
[Here](https://docs.wpilib.org/en/latest/docs/software/wpilib-overview/3rd-party-libraries.html#the-mechanism-c-java) it is stated that if you are not using VSCode, you need to create the vendordeps folder, etc. However, there is no documentation of the external vendordeps tool (`wpilibutility.exe`).

I will also create an issue in the allwpilib repo for perhaps creating a gradle task for vendordeps, but either way the external tool should be documented.

**Comment by Daltz333** [comment]
Closing for same reasons of https://github.com/wpilibsuite/allwpilib/issues/2492
