### ISSUE TITLE
Document handling strings in wpilibc

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/frc-docs#664]
If there is already documentation on this, please link to it. 
I didn't see any, but I might have missed it.

**Comment by AustinShalit** [comment]
What do you mean?

**Comment by Starlight220** [comment]
There are many c++ wpi classes for handling strings (StringRef, SmallString, etc...). There should be docs about them.

**Comment by AustinShalit** [comment]
Those are classes brought in from LLVM. I think the doxygen information is sufficient here unless we can identify exactly what information about them we want to include in the frc-docs.

**Comment by Daltz333** [comment]
@Starlight220 Are you fine with closing this issue? We can add links to the doxygen to a couple places but I'm not sure we should extend maintenance to documenting LLVM classes.

**Comment by Starlight220** [comment]
I'll be direct - the reason I opened this issue is that I had a PR in allwpilib that dabbled in C++ string handling. I mainly use Java, I am not very good with C++. I mimicked what was done somewhere else in the library, but I was lost between the different String-like types: when do I use each of `StringRef`/`SmallString`/I don't even know what else? If these classes are included in wpilibc (regardless of whether they are wpi-originated or external), frc-docs should document them. Full, deep detailing is unnecessary, but a basic overview of what, when, and how these classes should be used should be included or at least linked to (if an external/LLVM overview exists, and is enough for teams/wpilib contributors to understand what to use when). 
A whole guide for contributing to WPILib in advanced subjects (JNI, running stuff like NT in sim for tests, etc.) should also be created, but that's a different issue, and should probably be in allwpilib and not frc-docs.

**Comment by ItayZiv** [comment]
Id say a separate issue on documenting advanced usages for contributing is something that might be worth and definability should be a issue here (along with a possible transition of contributing.md from allwpilib to be in the docs as well)

**Comment by Daltz333** [comment]
I will bring this up again in the next WPILib meeting. There has been some disagreement between splitting contributing docs into frc-docs and not their respective readmes.

**Comment by Starlight220** [comment]
Thanks! If my opinion counts for anything, I think each repo should have its contributing docs included. I don't really care if it's in Readmes or wikis or something else, but it needs to be accessible. GitHub renders Readmes relatively well, I think it can stay that way. Each repo should have a `/contributing/` folder at root with the contributing docs, as I think the contributing guidelines for each repo are different. However, the contributing guides should definitely be linked to from frc-docs. I can try to help writing these guides, but I will probably need help with some technical details. 
I also opened wpilibsuite/allwpilib#2524 for this, as that is the main issue. I suggest we move this discussion there.
