### ISSUE TITLE
Add translation instructions for PR authors

### ISSUE THREAD

**Issue by prateekma** [wpilibsuite/frc-docs#667]
See https://github.com/wpilibsuite/frc-docs/pull/665#issuecomment-626313993
Ideally, these instructions would also be included in a file inside the main repository itself and not just the docs.wpilib.org website.

**Comment by Daltz333** [comment]
Yep, forgot to add to the readme. You're also welcome to go ahead and add it. It's only necessary on rst additions and moving rst files around.
