### ISSUE TITLE
Add shuffleboard to troubleshooting dashboard connectivity

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#680]
https://docs.wpilib.org/en/stable/docs/software/driverstation/troubleshooting-dashboard-connectivity.html

**Comment by yellowjaguar5** [comment]
Would it be appropriate to use the suggestions for SmartDashboard currently found on that page, but with screenshots from Shuffleboard? Or, are there different tips for troubleshooting the connectivity of Shuffleboard?

**Comment by AustinShalit** [comment]
I think a screenshot of the connection indicator at the bottom might be nice also with repeating some of the information from the other sections.
