### ISSUE TITLE
Set standards on WPI supported hardware documentation

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#69]
It needs to be decided on what documentation in terms of hardware is allowed. I can understand a vendor bias needs to be avoided as much as possible, but this may limit available docs for some commonly used equipment. Also, details regarding allowed images would be fantastic.

The current approach is, KOP equipment only (apart from conflicting documentation of third-party equipment that was on screensteps???).

As for images, any images taken locally or part of Creative Commons. 

@Kevin-OConnor

**Comment by AustinShalit** [comment]
For now, let’s stay with the status quo and maintain what hardware was on screensteps.

**Comment by Kevin-OConnor** [comment]
What do you mean by "conflicting documentation of third-party equipment that was on screensteps"?

**Comment by Daltz333** [comment]
In specific, the "third-party devices" article.

**Comment by Kevin-OConnor** [comment]
This one? https://wpilib.screenstepslive.com/s/currentCS/m/cpp/l/1035723-3rd-party-libraries

**Comment by Daltz333** [comment]
Correct.

**Comment by Daltz333** [comment]
After much internal discussion, it was determined to limit documentation to existing KOP materials. However, this discussion is still ongoing and may be expanded in the future, this is unlikely for the 2020 season.
