### ISSUE TITLE
PIDSubsystem Clairifcation

### ISSUE THREAD

**Issue by TechplexEngineer** [wpilibsuite/frc-docs#73]
In the article: https://frc-docs.readthedocs.io/en/develop/docs/software/commandbased/pid-subsystems-commands.html#using-a-pidsubsystem

The class with signature `public class ShooterSubsystem extends SynchronousPIDSubsystem` does not have a member m_shooter as referenced in the sample below the class, reporduced here:
```Java
// Spin up the shooter when the 'A' button is pressed
driverController.getButton(Button.kA.value)
    .whenPressed(new InstantCommand(m_shooter::enable, m_shooter));
```

What is m_shooter and where does enable come from?

**Comment by Daltz333** [comment]
This includes docs for the command-based rewrite which has not been merged. This does not apply to current command-based.

**Comment by Kevin-OConnor** [comment]
That doesn't answer the question of what m_shooter refers to in the provided example code. It looks like it is probably an instance of a ShooterSubsystem, but this is not clear from the current doc.

**Comment by Daltz333** [comment]
@oblarg

**Comment by Oblarg** [comment]
The finished docs will link to the corresponding example projects in the wpilib examples repo (they're already written) where readers can view the full code.  Putting full classes in the docs is clunky and takes up tons of space.
