### ISSUE TITLE
rsvg-convert error when running make html on Windows

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#732]
Tracking https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter/issues/8
Was hoping to use CairoSVG, but it has enormous dependencies for Windows that just aren't feasible.

**Comment by Daltz333** [comment]
For now, you can just ignore it.

**Comment by ItayZiv** [comment]
Btw a note for making translations on windows (removing `|| /b`) would be useful (or actually removing that until sphinx update)

**Comment by Daltz333** [comment]
It only fixes the problem in builders such as gettext and linkcheck, it still runs in the HTML builder.

**Comment by TheTripleV** [comment]
Update from discord conversation:

rsvg-convert is available on Windows from various sources:
#### 1. https://opensourcepack.blogspot.com/2012/06/rsvg-convert-svg-image-conversion-tool.html
This is the rsvg-convert distribution available in choco.

#### 2. https://github.com/miyako/console-rsvg-convert
This is a clone of rsvg-convert.

Both work on Windows.
