### ISSUE TITLE
Refactor Structure

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/frc-docs#757]
Discussion of changes got a bit off-topic in #726 and went to general changes that are not directly connected to the "Getting Started" rewrite. So the discussion of article refactoring can be done here. I'll start a checklist of changes/refactorings that should be done, and any additions are welcome - add a comment and me or one of the maintainers (probably @Daltz333) will add it to the checklist.

- [ ] Transformation of the "Getting Started" section into a more concrete and streamlined "0-to-Robot" tutorial (discussion in #726)
- [ ] Split "FRC Control System Hardware Overview" into more focused articles about each category
- [ ] Add Actuator article in Hardware
- [ ] Split "FRC Software Component Overview", with each tool explained where it's used (i.e. go over the Imaging Tool in the "Imaging your roboRIO" section)
- [ ] Split Java+Cpp/LV articles (i.e. [FRC Software Component Overview](https://docs.wpilib.org/en/stable/docs/getting-started/getting-started-frc-control-system/control-system-software.html))
- [ ] Should [Updating and Configuring Pneumatics Control Module and Power Distribution Panel](https://docs.wpilib.org/en/stable/docs/getting-started/getting-started-frc-control-system/updating-and-configuring-pneumatics-control-moduleand-power-distribution-panel.html) be a whole article? I would split/refactor this to the PDP/PCM overview.

Some topics that need articles written, and structure is relevant (note that some of these have their own GH issues): 
- [ ] Machine Learning 
- [ ] Relays 
- [ ] Reorganize pneumatics section, including pressure sensors and compressor switch API (started with #760)

As there are many issues with the "FRC Software Component Overview" article. Each tool should be split somewhere else. Some work is being done for this in #604. Here's a quick overview of my suggestions:
- [ ] Radio Config Utility -> Networking section 
- [ ] roboRIO Imaging Tool -> "Imaging Your roboRIO"
- [ ] [LabVIEW](https://docs.wpilib.org/en/stable/docs/getting-started/getting-started-frc-control-system/control-system-software.html#labview-frc-windows-only), [Simulator](https://docs.wpilib.org/en/stable/docs/getting-started/getting-started-frc-control-system/control-system-software.html#frc-robot-simulator-windows-only), maybe [LV Dashboard](https://docs.wpilib.org/en/stable/docs/getting-started/getting-started-frc-control-system/control-system-software.html#frc-labview-dashboard-windows-only) too -> LabVIEW Components (new article, or work into the existing LV docs)
- [ ] Axis Camera Setup -> [Configuring an Axis Camera
](https://docs.wpilib.org/en/stable/docs/software/vision-processing/introduction/configuring-an-axis-camera.html#configuring-an-axis-camera)
- [ ] DS, all of the dashboards -> perhaps a new "Operator Interface"/"Driver Station" article?
- [ ] VSCode, RobotBuilder -> Software Components (C++/Java) with more emphasis on each, maybe merge with [VSC basics](https://docs.wpilib.org/en/stable/docs/software/wpilib-overview/vscode-basics.html#visual-studio-code-basics-and-the-wpilib-extension)

**Comment by Daltz333** [comment]
Please note that any hardware changes requires FIRST approval beforehand.

**Comment by Starlight220** [comment]
WDYM "hardware changes"?

**Comment by Starlight220** [comment]
I'm adding some stuff from other issues into the checklist, as they are relevant

**Comment by Daltz333** [comment]
Any hardware article additions or major changes need FIRST approval.

**Comment by Starlight220** [comment]
I'm starting to work on some of the smaller changes above, and submit a PR for each one. If there are some issues that are problematic/should be handled differently, please let me know before I spend too much time on them.

**Comment by Starlight220** [comment]
What software components are relevant only to LV, or not relevant to LV at all?
I assume VSCode and RobotBuilder fall under the second category; while Robot Simulator, LV FRC, and maybe the LV dashboard fall under the first. Anything else?

**Comment by Daltz333** [comment]
Basically.

**Comment by sciencewhiz** [comment]
LV Dashboard is interopable with C++/Java robot code and smartdashboard/shuffleboard work with LabVIEW robot. They are not the most common, but are supported (my team ran LabVIEW dashboard with Java robot for several years).

**Comment by Starlight220** [comment]
So how do you propose we divide the components? Or perhaps all dashboards should be split into a separate article?

**Comment by Daltz333** [comment]
I've been a big fan of per-topic structure for a long time.

**Comment by jasondaming** [comment]
I think this issue should probably be closed in favor of a bunch of the other restructure issues that are more up to date.
