### ISSUE TITLE
Custom Extension: Add extension to grab top transifex contributors per language

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#762]
Requested by @redrield from Discord

Will need to have a custom extension to grab top contributors from either transifex or github

**Comment by AustinShalit** [comment]
From the Transifex API: https://docs.transifex.com/api-2-5/reports

>The Reports endpoint is only available on the Enterprise plan.

You'll probably need to parse the PO files. All of the translators are listed in the comments.
