### ISSUE TITLE
Known Issue: Garbled DS log messages

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#776]
https://www.chiefdelphi.com/t/ds-log/386547

**Comment by ItayZiv** [comment]
Is this a docs issue? Or is the issue to document the garbled log messages.
I believe it’s caused if windows is set to a language that isn’t English, this happens to quite a few teams here in Israel when their computers were set to Hebrew

**Comment by Daltz333** [comment]
There is a known issues article

**Comment by AustinShalit** [comment]
Sorry... I was typing fast because I didn't want to forget. The issue should be added to the known issues page with the resolution steps Joe provided.

**Comment by ItayZiv** [comment]
That is a iffy solution tho, you can fix it by changing the language of the computer iirc.

**Comment by sciencewhiz** [comment]
My understanding is that it occurs regardless of the language setting of the computer and it's a bug related to UTF-8 text being interpreted as UTF-16 by the log viewer. 

Can you confirm that switching languages fixed it for you?

**Comment by ItayZiv** [comment]
I haven't had this problem myself, I have heard from other teams here, for now, its fine to add the solution in the CD post, when I can ill check when I can...

**Comment by sciencewhiz** [comment]
I heard from someone else that switching to English-American fixed it, although it must not be well know, since no one has posted it in the linked thread. 

Since changing the language is more intrusive, I think both changing the language and copy and paste into notepad should be included in the known issue.

**Comment by ItayZiv** [comment]
I think for now its fine to add the copy paste to notepad, then possibly leave this issue open until the other solution is actually checked (I can try do it at some point)
