### ISSUE TITLE
How to grab the current git commit in Java?

### ISSUE THREAD

**Issue by carlosgj** [wpilibsuite/frc-docs#783]
I'd like to be able to log the git commit ID of the code running on the robot, to make analysis of past data easier. [Here's](https://stackoverflow.com/questions/6526451/how-to-include-git-commit-number-into-a-c-executable) a post detailing how to do it with make in C. I'm thinking perhaps a compile-time-generated file in src/main/resources for Java. If possible, it would also be nice to indicate if there were uncommitted changes to the repo when the code was compiled: <commit>-CLEAN vs. <commit>-DIRTY, for example. 

Since not everyone uses git, it would need to fail gracefully if the code isn't in a repo.

**Comment by Starlight220** [comment]
What do we want to explain here? 
Gradle 101?
Is this supposed to be some sort of tutorial to help teams implement this the way they want?
> better practices in gradle and how to do things like this right.

What better practices? How to do _what_ things right - write a gradle task? Handle dependencies?

A short tutorial on gradle is a good idea and can include some stuff like custom tasks, how to properly declare dependencies, etc. 
Including docs on gradleRIO tasks (other than `build`/`deploy`) is also a good idea.
Having a compile-time file with some build metadata is an idea that can be implemented. 

However, having a task type with support for adding/retrieving files from the RIO is something that can be helpful in gradleRIO.

**Comment by Starlight220** [comment]
So we want a gradle tutorial about:
- [ ] Declaring dependencies/repositories
- [ ] Creating custom tasks?
- [ ] Using tasks
- Anything else?

**Comment by AustinShalit** [comment]
I am not sure if we want a complete Gradle tutorial. The Gradle docs are awesome and I am not sure we can do better. The solution to this issue might be to just post the appropriate Gradle snip-it here.

**Comment by Starlight220** [comment]
Then what do we want? That's what I'm trying to understand from the second I saw this issue, and I didn't get an answer. 

>>> This isn't something fantastic to be built into GradleRIO, because teams would always want something slightly different.

So @ThadHouse - I have an idea: we can have a team-defined task for creating a logfile that would be readable from the Driver Station. A task type can be built into GradleRIO to provide teams with a neater syntax/API. A default impl can be in the template `build.gradle`, and teams that want something else can provide their own impl. It might be possible to log build metadata in said file, resolving _that_ issue. 
I might be able to work on this myself if I would be given some design insight and a green light.

**Comment by Starlight220** [comment]
@carlosgj have you seen [this](https://stackoverflow.com/questions/28498688/gradle-script-to-autoversion-and-include-the-commit-hash-in-android) StackOverflow page? The first answer also contains a link to another page with a similar question.

**Comment by jasondaming** [comment]
Not sure this is a general issue affecting enough people to warrant a new article is it?

**Comment by Daltz333** [comment]
This issue is marked as support. I think just answering the OPs question is good enough.

**Comment by jasondaming** [comment]
So do we want to close this then?
