### ISSUE TITLE
Only check links on git-diffs

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#789]
Option 1: Write our own linkchecker (can't use docutils unfortunately since we're doing diffs)
Option 2: https://github.com/sphinx-doc/sphinx/issues/8046

**Comment by AustinShalit** [comment]
I think I would even take something that didn't read the links themselves but only checked the changed files.

**Comment by TheTripleV** [comment]
I got this working locally as written by Austin's comment. Only changed files are checked.

Checking for links is a bit more involved.

**Comment by TheTripleV** [comment]
Link: https://github.com/TheTripleV/sphinxext-linkcheckdiff
