### ISSUE TITLE
Add [Deprecated] Command-Based docs

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#79]
Still supported, albeit deprecated. I'll end up doing this in the next few days or so.

**Comment by AustinShalit** [comment]
Just to clarify, the current method of doing command based robots is not deprecated.

**Comment by Daltz333** [comment]
@calcmogul In discussion with Tyler, he said that it would be deprecated for 2020 and removed for 2021 upon merge of the rewrite.

**Comment by calcmogul** [comment]
Removal in 2022 or 2023 is also possible depending on how slow we think people will migrate.
