### ISSUE TITLE
Hall Effect sensor wiring backwards

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#809]
In https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/hardware/sensors/images/proximity-switches-hardware/hall-effect-sensor-to-roborio.svg the ground on the sensor goes to signal on the roborio, and vice versa.

**Comment by Daltz333** [comment]
@yellowjaguar5

**Comment by yellowjaguar5** [comment]
Thanks for the ping. School is just starting for me, so I have very little time for side projects. I hope to address it in the next two weeks. Future folks who stumble across this, feel free to ping me again if I don't get to it in a timely manner.
