### ISSUE TITLE
DS spacebar & enter key functionality

### ISSUE THREAD

**Issue by nlaverdure** [wpilibsuite/frc-docs#814]
The section "Driver Station Key Shortcuts" [1] doesn't warn the reader that when the DS is connected to FMS, enter and spacebar keypresses are ignored, and do not disable or e-stop the robot. [2][3]  When safety controls violate UI design best practices (e.g. by being mode-dependent and therefore non-habituating) [4] this is especially important to document.

Suggestion:
_Note: When connected to FMS during a match, teams must press the E-stop button in the Player Station to emergency stop their robot, as the enter and spacebar keys are ignored by the FMS._

[1] https://docs.wpilib.org/en/stable/docs/software/driverstation/driver-station.html#driver-station-key-shortcuts
[2] https://www.chiefdelphi.com/t/driver-station-ghost-estop/157662/28
[3]
![image](https://user-images.githubusercontent.com/41549690/91463640-a2d7b380-e859-11ea-8043-1d38310ba0e3.png)
[4] http://nitpicker.pbworks.com/w/page/12451253/The%2520Humane%2520Interface

**Comment by Starlight220** [comment]
I assume that with FMS connected, enable/disable and eStop functionalities don't work, and the only shortcut documented is F1 for joystick refresh (and that does work)?
Just to clear up. I'll take care of this soon.

**Comment by Daltz333** [comment]
Correct. I can confirm joystick refresh does still work.
