### ISSUE TITLE
Add Sphinx Extension for the "latest" version declaring not stable.

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#828]
We don't need to create this ourselves, as it exists somewhere. I just cannot remember what it's called but I believe it's published by a maintainer of RTD. Should be a fairly easy issue.

**Comment by TheTripleV** [comment]
This? https://sphinx-version-warning.readthedocs.io/

**Comment by prateekma** [comment]
Will this not suffice? https://docs.readthedocs.io/en/stable/versions.html#version-warning

**Comment by Daltz333** [comment]
@prateekma that will not apply to "stable" or "latest" only old versioned tags.

**Comment by AustinShalit** [comment]
Maybe we can also do the same thing if someone is looking at a previous year's documentation?

**Comment by TheTripleV** [comment]
There are 2 ui options (https://sphinx-version-warning.readthedocs.io/en/latest/who-is-using-it.html):
1. A sphinx admonition
2. A banner (like the Python docs)

**Comment by Daltz333** [comment]
@AustinShalit that automatically happens right nw

**Comment by Daltz333** [comment]
Personally I'd have to see the banner on the docs before I'd make a decision.
