### ISSUE TITLE
Awkward language on wiring page

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#829]
https://docs.wpilib.org/en/stable/docs/getting-started/getting-started-frc-control-system/how-to-wire-a-robot.html#layout-the-core-control-system-components

>Layout the components on the board. One layout that should work is shown in the images/how-to-wire-a-robot above.

"images/how-to-wire-a-robot" is weird maybe we can be clearer.

**Comment by Daltz333** [comment]
Can probably just get renamed to "Go ahead and layout the components on the board. An example layout is shown in the image above."
