### ISSUE TITLE
Does the Driver Station subnet mask actually have to be 255.0.0.0?

### ISSUE THREAD

**Issue by JonathanLindsey** [wpilibsuite/frc-docs#837]
The [IP Configurations - On the Field Static Configuration](https://docs.wpilib.org/en/latest/docs/networking/networking-introduction/ip-configurations.html#on-the-field-static-configuration) section states:
>Driver Station - Static `10.TE.AM.5` would be a reasonable choice, subnet mask **must** be `255.0.0.0`

For the roboRIO, IP camera, and other devices it less strongly recommends the subnet mask of 255.255.255.0.

Why **must** the driver station have the 255.0.0.0 subnet mask?

I seems my team has used a static 255.255.255.0 subnet mask without issue. Additionally, I noticed another team's driver station in 2019 had a dynamically assigned 255.255.255.0 subnet mask while connected to the field and it was working. Here's a picture.
![IMG_20190315_130435](https://user-images.githubusercontent.com/18510187/93724053-77e73380-fb69-11ea-9c3f-3cd3f258d05b.jpg)
*The picture has been sitting on my phone, unlabeled for over a year so please don't completely trust that I remembered everything correctly. Test it to make sure.*

Note: The subnet recommendations may be changing soon because of #372 but I think it would still be wise to understand this.

**Comment by PeterJohnson** [comment]
Yes, it has to have a 255.0.0.0 netmask to talk to the FMS, which is at a 10.0.0.X IP.

**Comment by ThadHouse** [comment]
If you don't have a gateway set, you need 255.0.0.0. If a gateway is set, which iirc can either be 10.0.100.1 or 10.te.ea.4, and the gateway will forward correctly. But usually it's easier to set the less restrictive netmask rather then the full netmask, and then requiring the gateway to be correct.

**Comment by PeterJohnson** [comment]
A gateway of 10.0.100.1 won't work with a 255.255.255.0 netmask.  If the 10.TE.AM.4 actually works as a gateway, that will work.  But yes, it's much better to just use the wider netmask--there is no downside to it.

**Comment by JonathanLindsey** [comment]
Now it's making since. For a while I was trying to figure out why you were referring to 10.0.100.5 AND 10.0.100.1. It's that the driver station needs to talk to the FMS Server at 10.0.100.5 but the path the data needs to take is 10.te.am.4 (the primary Ethernet switch in the SCC or the Score Switch?) -> 10.0.100.1 (the Field Router) -> 10.0.100.5 (the FMS Server) right? [This](https://wpilib.screenstepslive.com/s/fms/m/whitepaper/l/608744-fms-whitepaper#field-network) shows a good diagram but lacks the IP addresses.

[Off-Season FMS Computer Configuration](https://wpilib.screenstepslive.com/s/fms/m/offseason/l/589540-fms-computer-configuration). The top screenshot (if it doesn't render, click Network Adapter) shows that the Off-Season FMS computer/[server?] has a subnet mask of 255.0.0.0 which means it should be able to communicate with the driver stations even if they have 255.255.255.0 subnet masks and no default gateway right?

Can we infer the official FMS server has a 255.255.255.0 subnet mask?

I know about the FMS Documentation at https://wpilib.screenstepslive.com/s/fms but the only place I see that specifies IP addresses is the Off-Season FMS documentation there which does not use the official FMS hardware. I take it there may be differences between the Off-Season and official FMS systems. Is there someplace publicly accessible I haven't looked that documents the 10.0.100.x addresses and official FMS better?

**Comment by ThadHouse** [comment]
The IP addresses that are accessible on the FMS are not documented, mainly so in the future they could change if necessary. As long as the DS and FMS agree, things will work. For documentation, saying 10.0.100.x must be reachable either via a gateway or a 255.0.0.0 subnet mask is fine, and doesn't lock things down for the future (Currently when we hit >25599 teams the networking setup will have to be changed at least somewhat)

 Official FMS probably has a 255.0.0.0 subnet because of the VPN's.

**Comment by PeterJohnson** [comment]
If the driver station has a netmask of 255.255.255.0 and does not have a gateway set, it will be unable to communicate with the FMS.

**Comment by Kevin-OConnor** [comment]
> [Off-Season FMS Computer Configuration](https://wpilib.screenstepslive.com/s/fms/m/offseason/l/589540-fms-computer-configuration). The top screenshot (if it doesn't render, click Network Adapter) shows that the Off-Season FMS computer/[server?] has a subnet mask of 255.0.0.0 which means it should be able to communicate with the driver stations even if they have 255.255.255.0 subnet masks and no default gateway right?

In this scenario the FMS could talk to the DS but the DS couldn't talk back (and may reject the incoming FMS packets too, I forget how Windows handles this)

> Can we infer the official FMS server has a 255.255.255.0 subnet mask?
I don't recall how the FMS server adapter is set but it shouldn't matter.

> I know about the FMS Documentation at https://wpilib.screenstepslive.com/s/fms but the only place I see that specifies IP addresses is the Off-Season FMS documentation there which does not use the official FMS hardware. I take it there may be differences between the Off-Season and official FMS systems. Is there someplace publicly accessible I haven't looked that documents the 10.0.100.x addresses and official FMS better?

Probably not. Is there some reason that this matters to teams?

**Comment by Daltz333** [comment]
@JonathanLindsey Are your concerns answered adequately? Can I close this issue?

**Comment by AustinShalit** [comment]
Please reopen if you have additional questions or feedback.
