### ISSUE TITLE
Change "master" to "main" terminology where applicable

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#838]
In cases where "master" is technically accurate (IE in cases of object and class names), prefer it.

**Comment by prateekma** [comment]
Pretty much all occurrences of "master" are from articles related to GitHub or come from GitHub links to allwpilib code. There were only two occurrences where the usage didn't fall into the two categories above:

 * https://github.com/wpilibsuite/frc-docs/blob/master/source/conf.py on L104 (can reword this comment)
 * https://github.com/wpilibsuite/frc-docs/blob/master/source/index.rst on L1 (can reword this comment)

We can change all the GitHub articles to use `main` once `main` is the default branch on GitHub.

**Comment by sciencewhiz** [comment]
Fixed by #907
