### ISSUE TITLE
Missing parentheses

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#841]
>../../frc-docs/source/docs/getting-started/getting-started-frc-control-system/control-system-software.rst:102

>OutlineViewer is a utility used to view, modify and add to the contents of the NetworkTables for debugging purposes. It displays all key value pairs currently in the NetworkTables and can be used to modify the value of existing keys or add new keys to the table. OutlineViewer is included in the C++ and Java language updates (found in ``\tools\wpilib``. Teams may need to install the Java Runtime Environment to use the OutlineViewer on computers not set up for Java programming.

>( is missing in the orginal text)

Hasan Bilgin

**Comment by Saif807380** [comment]
Can I go ahead and fix it?

**Comment by AustinShalit** [comment]
> Can I go ahead and fix it?
Sure
