### ISSUE TITLE
Metric Units

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#844]
Many of the translation teams have commented that it would help teams around the world to have metric equivalents of sizes in the documentation.

**Comment by Kevin-OConnor** [comment]
I assume this is referring to any sizes we might have in FRC docs? I can't imagine there are many dimensions in the documentation. We should definitely update them to include metric equivalents.

**Comment by Starlight220** [comment]
Would it be enough to pop the sizes into an inch->meter converter and round, or is something more advanced needed?

**Comment by Starlight220** [comment]
A search of `inches` in frc-docs shows these results:
- > Identifying and Processing the Targets
Coverage Area
... The area of the retroreflective strips is 80 square **inches**. ...

- > Differential Drive Kinematics
Converting Chassis Speeds to Wheel Speeds
... Java C++ // Creating my kinematics object: track width of 27 **inches** DifferentialDriveKinematics kinematics ...
Converting Wheel Speeds to Chassis Speeds
... Java C++ // Creating my kinematics object: track width of 27 **inches** DifferentialDriveKinematics kinematics ...

- > Camera Settings
Resolution
... The tape used on the target is 4 **inches** wide, and for good processing, you will want that 4 **inch** feature ...

- > Adding field images to PathWeaver
JSON Format
... The field units are case-insensitive and can be in meters, cm, mm, **inches**, feet, yards, or miles. ...

- > Ultrasonics - Software
Using ultrasonics in code
... example, the following code will drive the robot forward until the ultrasonic measures a distance of 12 **inches** ...

The PathWeaver usage shouldn't be changed as it specifies `inches` as an option for the tool units (alongside meters and others). 
I'm not sure how much specifying metric equivalents would help when it's an example target/setpoint for PID etc.
The vision target usage should definitely be added.

**Comment by Daltz333** [comment]
This issue was opened in response to the translation team noting that the hardware documentation in particular uses imperial (wire gauges, robot part dimensions, etc).
