### ISSUE TITLE
File extension formatting

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#848]
I was recently sent a message on this line in the docs:

> ../../frc-docs/source/docs/getting-started/getting-started-frc-control-system/wpilib-setup.rst:209

> Download the Linux .deb file from....

asking about the formatting of the file extension in that line. Talking with the team, I see 4 options:

- .deb
- `.deb`
- ".deb"
- "`.deb`"

Just opening this for tracking.

**Comment by Daltz333** [comment]
+1 for option 2

**Comment by AustinShalit** [comment]
It was decided that option 2: `.deb` is the right answer. If someone could go look for all the file extension and update ❤️

**Comment by sciencewhiz** [comment]
Add to styleguide?
