### ISSUE TITLE
Add Github Action to push "main" changes to "stable" during competition season.

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#853]
Any changes pushed to "main" branch should be automatically pushed to "stable".

- This branch will be created right before kickoff
- It should only get pushed to from Jan 1 to end of competition season (COVID changes this date)

**Comment by Starlight220** [comment]
is "stable" simply a git tag that should simply be moved, or something else?

**Comment by Daltz333** [comment]
A branch called stable.

**Comment by Starlight220** [comment]
so we basically want to merge/squash/'add the commits' of `main` into `stable`?

**Comment by Daltz333** [comment]
A merge, yes. We do *not* want to squash. We want to keep history linear.

"PR created points toward master" -> Github actions pushes commit to "stable" branch

**Comment by Starlight220** [comment]
Ok, I can work on that!

**Comment by Starlight220** [comment]
Why not cherry-pick?

**Comment by Daltz333** [comment]
I'm confused, what do you need to cherry pick. It should just be a simple ``git checkout stable, git merge master, git push``

**Comment by Daltz333** [comment]
Individually will not *ever* commit directly to stable.

**Comment by Starlight220** [comment]
oh ok. Should I first checkout `main`, or checkout `stable` from the beginning? And I'm using actions/checkout for all checkouts
