### ISSUE TITLE
sync readme.md and contributing docs

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#868]

**Comment by Daltz333** [comment]
-1 to this. It adds a lot of unnecessary work with little gain. We lose a lot of necessary formatting by converting to markdown, and duplicating for the sake of duplicating isn't very useful.

**Comment by Daltz333** [comment]
An example of this would be the RobotPy development section, or any other docs on readthedocs
- https://robotpy.readthedocs.io/en/stable/dev/index.html
