### ISSUE TITLE
Gain definition in State Space Glossary incorrect

### ISSUE THREAD

**Issue by RegisBKL** [wpilibsuite/frc-docs#869]
There's an error in the documentation regarding the advanced controls state space, see link: 
https://docs.wpilib.org/en/latest/docs/software/advanced-controls/state-space/state-space-glossary.html

Original english text: 

A proportional value that relates the magnitude of an input signal to the magnitude of an output signal. In the signal-dimensional case, gain can be thought of as the proportional term of a PID controller. A gain greater than one would amplify an input signal, while a gain less than one would dampen an input signal. **A gain less than _one_ would negate the input.**

It should be:
A proportional value that relates the magnitude of an input signal to the magnitude of an output signal. In the signal-dimensional case, gain can be thought of as the proportional term of a PID controller. A gain greater than one would amplify an input signal, while a gain less than one would dampen an input signal. **A gain less than _zero_ would negate the input.**

**Comment by mcm001** [comment]
Nice catch. That's correct.
