### ISSUE TITLE
Typo in the document

### ISSUE THREAD

**Issue by RegisBKL** [wpilibsuite/frc-docs#873]
Document: https://www.transifex.com/wpilib/frc-docs/translate/#fr_CA/docs--software--advanced-controls--state-space--state-space-flywheel-walkthrough/302682238

Actual paragraph:
To rewrite this in state-space notation using :term:`system identification`, we recall from the flywheel :ref:`state-space notation example <docs/software/advanced-controls/state-space/state-space-intro:State-space Notation Example: Flywheel from kV and kA>`, where we rewrote the **folllwing** equation in terms of :math:`\mathbf{a}`.

It should be:
To rewrite this in state-space notation using :term:`system identification`, we recall from the flywheel :ref:`state-space notation example <docs/software/advanced-controls/state-space/state-space-intro:State-space Notation Example: Flywheel from kV and kA>`, where we rewrote the **following** equation in terms of :math:`\mathbf{a}`.

**Comment by Daltz333** [comment]
@msoucy

**Comment by Daltz333** [comment]
Closes in #874
