### ISSUE TITLE
Correct Term Capilization

### ISSUE THREAD

**Issue by Starlight220** [wpilibsuite/frc-docs#883]
I think some terms are miscapitalized throughout the docs. 
I found these:
- `java` {`Java`} (`What is WPILib`)
- `github`, `Github` {`GitHub`} (`What is WPILib`, `Git Version Control Introduction`)
- `linux` {`Linux`} (`Git Version Control Introduction`)
- `powershell` {`PowerShell` - this is the official capitalization but we can decide on a different one, just needs to be consistent} (`Git Version Control Introduction`)

Even if we decide on a different capitalization, it should be consistent throughout frc-docs. I think that a spellchecker was implemented precisely for this purpose - why didn't it catch these?

**Comment by Daltz333** [comment]
Misspellings isn't reliant on capitalization

**Comment by Starlight220** [comment]
Isn't the spellchecker case-sensitive?

**Comment by Daltz333** [comment]
No

**Comment by sciencewhiz** [comment]
It's not a spell checker, rather it checks a list of commonly misspelled forms of words. That's why it doesn't complain about all the unknown words.

**Comment by Daltz333** [comment]
There is a portion in the style guide about proper capitalization, this can be added there, and a "find/replace" can be done to ensure its all matching.
