### ISSUE TITLE
Add sensor delay issue to state-space debugging page

### ISSUE THREAD

**Issue by prateekma** [wpilibsuite/frc-docs#893]
Sensor delay will be a very common issue (especially with the abundance of smart motor controllers) and LQR might generate aggressive controller gains if not taken care of, resulting in excessive oscillation. This behavior and the recommended fix should be documented in the "Debugging State-Space Models and Controllers" page since we expect users to consult this document when something goes wrong.

**Comment by Daltz333** [comment]
Needs to have a code example.
