### ISSUE TITLE
Port Shuffleboard Advanced section

### ISSUE THREAD

**Issue by Kevin-OConnor** [wpilibsuite/frc-docs#90]
Shuffleboard advanced section is still missing: https://wpilib.screenstepslive.com/s/currentCS/m/shuffleboard/c/235105

Not sure that "advanced applications" is the right title for all of these, either some should move or the section should be renamed.

- [ ] Displaying camera streams
- [ ] Working with graphs
- [ ] Using record and playback
- [ ] Working with Commands and Subsystems
- [ ] Testing and tuning PID loops
- [ ] Viewing hierarchies of data

**Comment by Daltz333** [comment]
Here are my thoughts.

1. Rename Shuffleboard Getting Started to" Shuffleboard - Basics", also rename "Shuffleboard Layouts with Code" to "Shuffleboard - Layouts with Code"
- Displaying Camera Streams - Should be part of Shuffleboard basics
- Working with Graphs - Should be part of Shuffleboard basics
- Recording and Playback - Should be part of Shuffleboard basics
2. Create a section possibly called "Shuffleboard - Advanced Configuration"
- Working with Commands and Subsystems  - Goes in this section
- Testing and tuning PID loops - Goes in this section
- Viewing hierarchies of data - I can fill out this section with basic screenshots if wanted. Can also go in this section

What are your thoughts?

**Comment by Kevin-OConnor** [comment]
That sounds good to me!
