### ISSUE TITLE
Make installer docs more clear on what the select existing download vscode button in the installer does.

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/frc-docs#918]
People will assume this button is used to select an existing copy of vscode, which is not the case.

**Comment by Starlight220** [comment]
Generally, it needs to be clear that that VS Code options in the installer refer to VS Code installers, and decide what installer is run when the `VS Code` checkbox is selected at the end page of the installer.

**Comment by Daltz333** [comment]
No external installer is ran, see my comments on your PR.
