### ISSUE TITLE
Document map xbox button in simulation

### ISSUE THREAD

**Issue by agasser** [wpilibsuite/frc-docs#926]
**Describe the bug**
XBox controller axes do not have the correct index values in the simulator. The values differ from what the Driver Station displays and when the XBoxController class returns.

| Axis | DS Index | Sim Index|
| ------ | ------ | ------ |
| L X | 0 | 0 |
| L Y | 1 | 1 |
| L Trigger | 2 | 4 |
| R Trigger | 3 | 5 |
| R X | 4 | 2 |
| R Y | 5 | 3 |

**To Reproduce**
1. Launch the simulator
1. Drag a XBox Controller from _System Joysticks_ to _Joysticks_
1. Launch the Driver Station
1. Operate the axes and observe the difference between Driver Station and the simulator

**Expected behavior**
Driver Station and the simulator should report the same axes values.

**Screenshots**
![image](https://user-images.githubusercontent.com/1993518/98727687-f0929100-235d-11eb-93a0-0bd41b60b0f4.png)
![image](https://user-images.githubusercontent.com/1993518/98727731-03a56100-235e-11eb-88e0-10428aa8a2db.png)
![image](https://user-images.githubusercontent.com/1993518/98727771-16b83100-235e-11eb-9078-29ae1b1fc147.png)
![image](https://user-images.githubusercontent.com/1993518/98728146-b249a180-235e-11eb-86b4-cb549ce3d8ba.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java version: 11 (packaged with WPILib)

**Comment by sciencewhiz** [comment]
If it was checked by default, then the mapping would be wrong for joysticks.

**Comment by PeterJohnson** [comment]
The detection of xbox controllers vs normal joysticks is not very robust across controllers and operating systems.  However, as long as the checkbox remains, we could try to better "guess" a likely default (e.g. if "Xbox" is in the name).
