### ISSUE TITLE
Runtime Error Numpy Installation

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#943]
After installing beta2 and python 3.7.9 for characterization and running "frc-characterization drive new" I got the error: "RuntimeError: The current Numpy installation ('c:\\users\\jason\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime."

After some troubleshooting we found that this was due to numpy 1.19.4 and 'pip install numpy==1.19.3' fixed the issue.

**To Reproduce**
1. Install python 3.7.9
2. Run characterization

**Expected behavior**
Characterization launches normally.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - argcomplete==1.12.1
console-menu==0.6.0
control==0.8.3
cycler==0.10.0
frc-characterization==2021.1b1
frccontrol==2020.30
importlib-metadata==2.0.0
kiwisolver==1.3.1
Mako==1.1.3
MarkupSafe==2.0.0a1
matplotlib==3.3.3
numpy==1.19.4
packaging==20.4
pandas==1.1.4
patsy==0.5.1
Pillow==8.0.1
Pint==0.16.1
pynetworktables==2020.0.4
pyparsing==3.0.0b1
python-dateutil==2.8.1
pytz==2020.4
scipy==1.5.4
six==1.15.0
statsmodels==0.12.1
zipp==3.4.0

**Fix**
Need to add documentation [here](https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/robot-characterization/introduction.html) that explains how to fix this (pip install numpy==1.19.3)

**Comment by PeterJohnson** [comment]
As a workaround try using the 32-bit install of Python.

**Comment by Daltz333** [comment]
Closed with https://github.com/wpilibsuite/frc-characterization/pull/144
