### ISSUE TITLE
Correct StartEndCommand example

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#958]
The example for StartEndCommand should be changed because the WPILib drive commands will abort since the motor safety isn't fed. https://docs.wpilib.org/en/latest/docs/software/commandbased/convenience-features.html#startendcommand

**Comment by jasondaming** [comment]
So I think there are a couple of different ways to go with this:
- Make this for a different subsystem that wouldn't have motor safety.  Flywheel?  Intake? etc
- Turn motor safety off (I think this is a bad idea for an example)
- Others?
