### ISSUE TITLE
Restructure the Control System Hardware Overview

### ISSUE THREAD

**Issue by jasondaming** [wpilibsuite/frc-docs#967]
A common problem is that users do not know that tools exist.  Overviews in general do a good job of introducing a bunch of topics quickly but I think that in a lot of cases users don't know what to do with them or how a given component can solve their problems.  Rarely do we get "new users" that want to read everything cover to cover they want to read exactly what they need to get what they want done.  So I have 2 proposals:

- Introduce things in an example solving way and constantly link to tools that can help solve those problems
- Only overview the things that are required and do it in a way that gets them to want to learn more.  Every overview item should link to something more in depth.

### **Control System Hardware Overview:**
**Overview of Control System** - this is a good picture but only because I already know everything on this picture and where it goes.  If I actually wanted to use this picture as a new user it would be near worthless at the size it is.  Clicking on the picture should make it much bigger.  If I know to right click and open in a new tab it becomes much more useful.

**NI roboRIO** - This is their first introduction to this piece of hardware right?  This is the "brain", this is where the code is run, this controls all of the other parts of the robot etc.  We don't need to link to manuals we need them to understand what this does on their robot.  It doesn't need to cover advanced protocols and read like a spec sheet for people who have been in the controls industry for years.  It needs to simply explain things and then link them to all that other good info here: https://docs.wpilib.org/en/latest/docs/software/roborio-info/index.html?highlight=roboRIO

I will keep going but before I do I want to make sure I properly understand the purpose of the overview and that I am not missing something major as what I am proposing is a big change from what is currently there.

**Comment by jasondaming** [comment]
@Kevin-OConnor this is where I am discussing restructuring the overviews

**Comment by jasondaming** [comment]
Notes from Slack:
1. Overview page moves under Hardware (with links from Zero to Robot to it in the learn more section)
2. The motor controllers and camera get spit into a Motor Controller Overview and Camera Overview.  The control system still introduces what they are (and maybe shows a small grid of pictures of them?) but then links to the corresponding other page
3. All of the overview items are rewritten to be shorter, introductory focused, and if required with a link to a more technical full explanation
4. Additional items are included such that everything is covered.  For Control System that should be at least everything in the diagram.  For software that means a few additional tools need to be added: Pathweaver, RobotSim, and Robot Characterization to name a couple.

**Comment by Kevin-OConnor** [comment]
1. Yep, sounds right.
2. Yes, this makes sense. When this page was originally written on Screensteps a long time ago there were many less options and then they got added 1 at a time. I'm not sure if a camera overview page is even necessary, but we can see as we go.
3. Yep, this seems reasonable.
4. I'm not sure I agree with the list that was on Slack. Solenoids and Compressors are not covered for the same reason that motors aren't covered, they are actuators with many legal choices, not controllers with a strictly controlled set of legal options. The software one is definitely missing some of the more recent tools as you've noted.

**Comment by jasondaming** [comment]
4. I think we should at least mention what a solenoid or a compressor is and point them to something.  I don't think we need to include every type possible but the more common ones might make sense as long as it is reasonably small.  What about things like: Robot Signal Light, 10/15 amp baby fuses, or POE injector?

Isn't there a fixed list of what motors can be used?  Not saying we should include them but we could under a Motors Overview.  I know many of my newer students constantly get confused between a CIM, MiniCIM, and Bag.

**Comment by Kevin-OConnor** [comment]
RSL and the fuses might make sense, not sure on the PoE injector cable, could go either way.

There is a fixed list of motors but they are generally not considered control system elements just like I wouldn't consider a compressor or solenoid a control system element. Brief mentions of them may make sense as the doc is actually re-written.
