### ISSUE TITLE
How to Install FRC WPILib and VS2020 on MacBook?

### ISSUE THREAD

**Issue by ShivamVashishtha** [wpilibsuite/frc-docs#980]
I have a 2020 MacBook. Could you tell me, how we install the WPILib and VS2020 on it?

**Comment by Daltz333** [comment]
Hi! Have you followed the Mac instructions here https://docs.wpilib.org/en/stable/docs/getting-started/getting-started-frc-control-system/wpilib-setup.html?

If so, is there a problem in specific?

**Comment by ShivamVashishtha** [comment]
On the instructions, it says that the MacOS file will be downloaded in the "dmg" format. But, when I download it, it downloads in the "tar" format. So, basically I can't get the FRC VSCode application, rather, I only get the folder.

**Comment by ShivamVashishtha** [comment]
> Hi! Have you followed the Mac instructions here https://docs.wpilib.org/en/stable/docs/getting-started/getting-started-frc-control-system/wpilib-setup.html?
> 
> If so, is there a problem in specific?

On the instructions, it says that the MacOS file will be downloaded in the "dmg" format. But, when I download it, it downloads in the "tar" format. So, basically I can't get the FRC VSCode application, rather, I only get the folder.

**Comment by Daltz333** [comment]
Are you using /latest/ or /stable/. The DMG is for beta testers only. You should only be downloading a tar file.

**Comment by Daltz333** [comment]
![Screenshot_20201205-193227_Firefox.jpg](https://user-images.githubusercontent.com/10674555/101268429-a15b3880-3730-11eb-8008-f2fcd8547ca6.jpg)

**Comment by ShivamVashishtha** [comment]
Great, it works. Thanks.
