### ISSUE TITLE
Using LabVIEW Dashboard with C++/Java code needs updates

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#984]
C++ SmartDashboard calls need frc namespace
There's references that SmartDashboard classes don't support arrays, but they have for 4 years, so examples should be added.

**Comment by jasondaming** [comment]
@Kevin-OConnor I am looking to update this article and have a few questions:
1) It mentions labels.  Does the LV Dashboard expose any of the labels to be programmatically set via Network Tables?  I don't think it did before I thought you had to edit them in a custom dashboard project?
2) "RobotDrive Motors" is just an array with doubles [Front Left, Front Right, Back Left, Back Right] Correct?
3) They can populate the "Auto List" (array of strings) and recieve the "Auto Selector" (string) right?
4) Gyro is just called "Gyro" right?  Does it need to be wrapped?  Will it handle negative values correctly?
4) Any other features C++/Java teams could use reasonably easily?
