### ISSUE TITLE
Driver Station undocumented feature - override robot IP address

### ISSUE THREAD

**Issue by samneff72** [wpilibsuite/frc-docs#986]
https://www.chiefdelphi.com/t/announcing-gloworm-an-inexpensive-and-open-source-vision-module/386370/72

Can we include that the DS can have the team number overridden as an IP address to point directly at a robot to control?
3rd party equipment relies on this function, its weird that it's not documented as something like an "Advanced Feature", or a throwaway sentence "In Non Competition Use ONLY, the Team Number can be overridden by the complete Robot IP address"  

See Ethernet section of: 

https://pdocs.kauailabs.com/vmx-pi/software/vmx-pi-for-frc-2020-robot-programming/vmx-pi-for-frc-documentation/controlling-a-vmx-pi-frc-robot-using-the-frc-driver-station/

**Comment by jasondaming** [comment]
I added a note on this [page](https://docs.wpilib.org/en/latest/docs/software/driverstation/driver-station.html).  I think this situation is very rare for typical FRC use.  I think we can allow people to know it is possible but still need to make it very clear that this is not something normal users should do.

**Comment by samneff72** [comment]
Thank you!
