### ISSUE TITLE
Broken PDF

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/frc-docs#990]
http://www.cooperindustries.com/content/dam/public/bussmann/Transportation/Circuit%20Protection/resources/datasheets/BUS_Tns_DS_18X_CIRCUITBREAKER.pdf is broken

**Comment by Daltz333** [comment]
Line 183 of docs/zero-to-robot/step-1/control-system-hardware

**Comment by jasondaming** [comment]
looks like it is now Eaton and it looks like they don't have a product page for it.  Closest I could find was [here](http://www.cooperindustries.com/content/dam/public/bussmann/Transportation/Circuit%20Protection/resources/datasheets/BUS_Tns_DS_18X_CIRCUITBREAKER.pdf).  Maybe we should just link to [Andymark](https://www.andymark.com/products/120-amp-breaker)

**Comment by jasondaming** [comment]
Either way I will close this in my Control System PR.  I think this [mouser](https://www.mouser.com/datasheet/2/87/BUS_Tns_DS_18X_CIRCUITBREAKER-515519.pdf) link is best.

**Comment by Daltz333** [comment]
It should be a separate PR. I can do it if you wish.
